//! Auto-generated image format tests
//! Generated by Python script - do not edit manually

#![cfg(test)]

use crate::media::image_support::{{
    detect_format, decode_image_bytes, ImageFormat,
}};


#[test]
fn test_detect_png() {
    let bytes: &[u8] = &[137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    assert_eq!(detect_format(bytes), ImageFormat::Png);
}

#[test]
fn test_detect_jpeg() {
    let bytes: &[u8] = &[255, 216, 255, 224, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    assert_eq!(detect_format(bytes), ImageFormat::Jpeg);
}

#[test]
fn test_detect_gif87() {
    let bytes: &[u8] = &[71, 73, 70, 56, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    assert_eq!(detect_format(bytes), ImageFormat::Gif);
}

#[test]
fn test_detect_gif89() {
    let bytes: &[u8] = &[71, 73, 70, 56, 57, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    assert_eq!(detect_format(bytes), ImageFormat::Gif);
}

#[test]
fn test_detect_webp() {
    let bytes: &[u8] = &[82, 73, 70, 70, 0, 0, 0, 0, 87, 69, 66, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    assert_eq!(detect_format(bytes), ImageFormat::WebP);
}

#[test]
fn test_detect_bmp() {
    let bytes: &[u8] = &[66, 77, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    assert_eq!(detect_format(bytes), ImageFormat::Bmp);
}
