//! Auto-generated layout tests
//! Generated by Python script - do not edit manually

#![cfg(test)]

use crate::parsers::layout::{{
    layout_page, total_content_height, hit_test_link,
    LayoutItem,
}};
use crate::parsers::page_document::PageDocument;


#[test]
fn test_layout_0() {
    let html = r#"<h1>Title</h1><p>Paragraph 1</p><p>Paragraph 2</p>"#;
    let page = PageDocument::from_html("https://test.com", html);
    let blocks = layout_page(&page, 1280.0);
    assert!(blocks.len() >= 3);
    let total_h = total_content_height(&blocks);
    assert!(total_h > 0.0);
}

#[test]
fn test_layout_1() {
    let html = r#"<div><span>Hello</span> <span>World</span></div>"#;
    let page = PageDocument::from_html("https://test.com", html);
    let blocks = layout_page(&page, 800.0);
    assert!(blocks.len() >= 2);
    let total_h = total_content_height(&blocks);
    assert!(total_h > 0.0);
}
