//! Auto-generated parser tests
//! Generated by Python script - do not edit manually

#![cfg(test)]

use crate::parsers::{{
    dom_tree::parse_html,
    page_document::PageDocument,
    css_simple::CssCascade,
    css_lexer::tokenize_css,
    js_lexer::tokenize_js,
}};


#[test]
fn test_parse_simple_page_0() {
    let input = r#"<html><head><title>Test</title></head><body><h1>Hello</h1></body></html>"#;
    let nodes = parse_html(input);
    assert!(nodes.len() > 0, "Should parse HTML");
    let page = PageDocument::from_html("https://test.com", input);
    assert_eq!(page.title.as_str(), "Test");
}

#[test]
fn test_parse_with_links_1() {
    let input = r#"<a href="https://example.com">Link</a>"#;
    let nodes = parse_html(input);
    assert!(nodes.len() > 0, "Should parse HTML");
    let page = PageDocument::from_html("https://test.com", input);
    assert_eq!(page.title.as_str(), "");
}

#[test]
fn test_parse_with_images_2() {
    let input = r#"<img src="test.png" alt="Test">"#;
    let nodes = parse_html(input);
    assert!(nodes.len() > 0, "Should parse HTML");
    let page = PageDocument::from_html("https://test.com", input);
    assert_eq!(page.title.as_str(), "");
}

#[test]
fn test_parse_simple_selector_3() {
    let input = r#"body { color: red; }"#;
    let tokens = tokenize_css(input);
    assert!(tokens.len() > 0, "Should tokenize CSS");
    let cascade = CssCascade::new();
    assert!(cascade.parse(input).is_ok());
}

#[test]
fn test_parse_class_selector_4() {
    let input = r#".container { width: 100%; }"#;
    let tokens = tokenize_css(input);
    assert!(tokens.len() > 0, "Should tokenize CSS");
    let cascade = CssCascade::new();
    assert!(cascade.parse(input).is_ok());
}

#[test]
fn test_parse_simple_var_5() {
    let input = r#"let x = 42;"#;
    let tokens = tokenize_js(input);
    assert!(tokens.len() > 0, "Should tokenize JS");
}

#[test]
fn test_parse_function_6() {
    let input = r#"function foo() { return 1; }"#;
    let tokens = tokenize_js(input);
    assert!(tokens.len() > 0, "Should tokenize JS");
}
