//! WebGPU Device - Hardware abstraction
//! Generated by Python

use std::sync::Arc;
use std::sync::Mutex;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DeviceFeatures {
    pub shader_f16: bool,
    pub depth_clip_control: bool,
    pub depth32_float_stencil8: bool,
    pub timestamp_query: bool,
    pub texture_compression_bc: bool,
    pub texture_compression_etc2: bool,
    pub texture_compression_astc: bool,
    pub indirect_first_instance: bool,
    pub multiview: bool,
    pub uniform_buffer_16bit: bool,
    pub storage_buffer_16bit: bool,
    pub compute_shaders: bool,
    pub fragment_depth: bool,
}

impl Default for DeviceFeatures {
    fn default() -> Self {
        Self {
            shader_f16: false,
            depth_clip_control: true,
            depth32_float_stencil8: true,
            timestamp_query: false,
            texture_compression_bc: true,
            texture_compression_etc2: true,
            texture_compression_astc: true,
            indirect_first_instance: true,
            multiview: false,
            uniform_buffer_16bit: false,
            storage_buffer_16bit: false,
            compute_shaders: true,
            fragment_depth: true,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct DeviceLimits {
    pub max_texture_dimension_2d: u32,
    pub max_bind_groups: u32,
    pub max_uniform_buffer_binding_size: u32,
    pub max_storage_buffer_binding_size: u64,
    pub max_vertex_buffers: u32,
    pub max_buffer_size: u64,
    pub max_compute_workgroup_size_x: u32,
    pub max_compute_invocations_per_workgroup: u32,
}

impl Default for DeviceLimits {
    fn default() -> Self {
        Self {
            max_texture_dimension_2d: 8192,
            max_bind_groups: 4,
            max_uniform_buffer_binding_size: 65536,
            max_storage_buffer_binding_size: 134217728,
            max_vertex_buffers: 8,
            max_buffer_size: 268435456,
            max_compute_workgroup_size_x: 256,
            max_compute_invocations_per_workgroup: 256,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Device {
    pub name: String,
    pub vendor: String,
    pub backend: GpuBackend,
    pub features: DeviceFeatures,
    pub limits: DeviceLimits,
    pub is_fallback: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum GpuBackend {
    Vulkan,
    Metal,
    DirectX12,
    OpenGL,
    WebGPU,
}

impl GpuBackend {
    pub fn name(&self) -> &'static str {
        match self {
            GpuBackend::Vulkan => "Vulkan",
            GpuBackend::Metal => "Metal",
            GpuBackend::DirectX12 => "DirectX 12",
            GpuBackend::OpenGL => "OpenGL",
            GpuBackend::WebGPU => "WebGPU",
        }
    }
}

impl Device {
    pub fn new(name: &str, vendor: &str, backend: GpuBackend) -> Self {
        Self {
            name: name.to_string(),
            vendor: vendor.to_string(),
            backend,
            features: DeviceFeatures::default(),
            limits: DeviceLimits::default(),
            is_fallback: false,
        }
    }

    pub fn fallback() -> Self {
        Self {
            name: "Software Renderer".to_string(),
            vendor: "Noir Browser".to_string(),
            backend: GpuBackend::WebGPU,
            features: DeviceFeatures::default(),
            limits: DeviceLimits::default(),
            is_fallback: true,
        }
    }

    /// Check if device supports compute shaders
    pub fn supports_compute(&self) -> bool {
        self.features.compute_shaders && !self.is_fallback
    }

    /// Check if device supports texture compression
    pub fn supports_compression(&self) -> bool {
        self.features.texture_compression_bc && !self.is_fallback
    }

    /// Get device info as string
    pub fn info(&self) -> String {
        format!("{} ({}) - {}", self.name, self.backend.name(), self.vendor)
    }
}

/// Request adapter info
pub struct AdapterInfo {
    pub devices: Vec<Device>,
}

impl AdapterInfo {
    /// Request the best available GPU adapter
    pub fn request_best() -> Self {
        let mut devices = Vec::new();

        // Try to detect available backends
        #[cfg(target_os = "windows")]
        {
            devices.push(Device::new("NVIDIA RTX", "NVIDIA", GpuBackend::DirectX12));
            devices.push(Device::new("AMD Radeon", "AMD", GpuBackend::DirectX12));
            devices.push(Device::new("Intel HD Graphics", "Intel", GpuBackend::DirectX12));
        }

        #[cfg(target_os = "linux")]
        {
            devices.push(Device::new("NVIDIA RTX", "NVIDIA", GpuBackend::Vulkan));
            devices.push(Device::new("AMD Radeon", "AMD", GpuBackend::Vulkan));
            devices.push(Device::new("Intel HD Graphics", "Intel", GpuBackend::Vulkan));
        }

        #[cfg(target_os = "macos")]
        {
            devices.push(Device::new("Apple GPU", "Apple", GpuBackend::Metal));
        }

        if devices.is_empty() {
            devices.push(Device::fallback());
        }

        Self { devices }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_device_creation() {
        let device = Device::new("Test GPU", "Test Vendor", GpuBackend::Vulkan);
        assert_eq!(device.name, "Test GPU");
        assert!(device.supports_compute());
    }

    #[test]
    fn test_fallback_device() {
        let device = Device::fallback();
        assert!(!device.supports_compute());
        assert!(device.is_fallback);
    }

    #[test]
    fn test_backend_name() {
        assert_eq!(GpuBackend::Vulkan.name(), "Vulkan");
        assert_eq!(GpuBackend::Metal.name(), "Metal");
        assert_eq!(GpuBackend::DirectX12.name(), "DirectX 12");
    }
}
