//! WebGPU Module - GPU acceleration for Noir Browser
//! Generated by Python
//!
//! Multi-backend support:
//! - Windows: DirectX 12, Vulkan
//! - Linux: Vulkan, OpenGL
//! - macOS: Metal
//! - Android: Vulkan, OpenGL
//!
//! Features:
//! - 2D rendering pipeline
//! - Compute shaders
//! - Texture management
//! - Bridge to JS engine v3

#![allow(dead_code)]

pub mod device;
pub mod pipeline;
pub mod shaders;
pub mod buffer;
pub mod texture;
pub mod renderer;
pub mod bridge;
pub mod compute;
pub mod pwa;

pub use device::{Device, DeviceFeatures, DeviceLimits};
pub use pipeline::{Pipeline, PipelineConfig, PrimitiveTopology};
pub use shaders::{ShaderModule, ShaderStage};
pub use buffer::{Buffer, BufferUsage, VertexFormat};
pub use texture::{Texture, TextureFormat, TextureUsage};
pub use renderer::Renderer;
pub use bridge::JsBridge;
pub use compute::ComputePipeline;
pub use pwa::{PwaManager, ServiceWorker, Manifest};
