//! PWA (Progressive Web App) Support
//! Generated by Python

use std::collections::HashMap;

/// Web App Manifest
#[derive(Debug, Clone)]
pub struct Manifest {
    pub name: String,
    pub short_name: String,
    pub start_url: String,
    pub display: DisplayMode,
    pub background_color: String,
    pub theme_color: String,
    pub icons: Vec<Icon>,
    pub description: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DisplayMode {
    Fullscreen,
    Standalone,
    MinimalUi,
    Browser,
}

impl DisplayMode {
    pub fn as_str(&self) -> &'static str {
        match self {
            DisplayMode::Fullscreen => "fullscreen",
            DisplayMode::Standalone => "standalone",
            DisplayMode::MinimalUi => "minimal-ui",
            DisplayMode::Browser => "browser",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Icon {
    pub src: String,
    pub sizes: String,
    pub icon_type: String,
    pub purpose: Option<String>,
}

impl Manifest {
    pub fn new(name: &str, short_name: &str, start_url: &str) -> Self {
        Self {
            name: name.to_string(),
            short_name: short_name.to_string(),
            start_url: start_url.to_string(),
            display: DisplayMode::Standalone,
            background_color: "#1a1a1a".to_string(),
            theme_color: "#ff3344".to_string(),
            icons: Vec::new(),
            description: None,
        }
    }

    pub fn to_json(&self) -> String {
        let mut json = String::from("{");
        json.push_str(&format!("\"name\": \"{}\",", self.name));
        json.push_str(&format!("\"short_name\": \"{}\",", self.short_name));
        json.push_str(&format!("\"start_url\": \"{}\",", self.start_url));
        json.push_str(&format!("\"display\": \"{}\",", self.display.as_str()));
        json.push_str(&format!("\"background_color\": \"{}\",", self.background_color));
        json.push_str(&format!("\"theme_color\": \"{}\",", self.theme_color));
        if let Some(desc) = &self.description {
            json.push_str(&format!("\"description\": \"{}\",", desc));
        }
        if !self.icons.is_empty() {
            json.push_str("\"icons\": [");
            for (i, icon) in self.icons.iter().enumerate() {
                if i > 0 { json.push(','); }
                json.push_str(&format!(
                    "{{\"src\": \"{}\", \"sizes\": \"{}\", \"type\": \"{}\"}}",
                    icon.src, icon.sizes, icon.icon_type
                ));
            }
            json.push(']');
        }
        json.push('}');
        json
    }
}

/// Service Worker registration
pub struct ServiceWorker {
    pub scope: String,
    pub script_url: String,
    pub state: ServiceWorkerState,
    pub active: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ServiceWorkerState {
    Installing,
    Installed,
    Activating,
    Activated,
    Redundant,
}

impl ServiceWorker {
    pub fn new(scope: &str, script_url: &str) -> Self {
        Self {
            scope: scope.to_string(),
            script_url: script_url.to_string(),
            state: ServiceWorkerState::Installing,
            active: false,
        }
    }
}

/// Cache for offline support
pub struct CacheStorage {
    pub caches: HashMap<String, Cache>,
}

pub struct Cache {
    pub name: String,
    pub requests: Vec<CachedRequest>,
}

#[derive(Debug, Clone)]
pub struct CachedRequest {
    pub url: String,
    pub response: String,
    pub timestamp: u64,
    pub max_age: u64,
}

impl CacheStorage {
    pub fn new() -> Self {
        Self { caches: HashMap::new() }
    }

    pub fn open(&mut self, name: &str) -> &mut Cache {
        self.caches.entry(name.to_string()).or_insert_with(|| Cache {
            name: name.to_string(),
            requests: Vec::new(),
        })
    }

    pub fn match_url(&self, name: &str, url: &str) -> Option<&CachedRequest> {
        self.caches.get(name)?.requests.iter().find(|r| r.url == url)
    }
}

impl Default for CacheStorage {
    fn default() -> Self {
        Self::new()
    }
}

/// PWA Manager - Coordinates PWA features
pub struct PwaManager {
    pub manifest: Option<Manifest>,
    pub service_workers: Vec<ServiceWorker>,
    pub cache_storage: CacheStorage,
    pub install_prompt_shown: bool,
    pub can_install: bool,
    pub offline_mode: bool,
}

impl PwaManager {
    pub fn new() -> Self {
        Self {
            manifest: None,
            service_workers: Vec::new(),
            cache_storage: CacheStorage::new(),
            install_prompt_shown: false,
            can_install: false,
            offline_mode: false,
        }
    }

    /// Set the web app manifest
    pub fn set_manifest(&mut self, manifest: Manifest) {
        self.manifest = Some(manifest);
    }

    /// Register a service worker
    pub fn register_service_worker(&mut self, scope: &str, script_url: &str) -> u64 {
        let id = self.service_workers.len() as u64;
        self.service_workers.push(ServiceWorker::new(scope, script_url));
        id
    }

    /// Show install prompt (simulated)
    pub fn show_install_prompt(&mut self) -> bool {
        if self.can_install && !self.install_prompt_shown {
            self.install_prompt_shown = true;
            true
        } else {
            false
        }
    }

    /// Enable offline mode
    pub fn enable_offline(&mut self) {
        self.offline_mode = true;
    }

    /// Cache a response
    pub fn cache_response(&mut self, cache_name: &str, url: &str, response: &str) {
        let cache = self.cache_storage.open(cache_name);
        cache.requests.push(CachedRequest {
            url: url.to_string(),
            response: response.to_string(),
            timestamp: 0,
            max_age: 86400, // 24 hours
        });
    }

    /// Get cached response
    pub fn get_cached(&self, cache_name: &str, url: &str) -> Option<String> {
        self.cache_storage.match_url(cache_name, url).map(|r| r.response.clone())
    }

    /// Get statistics
    pub fn stats(&self) -> PwaStats {
        PwaStats {
            has_manifest: self.manifest.is_some(),
            service_worker_count: self.service_workers.len(),
            cache_count: self.cache_storage.caches.len(),
            cached_request_count: self.cache_storage.caches.values()
                .map(|c| c.requests.len() as u64)
                .sum(),
            can_install: self.can_install,
            offline_mode: self.offline_mode,
        }
    }
}

#[derive(Debug, Clone)]
pub struct PwaStats {
    pub has_manifest: bool,
    pub service_worker_count: usize,
    pub cache_count: usize,
    pub cached_request_count: u64,
    pub can_install: bool,
    pub offline_mode: bool,
}

impl Default for PwaManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_manifest() {
        let mut m = Manifest::new("Noir Browser", "Noir", "/");
        m.display = DisplayMode::Standalone;
        let json = m.to_json();
        assert!(json.contains("Noir Browser"));
    }

    #[test]
    fn test_service_worker() {
        let mut pm = PwaManager::new();
        let id = pm.register_service_worker("/", "/sw.js");
        assert_eq!(id, 0);
    }

    #[test]
    fn test_cache() {
        let mut cs = CacheStorage::new();
        cs.open("v1").requests.push(CachedRequest {
            url: "/test".to_string(),
            response: "cached".to_string(),
            timestamp: 0,
            max_age: 3600,
        });
        assert!(cs.match_url("v1", "/test").is_some());
    }
}
