//! WebGPU Renderer - 2D rendering pipeline
//! Generated by Python

use super::device::Device;
use super::buffer::{Buffer, BufferUsage, VertexFormat};
use super::texture::{Texture, TextureFormat, TextureUsage};
use super::pipeline::{Pipeline, PipelineConfig, PrimitiveTopology};
use super::shaders::{ShaderModule, create_standard_shaders};

/// 2D vertex with position, color, and optional texture coords
#[repr(C)]
#[derive(Copy, Clone, Debug)]
pub struct Vertex2D {
    pub position: [f32; 2],
    pub color: [f32; 4],
    pub tex_coords: [f32; 2],
}

impl Vertex2D {
    pub fn new(x: f32, y: f32, r: f32, g: f32, b: f32, a: f32) -> Self {
        Self {
            position: [x, y],
            color: [r, g, b, a],
            tex_coords: [0.0, 0.0],
        }
    }

    pub fn with_tex_coords(mut self, u: f32, v: f32) -> Self {
        self.tex_coords = [u, v];
        self
    }
}

/// Uniform buffer for view-projection matrix
#[repr(C)]
#[derive(Copy, Clone, Debug)]
pub struct Uniforms {
    pub view_proj: [[f32; 4]; 4],
}

impl Uniforms {
    pub fn orthographic(width: f32, height: f32) -> Self {
        // Simple orthographic projection for 2D
        let l = 0.0;
        let r = width;
        let b = height;
        let t = 0.0;
        let n = -1.0;
        let f = 1.0;

        let view_proj = [
            [2.0 / (r - l), 0.0, 0.0, 0.0],
            [0.0, 2.0 / (t - b), 0.0, 0.0],
            [0.0, 0.0, 1.0 / (f - n), 0.0],
            [(l + r) / (l - r), (b + t) / (b - t), n / (n - f), 1.0],
        ];

        Self { view_proj }
    }

    pub fn identity() -> Self {
        Self {
            view_proj: [
                [1.0, 0.0, 0.0, 0.0],
                [0.0, 1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0, 0.0],
                [0.0, 0.0, 0.0, 1.0],
            ],
        }
    }
}

/// Main renderer for 2D graphics
pub struct Renderer {
    pub device: Device,
    pub vertex_buffer: Option<Buffer>,
    pub index_buffer: Option<Buffer>,
    pub uniform_buffer: Option<Buffer>,
    pub main_pipeline: Option<Pipeline>,
    pub text_pipeline: Option<Pipeline>,
    pub image_pipeline: Option<Pipeline>,
    pub vertex_count: u32,
    pub index_count: u32,
    pub frame_count: u64,
    pub draw_calls: u64,
    pub triangles_rendered: u64,
}

impl Renderer {
    pub fn new(device: Device) -> Self {
        Self {
            device,
            vertex_buffer: None,
            index_buffer: None,
            uniform_buffer: None,
            main_pipeline: None,
            text_pipeline: None,
            image_pipeline: None,
            vertex_count: 0,
            index_count: 0,
            frame_count: 0,
            draw_calls: 0,
            triangles_rendered: 0,
        }
    }

    /// Initialize the renderer (compile shaders, create buffers)
    pub fn init(&mut self) {
        // Create vertex buffer
        self.vertex_buffer = Some(Buffer::new(
            1,
            1024 * 1024, // 1MB
            BufferUsage::vertex_and_index(),
        ).with_label("Vertex Buffer"));

        // Create index buffer
        self.index_buffer = Some(Buffer::new(
            2,
            256 * 1024, // 256KB
            BufferUsage::index_buffer(),
        ).with_label("Index Buffer"));

        // Create uniform buffer
        self.uniform_buffer = Some(Buffer::new(
            3,
            256,
            BufferUsage::uniform_buffer(),
        ).with_label("Uniform Buffer"));

        // Create pipelines
        self.main_pipeline = Some(Pipeline::new(1, PipelineConfig::default()));

        let text_config = PipelineConfig {
            name: "text".to_string(),
            vertex_format: VertexFormat::basic_2d(),
            topology: PrimitiveTopology::TriangleStrip,
            ..Default::default()
        };
        self.text_pipeline = Some(Pipeline::new(2, text_config));

        let image_config = PipelineConfig {
            name: "image".to_string(),
            vertex_format: VertexFormat::textured_2d(),
            topology: PrimitiveTopology::TriangleList,
            ..Default::default()
        };
        self.image_pipeline = Some(Pipeline::new(3, image_config));
    }

    /// Begin a new frame
    pub fn begin_frame(&mut self) {
        self.frame_count += 1;
        self.draw_calls = 0;
        self.triangles_rendered = 0;
    }

    /// Draw a colored rectangle
    pub fn draw_rect(&mut self, x: f32, y: f32, w: f32, h: f32, r: f32, g: f32, b: f32, a: f32) {
        // Create 4 vertices for the quad
        let v0 = Vertex2D::new(x, y, r, g, b, a);
        let v1 = Vertex2D::new(x + w, y, r, g, b, a);
        let v2 = Vertex2D::new(x + w, y + h, r, g, b, a);
        let v3 = Vertex2D::new(x, y + h, r, g, b, a);

        let _ = (v0, v1, v2, v3); // Would be added to vertex buffer
        self.triangles_rendered += 2; // 2 triangles per quad
        self.draw_calls += 1;
    }

    /// Draw a textured quad (for images)
    pub fn draw_textured(&mut self, x: f32, y: f32, w: f32, h: f32, texture: &Texture) {
        let _ = (x, y, w, h, texture);
        self.draw_calls += 1;
        self.triangles_rendered += 2;
    }

    /// Draw text (glyphs)
    pub fn draw_text(&mut self, x: f32, y: f32, text: &str, color: [f32; 4], size: f32) {
        let char_width = size * 0.6;
        let mut cx = x;
        for _ch in text.chars() {
            // Each character is a quad
            self.draw_rect(cx, y, char_width, size, color[0], color[1], color[2], color[3]);
            cx += char_width;
        }
    }

    /// End frame and present
    pub fn end_frame(&mut self) {
        // Would call wgpu::Queue::submit here
    }

    /// Get statistics
    pub fn stats(&self) -> RendererStats {
        RendererStats {
            frame_count: self.frame_count,
            draw_calls: self.draw_calls,
            triangles_rendered: self.triangles_rendered,
            vertex_count: self.vertex_count,
            backend: self.device.backend.name().to_string(),
            device: self.device.name.clone(),
            is_fallback: self.device.is_fallback,
        }
    }
}

#[derive(Debug, Clone)]
pub struct RendererStats {
    pub frame_count: u64,
    pub draw_calls: u64,
    pub triangles_rendered: u64,
    pub vertex_count: u32,
    pub backend: String,
    pub device: String,
    pub is_fallback: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vertex_creation() {
        let v = Vertex2D::new(10.0, 20.0, 1.0, 0.0, 0.0, 1.0);
        assert_eq!(v.position[0], 10.0);
        assert_eq!(v.position[1], 20.0);
        assert_eq!(v.color[0], 1.0);
    }

    #[test]
    fn test_orthographic_projection() {
        let proj = Uniforms::orthographic(800.0, 600.0);
        // Check that it's a valid matrix
        assert_eq!(proj.view_proj[3][3], 1.0);
    }

    #[test]
    fn test_renderer_init() {
        let device = Device::new("Test", "Test", super::super::device::GpuBackend::Vulkan);
        let mut renderer = Renderer::new(device);
        renderer.init();
        assert!(renderer.vertex_buffer.is_some());
        assert!(renderer.main_pipeline.is_some());
    }

    #[test]
    fn test_renderer_draw() {
        let device = Device::fallback();
        let mut renderer = Renderer::new(device);
        renderer.init();
        renderer.begin_frame();
        renderer.draw_rect(0.0, 0.0, 100.0, 100.0, 1.0, 0.0, 0.0, 1.0);
        renderer.end_frame();
        let stats = renderer.stats();
        assert_eq!(stats.draw_calls, 1);
        assert_eq!(stats.triangles_rendered, 2);
    }
}
