//! WebGPU Shaders - WGSL shader modules
//! Generated by Python

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ShaderStage {
    Vertex,
    Fragment,
    Compute,
}

impl ShaderStage {
    pub fn name(&self) -> &'static str {
        match self {
            ShaderStage::Vertex => "Vertex",
            ShaderStage::Fragment => "Fragment",
            ShaderStage::Compute => "Compute",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ShaderModule {
    pub name: String,
    pub stage: ShaderStage,
    pub code: String,
    pub entry_point: String,
}

impl ShaderModule {
    pub fn new(name: &str, stage: ShaderStage, code: &str, entry_point: &str) -> Self {
        Self {
            name: name.to_string(),
            stage,
            code: code.to_string(),
            entry_point: entry_point.to_string(),
        }
    }
}

/// WGSL shader for 2D text/rectangle rendering
pub const SHADER_2D_WGSL: &str = r#"
// Vertex shader for 2D rendering
struct VertexInput {
    @location(0) position: vec2<f32>,
    @location(1) color: vec4<f32>,
    @location(2) tex_coords: vec2<f32>,
};

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) color: vec4<f32>,
    @location(1) tex_coords: vec2<f32>,
};

struct Uniforms {
    view_proj: mat4x4<f32>,
};

@group(0) @binding(0)
var<uniform> uniforms: Uniforms;

@vertex
fn vs_main(input: VertexInput) -> VertexOutput {
    var out: VertexOutput;
    out.clip_position = uniforms.view_proj * vec4<f32>(input.position, 0.0, 1.0);
    out.color = input.color;
    out.tex_coords = input.tex_coords;
    return out;
}

// Fragment shader
@group(1) @binding(0)
var texture_sampler: sampler;

@group(1) @binding(1)
var texture_data: texture_2d<f32>;

@fragment
fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> {
    let tex_color = textureSample(texture_data, texture_sampler, input.tex_coords);
    return input.color * tex_color;
}
"#;

/// WGSL shader for solid color rendering
pub const SHADER_SOLID_WGSL: &str = r#"
struct VertexInput {
    @location(0) position: vec2<f32>,
    @location(1) color: vec4<f32>,
};

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) color: vec4<f32>,
};

struct Uniforms {
    view_proj: mat4x4<f32>,
};

@group(0) @binding(0)
var<uniform> uniforms: Uniforms;

@vertex
fn vs_main(input: VertexInput) -> VertexOutput {
    var out: VertexOutput;
    out.clip_position = uniforms.view_proj * vec4<f32>(input.position, 0.0, 1.0);
    out.color = input.color;
    return out;
}

@fragment
fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> {
    return input.color;
}
"#;

/// WGSL compute shader for image processing
pub const SHADER_IMAGE_PROCESS_WGSL: &str = r#"
struct ImageParams {
    width: u32,
    height: u32,
    blur_radius: f32,
};

@group(0) @binding(0)
var input_texture: texture_2d<f32>;

@group(0) @binding(1)
var output_texture: texture_storage_2d<rgba8unorm, write>;

@group(0) @binding(2)
var<uniform> params: ImageParams;

@compute @workgroup_size(8, 8, 1)
fn cs_main(@builtin(global_invocation_id) gid: vec3<u32>) {
    let coords = vec2<i32>(i32(gid.x), i32(gid.y));
    if (coords.x >= i32(params.width) || coords.y >= i32(params.height)) {
        return;
    }

    var color = vec4<f32>(0.0, 0.0, 0.0, 0.0);
    var count = 0.0;

    // Simple box blur
    for (var dy = -5; dy <= 5; dy = dy + 1) {
        for (var dx = -5; dx <= 5; dx = dx + 1) {
            let sample_coords = coords + vec2<i32>(dx, dy);
            if (sample_coords.x >= 0 && sample_coords.x < i32(params.width) &&
                sample_coords.y >= 0 && sample_coords.y < i32(params.height)) {
                let sample = textureLoad(input_texture, sample_coords, 0);
                color = color + vec4<f32>(sample.r, sample.g, sample.b, sample.a);
                count = count + 1.0;
            }
        }
    }

    let result = color / vec4<f32>(count, count, count, count);
    textureStore(output_texture, coords, result);
}
"#;

/// Create standard shader modules
pub fn create_standard_shaders() -> Vec<ShaderModule> {
    vec![
        ShaderModule::new("2d_vertex", ShaderStage::Vertex, SHADER_2D_WGSL, "vs_main"),
        ShaderModule::new("2d_fragment", ShaderStage::Fragment, SHADER_2D_WGSL, "fs_main"),
        ShaderModule::new("solid", ShaderStage::Vertex, SHADER_SOLID_WGSL, "vs_main"),
        ShaderModule::new("image_process", ShaderStage::Compute, SHADER_IMAGE_PROCESS_WGSL, "cs_main"),
    ]
}
