//! Auto-generated WASM Decoder
//! Generated by Python - do not edit manually

use super::reader::Reader;
use super::types::*;

const WASM_MAGIC: [u8; 4] = [0x00, 0x61, 0x73, 0x6D];
const WASM_VERSION: [u8; 4] = [0x01, 0x00, 0x00, 0x00];

#[derive(Debug, Clone)]
pub struct Module {
    pub types: Vec<FuncType>,
    pub imports: Vec<Import>,
    pub functions: Vec<u32>, // type indices
    pub memories: Vec<MemoryType>,
    pub globals: Vec<Global>,
    pub exports: Vec<Export>,
    pub start: Option<u32>,
    pub table: Vec<u32>, // type indices
    pub code: Vec<FunctionBody>,
    pub data: Vec<DataSegment>,
}

#[derive(Debug, Clone)]
pub struct Global {
    pub ty: GlobalType,
    pub init: Vec<u8>, // init expr
}

#[derive(Debug, Clone)]
pub struct FunctionBody {
    pub locals: Vec<(u32, ValueType)>,
    pub code: Vec<u8>,
}

#[derive(Debug, Clone)]
pub struct DataSegment {
    pub memory_index: u32,
    pub offset: Vec<u8>,
    pub data: Vec<u8>,
}

pub struct Decoder<'a> {
    reader: Reader<'a>,
}

impl<'a> Decoder<'a> {
    pub fn new(bytes: &'a [u8]) -> Self {
        Self {
            reader: Reader::new(bytes),
        }
    }

    pub fn decode(mut self) -> WasmResult<Module> {
        // Magic number
        let magic = self.reader.read_bytes(4)?;
        if magic != WASM_MAGIC {
            return Err(WasmError::InvalidMagic);
        }

        // Version
        let version = self.reader.read_bytes(4)?;
        if version != WASM_VERSION {
            return Err(WasmError::InvalidVersion);
        }

        let mut module = Module {
            types: Vec::new(),
            imports: Vec::new(),
            functions: Vec::new(),
            memories: Vec::new(),
            globals: Vec::new(),
            exports: Vec::new(),
            start: None,
            table: Vec::new(),
            code: Vec::new(),
            data: Vec::new(),
        };

        // Sections
        while self.reader.remaining() > 0 {
            let section_id = self.reader.read_u8()?;
            let _section_size = self.reader.read_leb128_u32()?;

            match section_id {
                1 => module.types = self.read_type_section()?,
                2 => module.imports = self.read_import_section()?,
                3 => module.functions = self.read_function_section()?,
                4 => module.table = self.read_table_section()?,
                5 => module.memories = self.read_memory_section()?,
                6 => module.globals = self.read_global_section()?,
                7 => module.exports = self.read_export_section()?,
                8 => module.start = self.read_start_section()?,
                9 => module.code = self.read_code_section()?,
                10 => module.data = self.read_data_section()?,
                _ => {
                    // Skip unknown section
                    let size = self.reader.read_leb128_u32()? as usize;
                    self.reader.read_bytes(size)?;
                }
            }
        }

        Ok(module)
    }

    fn read_type_section(&mut self) -> WasmResult<Vec<FuncType>> {
        self.reader.read_vector(|r| {
            r.read_u8()?; // function type marker (0x60)
            let params = r.read_vector(Self::read_value_type)?;
            let results = r.read_vector(Self::read_value_type)?;
            Ok(FuncType { params, results })
        })
    }

    fn read_value_type(reader: &mut Reader) -> WasmResult<ValueType> {
        match reader.read_u8()? {
            0x7F => Ok(ValueType::I32),
            0x7E => Ok(ValueType::I64),
            0x7D => Ok(ValueType::F32),
            0x7C => Ok(ValueType::F64),
            0x7B => Ok(ValueType::V128),
            0x70 => Ok(ValueType::FuncRef),
            0x6F => Ok(ValueType::ExternRef),
            t => Err(WasmError::InvalidValueType(t)),
        }
    }

    fn read_import_section(&mut self) -> WasmResult<Vec<Import>> {
        self.reader.read_vector(|r| {
            let module = r.read_name()?;
            let field = r.read_name()?;
            let kind_byte = r.read_u8()?;
            let kind = match kind_byte {
                0x00 => ExternalKind::Function(r.read_leb128_u32()?),
                0x01 => {
                    let _ = Self::read_value_type(r)?;
                    let _ = r.read_leb128_u32()?; // limits min
                    ExternalKind::Table
                }
                0x02 => {
                    let _ = r.read_leb128_u32()?; // limits min
                    ExternalKind::Memory
                }
                0x03 => {
                    let _ = Self::read_value_type(r)?;
                    r.read_u8()?; // mut
                    ExternalKind::Global
                }
                _ => return Err(WasmError::Validation("Invalid import kind".to_string())),
            };
            Ok(Import { module, field, kind })
        })
    }

    fn read_function_section(&mut self) -> WasmResult<Vec<u32>> {
        self.reader.read_vector(|r| r.read_leb128_u32())
    }

    fn read_table_section(&mut self) -> WasmResult<Vec<u32>> {
        self.reader.read_vector(|r| {
            let _ = Self::read_value_type(r)?;
            r.read_leb128_u32()?;
            Ok(0)
        })
    }

    fn read_memory_section(&mut self) -> WasmResult<Vec<MemoryType>> {
        self.reader.read_vector(|r| {
            let flags = r.read_u8()?;
            let min = r.read_leb128_u32()?;
            let max = if flags & 0x01 != 0 {
                Some(r.read_leb128_u32()?)
            } else {
                None
            };
            Ok(MemoryType { limits: Limits { min, max } })
        })
    }

    fn read_global_section(&mut self) -> WasmResult<Vec<Global>> {
        self.reader.read_vector(|r| {
            let value_type = Self::read_value_type(r)?;
            let mutable = r.read_u8()? != 0;
            let init_size = r.read_leb128_u32()? as usize;
            let init = r.read_bytes(init_size)?.to_vec();
            Ok(Global {
                ty: GlobalType { value_type, mutable },
                init,
            })
        })
    }

    fn read_export_section(&mut self) -> WasmResult<Vec<Export>> {
        self.reader.read_vector(|r| {
            let name = r.read_name()?;
            let kind_byte = r.read_u8()?;
            let index = r.read_leb128_u32()?;
            let kind = match kind_byte {
                0x00 => ExternalKind::Function(index),
                0x01 => ExternalKind::Table,
                0x02 => ExternalKind::Memory,
                0x03 => ExternalKind::Global,
                _ => return Err(WasmError::Validation("Invalid export kind".to_string())),
            };
            Ok(Export { name, kind })
        })
    }

    fn read_start_section(&mut self) -> WasmResult<Option<u32>> {
        let idx = self.reader.read_leb128_u32()?;
        Ok(Some(idx))
    }

    fn read_code_section(&mut self) -> WasmResult<Vec<FunctionBody>> {
        self.reader.read_vector(|r| {
            let body_size = r.read_leb128_u32()? as usize;
            let _body_start = r.pos();
            let locals = r.read_vector(|r2| {
                let count = r2.read_leb128_u32()?;
                let ty = Self::read_value_type(r2)?;
                Ok((count, ty))
            })?;
            let remaining = body_size - (r.pos() - _body_start);
            let code = r.read_bytes(remaining)?.to_vec();
            Ok(FunctionBody { locals, code })
        })
    }

    fn read_data_section(&mut self) -> WasmResult<Vec<DataSegment>> {
        self.reader.read_vector(|r| {
            let flags = r.read_u8()?;
            let memory_index = if flags & 0x02 != 0 {
                r.read_leb128_u32()?
            } else {
                0
            };
            let offset_size = r.read_leb128_u32()? as usize;
            let offset = r.read_bytes(offset_size)?.to_vec();
            let data = r.read_vector(|r2| r2.read_u8())?;
            Ok(DataSegment { memory_index, offset, data })
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_decode_magic() {
        // Minimal WASM module: (module)
        let wasm = vec![0x00, 0x61, 0x73, 0x6D, 0x01, 0x00, 0x00, 0x00];
        let decoder = Decoder::new(&wasm);
        let result = decoder.decode();
        assert!(result.is_ok());
    }

    #[test]
    fn test_decode_invalid_magic() {
        let wasm = vec![0xFF, 0xFF, 0xFF, 0xFF, 0x01, 0x00, 0x00, 0x00];
        let decoder = Decoder::new(&wasm);
        let result = decoder.decode();
        assert!(result.is_err());
    }
}
