//! Auto-generated WASM Executor
//! Generated by Python - do not edit manually

use super::types::*;
use super::decoder::*;
use std::collections::HashMap;

pub struct Instance {
    pub module: Module,
    pub memory: Vec<u8>,
    pub globals: Vec<Value>,
    pub functions: HashMap<String, Value>,
    pub stack: Vec<Value>,
}

impl Instance {
    pub fn new(module: Module) -> Self {
        let mut globals = Vec::new();
        for global in &module.globals {
            globals.push(Value::I32(0)); // Simplified
        }

        let mut memory = Vec::new();
        for mem in &module.memories {
            let size = (mem.limits.min as usize) * 65536;
            memory = vec![0; size];
        }

        let mut functions = HashMap::new();
        for (i, export) in module.exports.iter().enumerate() {
            if let ExternalKind::Function(idx) = export.kind {
                functions.insert(export.name.clone(), Value::I32(idx as i32));
            }
        }

        Self {
            module,
            memory,
            globals,
            functions,
            stack: Vec::new(),
        }
    }

    pub fn call(&mut self, name: &str, args: &[Value]) -> WasmResult<Vec<Value>> {
        if let Some(func_idx) = self.functions.get(name).cloned() {
            if let Value::I32(idx) = func_idx {
                self.call_function(idx as u32, args)
            } else {
                Err(WasmError::Trap("Not a function".to_string()))
            }
        } else {
            Err(WasmError::Trap(format!("Function not found: {}", name)))
        }
    }

    fn call_function(&mut self, func_idx: u32, args: &[Value]) -> WasmResult<Vec<Value>> {
        let body = self.module.code.get(func_idx as usize)
            .ok_or(WasmError::InvalidFunction(func_idx))?
            .clone();

        let func_type_idx = self.module.functions.get(func_idx as usize)
            .copied()
            .ok_or(WasmError::InvalidFunction(func_idx))?;
        let func_type = self.module.types.get(func_type_idx as usize)
            .ok_or(WasmError::Validation("Invalid type index".to_string()))?
            .clone();

        // Push args onto stack
        for arg in args {
            self.stack.push(arg.clone());
        }

        // Execute bytecode
        self.execute(&body.code)?;

        // Pop results
        let mut results = Vec::new();
        for _ in &func_type.results {
            results.push(self.stack.pop().unwrap_or(Value::I32(0)));
        }
        results.reverse();

        Ok(results)
    }

    fn execute(&mut self, code: &[u8]) -> WasmResult<()> {
        let mut pc = 0;
        let mut locals: Vec<Value> = Vec::new();
        let mut blocks: Vec<BlockFrame> = Vec::new();

        while pc < code.len() {
            let opcode = code[pc];
            pc += 1;

            match opcode {
                0x00 => {
                    // unreachable
                    return Err(WasmError::Trap("unreachable".to_string()));
                }
                0x01 => {
                    // nop
                }
                0x41 => {
                    // i32.const
                    let (val, new_pc) = self.read_leb128_i32(code, pc)?;
                    self.stack.push(Value::I32(val));
                    pc = new_pc;
                }
                0x6A => {
                    // i32.add
                    let b = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    let a = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    if let (Value::I32(x), Value::I32(y)) = (a, b) {
                        self.stack.push(Value::I32(x.wrapping_add(y)));
                    } else {
                        return Err(WasmError::Trap("Type mismatch".to_string()));
                    }
                }
                0x6B => {
                    // i32.sub
                    let b = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    let a = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    if let (Value::I32(x), Value::I32(y)) = (a, b) {
                        self.stack.push(Value::I32(x.wrapping_sub(y)));
                    } else {
                        return Err(WasmError::Trap("Type mismatch".to_string()));
                    }
                }
                0x6C => {
                    // i32.mul
                    let b = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    let a = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    if let (Value::I32(x), Value::I32(y)) = (a, b) {
                        self.stack.push(Value::I32(x.wrapping_mul(y)));
                    } else {
                        return Err(WasmError::Trap("Type mismatch".to_string()));
                    }
                }
                0x0B => {
                    // end
                    if blocks.is_empty() {
                        return Ok(());
                    }
                    blocks.pop();
                }
                0x1A => {
                    // drop
                    self.stack.pop();
                }
                0x1B => {
                    // select
                    let c = self.stack.pop().unwrap_or(Value::I32(0));
                    let b = self.stack.pop().unwrap_or(Value::I32(0));
                    let a = self.stack.pop().unwrap_or(Value::I32(0));
                    if let Value::I32(cond) = c {
                        self.stack.push(if cond != 0 { a } else { b });
                    }
                }
                _ => {
                    return Err(WasmError::InvalidOpcode(opcode));
                }
            }
        }

        Ok(())
    }

    fn read_leb128_i32(&self, code: &[u8], start: usize) -> WasmResult<(i32, usize)> {
        let mut result: i32 = 0;
        let mut shift = 0;
        let mut pc = start;

        loop {
            if pc >= code.len() {
                return Err(WasmError::UnexpectedEof);
            }
            let byte = code[pc];
            pc += 1;
            result |= ((byte & 0x7F) as i32) << shift;
            shift += 7;
            if byte & 0x80 == 0 {
                if shift < 32 && (byte & 0x40) != 0 {
                    result |= -(1 << shift);
                }
                return Ok((result, pc));
            }
        }
    }
}

struct BlockFrame {
    block_type: u8,
    start: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_instance_creation() {
        let module = Module {
            types: Vec::new(),
            imports: Vec::new(),
            functions: Vec::new(),
            memories: Vec::new(),
            globals: Vec::new(),
            exports: Vec::new(),
            start: None,
            table: Vec::new(),
            code: Vec::new(),
            data: Vec::new(),
        };
        let instance = Instance::new(module);
        assert_eq!(instance.globals.len(), 0);
    }
}
