//! Auto-generated WASM Engine
//! Generated by Python - do not edit manually
//!
//! Minimal WebAssembly implementation
//! Supports WASM MVP + basic opcodes

pub mod decoder;
pub mod executor;
pub mod reader;
pub mod types;

pub use decoder::{Decoder, Module, FunctionBody, Global, DataSegment};
pub use executor::Instance;
pub use types::{Value, ValueType, FuncType, WasmError, WasmResult};
