//! Auto-generated WASM Types
//! Generated by Python - do not edit manually

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq)]
pub enum ValueType {
    I32,
    I64,
    F32,
    F64,
    V128,
    FuncRef,
    ExternRef,
}

#[derive(Debug, Clone)]
pub struct FuncType {
    pub params: Vec<ValueType>,
    pub results: Vec<ValueType>,
}

#[derive(Debug, Clone)]
pub struct Limits {
    pub min: u32,
    pub max: Option<u32>,
}

#[derive(Debug, Clone)]
pub struct MemoryType {
    pub limits: Limits,
}

#[derive(Debug, Clone)]
pub struct GlobalType {
    pub value_type: ValueType,
    pub mutable: bool,
}

#[derive(Debug, Clone)]
pub enum ExternalKind {
    Function(u32),
    Table,
    Memory,
    Global,
}

#[derive(Debug, Clone)]
pub struct Export {
    pub name: String,
    pub kind: ExternalKind,
}

#[derive(Debug, Clone)]
pub struct Import {
    pub module: String,
    pub field: String,
    pub kind: ExternalKind,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Value {
    I32(i32),
    I64(i64),
    F32(f32),
    F64(f64),
    V128(u128),
}

#[derive(Debug, Clone, PartialEq)]
pub enum WasmError {
    InvalidMagic,
    InvalidVersion,
    UnexpectedEof,
    InvalidSection(u8),
    InvalidOpcode(u8),
    InvalidValueType(u8),
    InvalidFunction(u32),
    Validation(String),
    Trap(String),
}

impl std::fmt::Display for WasmError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            WasmError::InvalidMagic => write!(f, "Invalid magic number"),
            WasmError::InvalidVersion => write!(f, "Invalid version"),
            WasmError::UnexpectedEof => write!(f, "Unexpected end of file"),
            WasmError::InvalidSection(id) => write!(f, "Invalid section ID: {}", id),
            WasmError::InvalidOpcode(op) => write!(f, "Invalid opcode: 0x{:02x}", op),
            WasmError::InvalidValueType(t) => write!(f, "Invalid value type: 0x{:02x}", t),
            WasmError::InvalidFunction(idx) => write!(f, "Invalid function index: {}", idx),
            WasmError::Validation(msg) => write!(f, "Validation error: {}", msg),
            WasmError::Trap(msg) => write!(f, "Trap: {}", msg),
        }
    }
}

impl std::error::Error for WasmError {}

pub type WasmResult<T> = Result<T, WasmError>;
