//! Auto-generated JS <-> WASM Bridge
//! Generated by Python - do not edit manually
//!
//! Permite comunicacion bidireccional entre JS engine y WASM runtime

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use crate::js_engine_v3::interpreter::Interpreter;
use crate::js_engine_v3::JsValue;
use crate::wasm_v2::{Instance, Runtime, Value as WasmValue, WasmResult};

pub struct Bridge {
    js_interp: Arc<Mutex<Interpreter>>,
    wasm_instances: Arc<Mutex<HashMap<String, Arc<Mutex<Instance>>>>>,
    runtime: Arc<Mutex<Runtime>>,
    call_count: Arc<Mutex<u64>>,
}

impl Bridge {
    pub fn new(js_interp: Arc<Mutex<Interpreter>>) -> Self {
        Self {
            js_interp,
            wasm_instances: Arc::new(Mutex::new(HashMap::new())),
            runtime: Arc::new(Mutex::new(Runtime::new())),
            call_count: Arc::new(Mutex::new(0)),
        }
    }

    pub fn register_wasm(&self, name: &str, instance: Arc<Mutex<Instance>>) {
        self.wasm_instances.lock().unwrap().insert(name.to_string(), instance);
    }

    /// JS -> WASM: Llamar funcion WASM desde JS
    pub fn js_call_wasm(&self, module: &str, func: &str, args: Vec<JsValue>) -> WasmResult<Vec<JsValue>> {
        *self.call_count.lock().unwrap() += 1;

        // Convert JS args to WASM args
        let wasm_args: Vec<WasmValue> = args.iter().map(|v| self.js_to_wasm(v)).collect();

        // Call WASM function through runtime
        // Find instance by name
        let instance_idx = {
            let instances = self.wasm_instances.lock().unwrap();
            instances.keys().position(|k| k == module)
                .ok_or_else(|| crate::wasm_v2::WasmError::Link(format!("Module not found: {}", module)))?
        };
        let results = self.runtime.lock().unwrap().call(instance_idx, func, &wasm_args)?;

        // Convert WASM results to JS
        Ok(results.iter().map(|v| self.wasm_to_js(v)).collect())
    }

    /// WASM -> JS: Llamar funcion JS desde WASM (imports)
    pub fn wasm_call_js(&self, module: &str, func: &str, args: Vec<WasmValue>) -> WasmResult<WasmValue> {
        *self.call_count.lock().unwrap() += 1;

        let mut interp = self.js_interp.lock().unwrap();

        // Convert WASM args to JS args
        let js_args: Vec<JsValue> = args.iter().map(|v| self.wasm_to_js(v)).collect();

        // Call JS function
        let result = self.call_js_function(&mut interp, module, func, &js_args);

        // Convert JS result to WASM
        match result {
            Ok(v) => Ok(self.js_to_wasm(&v)),
            Err(e) => Err(crate::wasm_v2::WasmError::Trap(e)),
        }
    }

    fn call_js_function(&self, interp: &mut Interpreter, _module: &str, func: &str, _args: &[JsValue]) -> Result<JsValue, String> {
        // Simplified: would look up the function in JS env
        match func {
            "print" | "console.log" => {
                // Would print args
                Ok(JsValue::Undefined)
            }
            "Date.now" => {
                // Would return current timestamp
                Ok(JsValue::Number(0.0))
            }
            "Math.random" => {
                // Would return random number
                Ok(JsValue::Number(0.5))
            }
            _ => Err(format!("JS function not found: {}", func)),
        }
    }

    /// Convert JS value to WASM value
    pub fn js_to_wasm(&self, value: &JsValue) -> WasmValue {
        match value {
            JsValue::Number(n) => {
                if n.fract() == 0.0 && *n >= i32::MIN as f64 && *n <= i32::MAX as f64 {
                    WasmValue::I32(*n as i32)
                } else {
                    WasmValue::F64(*n)
                }
            }
            JsValue::String(s) => {
                // WASM doesn't have native strings, use memory pointer
                WasmValue::I32(s.len() as i32)
            }
            JsValue::Boolean(b) => WasmValue::I32(if *b { 1 } else { 0 }),
            JsValue::Null | JsValue::Undefined => WasmValue::I32(0),
            _ => WasmValue::I32(0),
        }
    }

    /// Convert WASM value to JS value
    pub fn wasm_to_js(&self, value: &WasmValue) -> JsValue {
        match value {
            WasmValue::I32(n) => JsValue::Number(*n as f64),
            WasmValue::I64(n) => JsValue::Number(*n as f64),
            WasmValue::F32(n) => JsValue::Number(*n as f64),
            WasmValue::F64(n) => JsValue::Number(*n),
            WasmValue::V128(n) => JsValue::Number(*n as f64),
        }
    }

    /// Allocate WASM memory and copy JS string to it
    pub fn js_string_to_wasm(&self, instance: &mut Instance, s: &str) -> u32 {
        let ptr = self.memory_alloc(instance, s.len() as u32);
        if let Some(bytes) = instance.memory.get_mut(ptr as usize..(ptr + s.len() as u32) as usize) {
            bytes.copy_from_slice(s.as_bytes());
        }
        ptr
    }

    /// Read WASM memory as JS string
    pub fn wasm_string_to_js(&self, instance: &Instance, ptr: u32, len: u32) -> String {
        if let Some(bytes) = instance.memory.get(ptr as usize..(ptr + len) as usize) {
            String::from_utf8_lossy(bytes).to_string()
        } else {
            String::new()
        }
    }

    /// Simple bump allocator for WASM memory
    fn memory_alloc(&self, instance: &mut Instance, size: u32) -> u32 {
        let heap_ptr = 1024u32; // Start heap after static area
        let current = self.heap_ptr(instance);
        let new_ptr = current + size;
        // Store new heap pointer
        if let Some(bytes) = instance.memory.get_mut(0..4) {
            let bytes_arr = new_ptr.to_le_bytes();
            bytes.copy_from_slice(&bytes_arr);
        }
        current + heap_ptr
    }

    fn heap_ptr(&self, instance: &Instance) -> u32 {
        if instance.memory.len() < 4 {
            0
        } else {
            u32::from_le_bytes([
                instance.memory[0],
                instance.memory[1],
                instance.memory[2],
                instance.memory[3],
            ])
        }
    }

    pub fn get_stats(&self) -> BridgeStats {
        BridgeStats {
            call_count: *self.call_count.lock().unwrap(),
            module_count: self.wasm_instances.lock().unwrap().len() as u32,
        }
    }
}

#[derive(Debug, Clone)]
pub struct BridgeStats {
    pub call_count: u64,
    pub module_count: u32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bridge_creation() {
        let interp = Arc::new(Mutex::new(Interpreter::new()));
        let bridge = Bridge::new(interp);
        let stats = bridge.get_stats();
        assert_eq!(stats.call_count, 0);
    }

    #[test]
    fn test_js_to_wasm_conversion() {
        let interp = Arc::new(Mutex::new(Interpreter::new()));
        let bridge = Bridge::new(interp);

        assert_eq!(bridge.js_to_wasm(&JsValue::Number(42.0)), WasmValue::I32(42));
        assert_eq!(bridge.js_to_wasm(&JsValue::Boolean(true)), WasmValue::I32(1));
        assert_eq!(bridge.js_to_wasm(&JsValue::Boolean(false)), WasmValue::I32(0));
    }

    #[test]
    fn test_wasm_to_js_conversion() {
        let interp = Arc::new(Mutex::new(Interpreter::new()));
        let bridge = Bridge::new(interp);

        assert_eq!(bridge.wasm_to_js(&WasmValue::I32(42)), JsValue::Number(42.0));
        assert_eq!(bridge.wasm_to_js(&WasmValue::F64(3.14)), JsValue::Number(3.14));
    }
}
