// AUTO-GENERATED BY NO-CHROMIUM RUST CODEGEN
// Based on the V8 'Bible' Extraction

#[allow(dead_code)]
pub struct V8Handle {
    pub ptr: usize,
}

/// Native Rust handle for V8 Allocator
pub struct Allocator {
    pub handle: V8Handle,
}

impl Allocator {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Array
pub struct Array {
    pub handle: V8Handle,
}

impl Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ArrayBuffer
pub struct ArrayBuffer {
    pub handle: V8Handle,
}

impl ArrayBuffer {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ArrayBufferView
pub struct ArrayBufferView {
    pub handle: V8Handle,
}

impl ArrayBufferView {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 BackingStore
pub struct BackingStore {
    pub handle: V8Handle,
}

impl BackingStore {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 BigInt
pub struct BigInt {
    pub handle: V8Handle,
}

impl BigInt {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 BigInt64Array
pub struct BigInt64Array {
    pub handle: V8Handle,
}

impl BigInt64Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 BigIntObject
pub struct BigIntObject {
    pub handle: V8Handle,
}

impl BigIntObject {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 BigUint64Array
pub struct BigUint64Array {
    pub handle: V8Handle,
}

impl BigUint64Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Boolean
pub struct Boolean {
    pub handle: V8Handle,
}

impl Boolean {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 BooleanObject
pub struct BooleanObject {
    pub handle: V8Handle,
}

impl BooleanObject {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 CompileHintsCollector
pub struct CompileHintsCollector {
    pub handle: V8Handle,
}

impl CompileHintsCollector {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 CompiledWasmModule
pub struct CompiledWasmModule {
    pub handle: V8Handle,
}

impl CompiledWasmModule {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ConsumeCodeCacheTask
pub struct ConsumeCodeCacheTask {
    pub handle: V8Handle,
}

impl ConsumeCodeCacheTask {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Context
pub struct Context {
    pub handle: V8Handle,
}

impl Context {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Data
pub struct Data {
    pub handle: V8Handle,
}

impl Data {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 DataView
pub struct DataView {
    pub handle: V8Handle,
}

impl DataView {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Date
pub struct Date {
    pub handle: V8Handle,
}

impl Date {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Delegate
pub struct Delegate {
    pub handle: V8Handle,
}

impl Delegate {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 DictionaryTemplate
pub struct DictionaryTemplate {
    pub handle: V8Handle,
}

impl DictionaryTemplate {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 EmbedderRootsHandler
pub struct EmbedderRootsHandler {
    pub handle: V8Handle,
}

impl EmbedderRootsHandler {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 EmbedderStateScope
pub struct EmbedderStateScope {
    pub handle: V8Handle,
}

impl EmbedderStateScope {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Exception
pub struct Exception {
    pub handle: V8Handle,
}

impl Exception {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Extension
pub struct Extension {
    pub handle: V8Handle,
}

impl Extension {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ExtensionConfiguration
pub struct ExtensionConfiguration {
    pub handle: V8Handle,
}

impl ExtensionConfiguration {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 External
pub struct External {
    pub handle: V8Handle,
}

impl External {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ExternalOneByteStringResource
pub struct ExternalOneByteStringResource {
    pub handle: V8Handle,
}

impl ExternalOneByteStringResource {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ExternalResourceVisitor
pub struct ExternalResourceVisitor {
    pub handle: V8Handle,
}

impl ExternalResourceVisitor {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ExternalSourceStream
pub struct ExternalSourceStream {
    pub handle: V8Handle,
}

impl ExternalSourceStream {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ExternalStringResource
pub struct ExternalStringResource {
    pub handle: V8Handle,
}

impl ExternalStringResource {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ExternalStringResourceBase
pub struct ExternalStringResourceBase {
    pub handle: V8Handle,
}

impl ExternalStringResourceBase {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 FixedArray
pub struct FixedArray {
    pub handle: V8Handle,
}

impl FixedArray {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Float16Array
pub struct Float16Array {
    pub handle: V8Handle,
}

impl Float16Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Float32Array
pub struct Float32Array {
    pub handle: V8Handle,
}

impl Float32Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Float64Array
pub struct Float64Array {
    pub handle: V8Handle,
}

impl Float64Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Function
pub struct Function {
    pub handle: V8Handle,
}

impl Function {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 FunctionTemplate
pub struct FunctionTemplate {
    pub handle: V8Handle,
}

impl FunctionTemplate {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 HeapCodeStatistics
pub struct HeapCodeStatistics {
    pub handle: V8Handle,
}

impl HeapCodeStatistics {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 HeapObjectStatistics
pub struct HeapObjectStatistics {
    pub handle: V8Handle,
}

impl HeapObjectStatistics {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 HeapSpaceStatistics
pub struct HeapSpaceStatistics {
    pub handle: V8Handle,
}

impl HeapSpaceStatistics {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 HeapStatistics
pub struct HeapStatistics {
    pub handle: V8Handle,
}

impl HeapStatistics {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Int16Array
pub struct Int16Array {
    pub handle: V8Handle,
}

impl Int16Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Int32
pub struct Int32 {
    pub handle: V8Handle,
}

impl Int32 {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Int32Array
pub struct Int32Array {
    pub handle: V8Handle,
}

impl Int32Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Int8Array
pub struct Int8Array {
    pub handle: V8Handle,
}

impl Int8Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Integer
pub struct Integer {
    pub handle: V8Handle,
}

impl Integer {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Isolate
pub struct Isolate {
    pub handle: V8Handle,
}

impl Isolate {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 IsolateGroup
pub struct IsolateGroup {
    pub handle: V8Handle,
}

impl IsolateGroup {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 JSON
pub struct JSON {
    pub handle: V8Handle,
}

impl JSON {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Location
pub struct Location {
    pub handle: V8Handle,
}

impl Location {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Locker
pub struct Locker {
    pub handle: V8Handle,
}

impl Locker {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Map
pub struct Map {
    pub handle: V8Handle,
}

impl Map {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 MeasureMemoryDelegate
pub struct MeasureMemoryDelegate {
    pub handle: V8Handle,
}

impl MeasureMemoryDelegate {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 MemorySpan
pub struct MemorySpan {
    pub handle: V8Handle,
}

impl MemorySpan {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Message
pub struct Message {
    pub handle: V8Handle,
}

impl Message {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 MicrotaskQueue
pub struct MicrotaskQueue {
    pub handle: V8Handle,
}

impl MicrotaskQueue {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Module
pub struct Module {
    pub handle: V8Handle,
}

impl Module {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ModuleRequest
pub struct ModuleRequest {
    pub handle: V8Handle,
}

impl ModuleRequest {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Name
pub struct Name {
    pub handle: V8Handle,
}

impl Name {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Number
pub struct Number {
    pub handle: V8Handle,
}

impl Number {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 NumberObject
pub struct NumberObject {
    pub handle: V8Handle,
}

impl NumberObject {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Numeric
pub struct Numeric {
    pub handle: V8Handle,
}

impl Numeric {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Object
pub struct Object {
    pub handle: V8Handle,
}

impl Object {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ObjectTemplate
pub struct ObjectTemplate {
    pub handle: V8Handle,
}

impl ObjectTemplate {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 PersistentHandleVisitor
pub struct PersistentHandleVisitor {
    pub handle: V8Handle,
}

impl PersistentHandleVisitor {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Primitive
pub struct Primitive {
    pub handle: V8Handle,
}

impl Primitive {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 PrimitiveArray
pub struct PrimitiveArray {
    pub handle: V8Handle,
}

impl PrimitiveArray {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Private
pub struct Private {
    pub handle: V8Handle,
}

impl Private {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Promise
pub struct Promise {
    pub handle: V8Handle,
}

impl Promise {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 PropertyDescriptor
pub struct PropertyDescriptor {
    pub handle: V8Handle,
}

impl PropertyDescriptor {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Proxy
pub struct Proxy {
    pub handle: V8Handle,
}

impl Proxy {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 RegExp
pub struct RegExp {
    pub handle: V8Handle,
}

impl RegExp {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Resolver
pub struct Resolver {
    pub handle: V8Handle,
}

impl Resolver {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ResourceConstraints
pub struct ResourceConstraints {
    pub handle: V8Handle,
}

impl ResourceConstraints {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Script
pub struct Script {
    pub handle: V8Handle,
}

impl Script {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ScriptCompiler
pub struct ScriptCompiler {
    pub handle: V8Handle,
}

impl ScriptCompiler {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ScriptOrModule
pub struct ScriptOrModule {
    pub handle: V8Handle,
}

impl ScriptOrModule {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ScriptOrigin
pub struct ScriptOrigin {
    pub handle: V8Handle,
}

impl ScriptOrigin {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ScriptStreamingTask
pub struct ScriptStreamingTask {
    pub handle: V8Handle,
}

impl ScriptStreamingTask {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Set
pub struct Set {
    pub handle: V8Handle,
}

impl Set {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 SharedArrayBuffer
pub struct SharedArrayBuffer {
    pub handle: V8Handle,
}

impl SharedArrayBuffer {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 SharedMemoryStatistics
pub struct SharedMemoryStatistics {
    pub handle: V8Handle,
}

impl SharedMemoryStatistics {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 SharedMemoryUsageRecorder
pub struct SharedMemoryUsageRecorder {
    pub handle: V8Handle,
}

impl SharedMemoryUsageRecorder {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 SharedValueConveyor
pub struct SharedValueConveyor {
    pub handle: V8Handle,
}

impl SharedValueConveyor {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Signature
pub struct Signature {
    pub handle: V8Handle,
}

impl Signature {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 SnapshotCreator
pub struct SnapshotCreator {
    pub handle: V8Handle,
}

impl SnapshotCreator {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 SourceLocation
pub struct SourceLocation {
    pub handle: V8Handle,
}

impl SourceLocation {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 StackFrame
pub struct StackFrame {
    pub handle: V8Handle,
}

impl StackFrame {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 StackTrace
pub struct StackTrace {
    pub handle: V8Handle,
}

impl StackTrace {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 StartupData
pub struct StartupData {
    pub handle: V8Handle,
}

impl StartupData {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 StreamedSource
pub struct StreamedSource {
    pub handle: V8Handle,
}

impl StreamedSource {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 String
pub struct String {
    pub handle: V8Handle,
}

impl String {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 StringObject
pub struct StringObject {
    pub handle: V8Handle,
}

impl StringObject {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 StrongRootAllocatorBase
pub struct StrongRootAllocatorBase {
    pub handle: V8Handle,
}

impl StrongRootAllocatorBase {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Symbol
pub struct Symbol {
    pub handle: V8Handle,
}

impl Symbol {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 SymbolObject
pub struct SymbolObject {
    pub handle: V8Handle,
}

impl SymbolObject {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Template
pub struct Template {
    pub handle: V8Handle,
}

impl Template {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 TryCatch
pub struct TryCatch {
    pub handle: V8Handle,
}

impl TryCatch {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 TypecheckWitness
pub struct TypecheckWitness {
    pub handle: V8Handle,
}

impl TypecheckWitness {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 TypedArray
pub struct TypedArray {
    pub handle: V8Handle,
}

impl TypedArray {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Uint16Array
pub struct Uint16Array {
    pub handle: V8Handle,
}

impl Uint16Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Uint32
pub struct Uint32 {
    pub handle: V8Handle,
}

impl Uint32 {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Uint32Array
pub struct Uint32Array {
    pub handle: V8Handle,
}

impl Uint32Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Uint8Array
pub struct Uint8Array {
    pub handle: V8Handle,
}

impl Uint8Array {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Uint8ClampedArray
pub struct Uint8ClampedArray {
    pub handle: V8Handle,
}

impl Uint8ClampedArray {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 UnboundModuleScript
pub struct UnboundModuleScript {
    pub handle: V8Handle,
}

impl UnboundModuleScript {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 UnboundScript
pub struct UnboundScript {
    pub handle: V8Handle,
}

impl UnboundScript {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Unlocker
pub struct Unlocker {
    pub handle: V8Handle,
}

impl Unlocker {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Unwinder
pub struct Unwinder {
    pub handle: V8Handle,
}

impl Unwinder {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Utf8Value
pub struct Utf8Value {
    pub handle: V8Handle,
}

impl Utf8Value {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 V8
pub struct V8 {
    pub handle: V8Handle,
}

impl V8 {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 V8_NODISCARD
pub struct V8_NODISCARD {
    pub handle: V8Handle,
}

impl V8_NODISCARD {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 Value
pub struct Value {
    pub handle: V8Handle,
}

impl Value {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ValueDeserializer
pub struct ValueDeserializer {
    pub handle: V8Handle,
}

impl ValueDeserializer {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ValueSerializer
pub struct ValueSerializer {
    pub handle: V8Handle,
}

impl ValueSerializer {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 ValueView
pub struct ValueView {
    pub handle: V8Handle,
}

impl ValueView {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 WasmMemoryMapDescriptor
pub struct WasmMemoryMapDescriptor {
    pub handle: V8Handle,
}

impl WasmMemoryMapDescriptor {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 WasmMemoryObject
pub struct WasmMemoryObject {
    pub handle: V8Handle,
}

impl WasmMemoryObject {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 WasmModuleCompilation
pub struct WasmModuleCompilation {
    pub handle: V8Handle,
}

impl WasmModuleCompilation {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 WasmModuleObject
pub struct WasmModuleObject {
    pub handle: V8Handle,
}

impl WasmModuleObject {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}

/// Native Rust handle for V8 WasmStreaming
pub struct WasmStreaming {
    pub handle: V8Handle,
}

impl WasmStreaming {
    pub fn from_raw(ptr: usize) -> Self {
        Self { handle: V8Handle { ptr } }
    }
}
