//! WASM Binary Decoder - Parses .wasm files
//! Generated by Python

use super::types::*;
use super::leb128::Reader;

const WASM_MAGIC: [u8; 4] = [0x00, 0x61, 0x73, 0x6D];
const WASM_VERSION: [u8; 4] = [0x01, 0x00, 0x00, 0x00];

#[derive(Debug, Clone)]
pub struct Module {
    pub types: Vec<FuncType>,
    pub imports: Vec<Import>,
    pub functions: Vec<u32>, // type indices
    pub tables: Vec<TableType>,
    pub memories: Vec<MemoryType>,
    pub globals: Vec<Global>,
    pub exports: Vec<Export>,
    pub start: Option<u32>,
    pub elements: Vec<Element>,
    pub code: Vec<FunctionBody>,
    pub data: Vec<DataSegment>,
    pub custom_sections: Vec<CustomSection>,
}

#[derive(Debug, Clone)]
pub struct Import {
    pub module: String,
    pub field: String,
    pub kind: ImportKind,
}

#[derive(Debug, Clone)]
pub enum ImportKind {
    Function(u32),
    Table(TableType),
    Memory(MemoryType),
    Global(GlobalType),
}

#[derive(Debug, Clone)]
pub struct Export {
    pub name: String,
    pub kind: ExportKind,
}

#[derive(Debug, Clone)]
pub enum ExportKind {
    Function(u32),
    Table(u32),
    Memory(u32),
    Global(u32),
}

#[derive(Debug, Clone)]
pub struct Global {
    pub ty: GlobalType,
    pub init: Vec<u8>,
}

#[derive(Debug, Clone)]
pub struct Element {
    pub table_index: u32,
    pub offset: Vec<u8>,
    pub init: Vec<u32>,
}

#[derive(Debug, Clone)]
pub struct FunctionBody {
    pub locals: Vec<(u32, ValueType)>,
    pub code: Vec<u8>,
}

#[derive(Debug, Clone)]
pub struct DataSegment {
    pub memory_index: u32,
    pub offset: Vec<u8>,
    pub data: Vec<u8>,
}

#[derive(Debug, Clone)]
pub struct CustomSection {
    pub name: String,
    pub data: Vec<u8>,
}

pub struct Decoder<'a> {
    reader: Reader<'a>,
}

impl<'a> Decoder<'a> {
    pub fn new(bytes: &'a [u8]) -> Self {
        Self { reader: Reader::new(bytes) }
    }

    pub fn decode(mut self) -> WasmResult<Module> {
        // Magic number
        let magic = self.reader.read_bytes(4)?;
        if magic != WASM_MAGIC {
            return Err(WasmError::InvalidMagic);
        }
        // Version
        let version = self.reader.read_bytes(4)?;
        if version != WASM_VERSION {
            return Err(WasmError::InvalidVersion);
        }

        let mut module = Module::new();

        while self.reader.remaining() > 0 {
            let section_id = self.reader.read_u8()?;
            let _section_size = self.reader.read_u32()?;

            match section_id {
                0 => {
                    // Custom section
                    let name = self.reader.read_name()?;
                    let data = self.reader.read_bytes(self.reader.remaining())?.to_vec();
                    module.custom_sections.push(CustomSection { name, data });
                }
                1 => module.types = self.read_type_section()?,
                2 => module.imports = self.read_import_section()?,
                3 => module.functions = self.read_function_section()?,
                4 => module.tables = self.read_table_section()?,
                5 => module.memories = self.read_memory_section()?,
                6 => module.globals = self.read_global_section()?,
                7 => module.exports = self.read_export_section()?,
                8 => module.start = self.read_start_section()?,
                9 => module.elements = self.read_element_section()?,
                10 => module.code = self.read_code_section()?,
                11 => module.data = self.read_data_section()?,
                12 => {
                    // Data count section (for bulk memory)
                    let _count = self.reader.read_u32()?;
                }
                _ => {
                    // Skip unknown section
                    let size = self.reader.read_u32()? as usize;
                    self.reader.read_bytes(size)?;
                }
            }
        }

        Ok(module)
    }

    fn read_type_section(&mut self) -> WasmResult<Vec<FuncType>> {
        self.reader.read_vector(|r| {
            r.read_u8()?; // 0x60 = function type
            let params = r.read_vector(|r2| ValueType::from_byte(r2.read_u8()?))?;
            let results = r.read_vector(|r2| ValueType::from_byte(r2.read_u8()?))?;
            Ok(FuncType { params, results })
        })
    }

    fn read_import_section(&mut self) -> WasmResult<Vec<Import>> {
        self.reader.read_vector(|r| {
            let module = r.read_name()?;
            let field = r.read_name()?;
            let kind_byte = r.read_u8()?;
            let kind = match kind_byte {
                0x00 => ImportKind::Function(r.read_u32()?),
                0x01 => {
                    let element_type = ValueType::from_byte(r.read_u8()?)?;
                    let limits = Self::read_limits(r)?;
                    ImportKind::Table(TableType { element_type, limits })
                }
                0x02 => {
                    let limits = Self::read_limits(r)?;
                    ImportKind::Memory(MemoryType { limits, shared: false })
                }
                0x03 => {
                    let value_type = ValueType::from_byte(r.read_u8()?)?;
                    let mutable = r.read_u8()? != 0;
                    ImportKind::Global(GlobalType { value_type, mutable })
                }
                _ => return Err(WasmError::Validation("Invalid import kind".to_string())),
            };
            Ok(Import { module, field, kind })
        })
    }

    fn read_function_section(&mut self) -> WasmResult<Vec<u32>> {
        self.reader.read_vector(|r| r.read_u32())
    }

    fn read_table_section(&mut self) -> WasmResult<Vec<TableType>> {
        self.reader.read_vector(|r| {
            let element_type = ValueType::from_byte(r.read_u8()?)?;
            let limits = Self::read_limits(r)?;
            Ok(TableType { element_type, limits })
        })
    }

    fn read_memory_section(&mut self) -> WasmResult<Vec<MemoryType>> {
        self.reader.read_vector(|r| {
            let limits = Self::read_limits(r)?;
            Ok(MemoryType { limits, shared: false })
        })
    }

    fn read_global_section(&mut self) -> WasmResult<Vec<Global>> {
        self.reader.read_vector(|r| {
            let value_type = ValueType::from_byte(r.read_u8()?)?;
            let mutable = r.read_u8()? != 0;
            let init_size = r.read_u32()? as usize;
            let init = r.read_bytes(init_size)?.to_vec();
            Ok(Global { ty: GlobalType { value_type, mutable }, init })
        })
    }

    fn read_export_section(&mut self) -> WasmResult<Vec<Export>> {
        self.reader.read_vector(|r| {
            let name = r.read_name()?;
            let kind_byte = r.read_u8()?;
            let index = r.read_u32()?;
            let kind = match kind_byte {
                0x00 => ExportKind::Function(index),
                0x01 => ExportKind::Table(index),
                0x02 => ExportKind::Memory(index),
                0x03 => ExportKind::Global(index),
                _ => return Err(WasmError::Validation("Invalid export kind".to_string())),
            };
            Ok(Export { name, kind })
        })
    }

    fn read_start_section(&mut self) -> WasmResult<Option<u32>> {
        Ok(Some(self.reader.read_u32()?))
    }

    fn read_element_section(&mut self) -> WasmResult<Vec<Element>> {
        self.reader.read_vector(|r| {
            let table_index = r.read_u32()?;
            let offset_size = r.read_u32()? as usize;
            let offset = r.read_bytes(offset_size)?.to_vec();
            let init = r.read_vector(|r2| r2.read_u32())?;
            Ok(Element { table_index, offset, init })
        })
    }

    fn read_code_section(&mut self) -> WasmResult<Vec<FunctionBody>> {
        self.reader.read_vector(|r| {
            let body_size = r.read_u32()? as usize;
            let start = r.pos();
            let locals = r.read_vector(|r2| {
                let count = r2.read_u32()?;
                let ty = ValueType::from_byte(r2.read_u8()?)?;
                Ok((count, ty))
            })?;
            let remaining = body_size - (r.pos() - start);
            let code = r.read_bytes(remaining)?.to_vec();
            Ok(FunctionBody { locals, code })
        })
    }

    fn read_data_section(&mut self) -> WasmResult<Vec<DataSegment>> {
        self.reader.read_vector(|r| {
            let flags = r.read_u8()?;
            let memory_index = if flags & 0x02 != 0 { r.read_u32()? } else { 0 };
            let offset_size = r.read_u32()? as usize;
            let offset = r.read_bytes(offset_size)?.to_vec();
            let data = r.read_vector(|r2| r2.read_u8())?;
            Ok(DataSegment { memory_index, offset, data })
        })
    }

    fn read_limits(r: &mut Reader) -> WasmResult<Limits> {
        let flags = r.read_u8()?;
        let min = r.read_u32()?;
        let max = if flags & 0x01 != 0 { Some(r.read_u32()?) } else { None };
        Ok(Limits { min, max })
    }
}

impl Module {
    pub fn new() -> Self {
        Self {
            types: Vec::new(),
            imports: Vec::new(),
            functions: Vec::new(),
            tables: Vec::new(),
            memories: Vec::new(),
            globals: Vec::new(),
            exports: Vec::new(),
            start: None,
            elements: Vec::new(),
            code: Vec::new(),
            data: Vec::new(),
            custom_sections: Vec::new(),
        }
    }
}
