//! WASM Interpreter - Executes validated modules
//! Generated by Python

use super::types::*;
use super::value::Value;
use super::decoder::*;
use std::collections::HashMap;const STACK_SIZE: usize = 1024;
const CALL_STACK_SIZE: usize = 1024;

pub struct Interpreter {
    pub stack: Vec<Value>,
    pub call_stack: Vec<CallFrame>,
    pub memory: Vec<Vec<u8>>,
    pub globals: Vec<Value>,
    pub tables: Vec<Vec<u32>>,
    pub functions: HashMap<String, FunctionRef>,
    pub fuel: u64, // For execution limits
    pub max_fuel: u64,
}

pub enum FunctionRef {
    Local { type_idx: u32, code: usize },
    Import { module: String, field: String },
    Host(String), // Host function name
}

pub struct CallFrame {
    pub locals: Vec<Value>,
    pub pc: usize,
    pub code: Vec<u8>,
    pub func_type: FuncType,
    pub function_index: Option<u32>,
}

impl Interpreter {
    pub fn new() -> Self {
        Self {
            stack: Vec::with_capacity(STACK_SIZE),
            call_stack: Vec::with_capacity(CALL_STACK_SIZE),
            memory: Vec::new(),
            globals: Vec::new(),
            tables: Vec::new(),
            functions: HashMap::new(),
            fuel: 0,
            max_fuel: 1_000_000,
        }
    }

    /// Set fuel limit for execution
    pub fn with_fuel(mut self, fuel: u64) -> Self {
        self.max_fuel = fuel;
        self
    }

    /// Execute a function
    pub fn execute(&mut self, module: &Module, func_idx: u32, args: &[Value]) -> WasmResult<Vec<Value>> {
        // Get function type
        let type_idx = *module.functions.get(func_idx as usize)
            .ok_or(WasmError::InvalidFunction(func_idx))?;
        let func_type = module.types.get(type_idx as usize)
            .ok_or(WasmError::InvalidTypeIndex(type_idx))?
            .clone();

        // Check args match
        if args.len() != func_type.params.len() {
            return Err(WasmError::Validation(
                format!("Expected {} args, got {}", func_type.params.len(), args.len())
            ));
        }

        // Push args onto stack
        for arg in args {
            self.push(*arg)?;
        }

        // Get function body
        let body = module.code.get(func_idx as usize)
            .ok_or(WasmError::InvalidFunction(func_idx))?
            .clone();

        // Create call frame
        let mut frame = CallFrame {
            locals: args.to_vec(),
            pc: 0,
            code: body.code.clone(),
            func_type: func_type.clone(),
            function_index: Some(func_idx),
        };

        // Add locals
        for (count, val_type) in &body.locals {
            for _ in 0..*count {
                frame.locals.push(Value::default_for(*val_type));
            }
        }

        self.call_stack.push(frame);

        // Execute
        self.run()?;

        // Pop results
        let mut results = Vec::new();
        for _ in &func_type.results {
            results.push(self.pop()?);
        }
        results.reverse();
        self.call_stack.pop();
        Ok(results)
    }

    fn run(&mut self) -> WasmResult<()> {
        loop {
            if self.fuel >= self.max_fuel {
                return Err(WasmError::Trap("Out of fuel".to_string()));
            }
            self.fuel += 1;

            if self.call_stack.is_empty() {
                return Ok(());
            }

            let frame = self.call_stack.last_mut().unwrap();
            if frame.pc >= frame.code.len() {
                self.call_stack.pop();
                continue;
            }

            let opcode = frame.code[frame.pc];
            frame.pc += 1;

            self.execute_opcode(opcode)?;
        }
    }

    fn execute_opcode(&mut self, opcode: u8) -> WasmResult<()> {
        match opcode {
            0x00 => Err(WasmError::Trap("unreachable".to_string())),
            0x01 => Ok(()), // nop
            0x0B => {
                // end - pop call frame
                self.call_stack.pop();
                Ok(())
            }
            0x0F => {
                // return
                self.call_stack.pop();
                Ok(())
            }
            0x1A => {
                // drop
                self.pop()?;
                Ok(())
            }
            0x1B => {
                // select
                let c = self.pop()?.as_i32();
                let b = self.pop()?;
                let a = self.pop()?;
                self.push(if c != 0 { a } else { b })?;
                Ok(())
            }
            0x20 => {
                // local.get
                let idx = self.read_leb_u32()?;
                let frame = self.call_stack.last().unwrap();
                let val = frame.locals[idx as usize];
                self.push(val)?;
                Ok(())
            }
            0x21 => {
                // local.set
                let idx = self.read_leb_u32()?;
                let val = self.pop()?;
                let frame = self.call_stack.last_mut().unwrap();
                frame.locals[idx as usize] = val;
                Ok(())
            }
            0x22 => {
                // local.tee
                let idx = self.read_leb_u32()?;
                let val = self.peek()?;
                let frame = self.call_stack.last_mut().unwrap();
                frame.locals[idx as usize] = val;
                Ok(())
            }
            0x23 => {
                // global.get
                let idx = self.read_leb_u32()?;
                let val = self.globals[idx as usize];
                self.push(val)?;
                Ok(())
            }
            0x24 => {
                // global.set
                let idx = self.read_leb_u32()?;
                let val = self.pop()?;
                self.globals[idx as usize] = val;
                Ok(())
            }
            0x28 => {
                // i32.load
                self.load_i32(0)
            }
            0x36 => {
                // i32.store
                self.store_i32(0)
            }
            0x3F => {
                // memory.size
                let mem = &self.memory[0];
                self.push(Value::I32((mem.len() / 65536) as i32))?;
                Ok(())
            }
            0x40 => {
                // memory.grow
                let pages = self.pop()?.as_i32() as usize;
                let mem = &mut self.memory[0];
                let current_pages = mem.len() / 65536;
                let new_size = (current_pages + pages) * 65536;
                mem.resize(new_size, 0);
                self.push(Value::I32(current_pages as i32))?;
                Ok(())
            }
            0x41 => {
                // i32.const
                let val = self.read_leb_i32()?;
                self.push(Value::I32(val))?;
                Ok(())
            }
            0x42 => {
                // i64.const
                let val = self.read_leb_i64()?;
                self.push(Value::I64(val))?;
                Ok(())
            }
            0x43 => {
                // f32.const
                let bits = self.read_u32()?;
                self.push(Value::F32(f32::from_bits(bits)))?;
                Ok(())
            }
            0x44 => {
                // f64.const
                let bits = self.read_u64()?;
                self.push(Value::F64(f64::from_bits(bits)))?;
                Ok(())
            }
            // Arithmetic
            0x6A => {
                // i32.add
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                self.push(Value::I32(a.wrapping_add(b)))?;
                Ok(())
            }
            0x6B => {
                // i32.sub
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                self.push(Value::I32(a.wrapping_sub(b)))?;
                Ok(())
            }
            0x6C => {
                // i32.mul
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                self.push(Value::I32(a.wrapping_mul(b)))?;
                Ok(())
            }
            0x6D => {
                // i32.div_s
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                if b == 0 { return Err(WasmError::Trap("division by zero".to_string())); }
                self.push(Value::I32(a / b))?;
                Ok(())
            }
            0x6E => {
                // i32.div_u
                let b = self.pop()?.as_i32() as u32;
                let a = self.pop()?.as_i32() as u32;
                if b == 0 { return Err(WasmError::Trap("division by zero".to_string())); }
                self.push(Value::I32((a / b) as i32))?;
                Ok(())
            }
            0x46 => {
                // i32.eq
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                self.push(Value::I32(if a == b { 1 } else { 0 }))?;
                Ok(())
            }
            0x47 => {
                // i32.ne
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                self.push(Value::I32(if a != b { 1 } else { 0 }))?;
                Ok(())
            }
            0x48 => {
                // i32.lt_s
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                self.push(Value::I32(if a < b { 1 } else { 0 }))?;
                Ok(())
            }
            0x4A => {
                // i32.gt_s
                let b = self.pop()?.as_i32();
                let a = self.pop()?.as_i32();
                self.push(Value::I32(if a > b { 1 } else { 0 }))?;
                Ok(())
            }
            0x45 => {
                // i32.eqz
                let a = self.pop()?.as_i32();
                self.push(Value::I32(if a == 0 { 1 } else { 0 }))?;
                Ok(())
            }
            0x10 => {
                // call
                let func_idx = self.read_leb_u32()?;
                self.handle_call(func_idx)
            }
            _ => Err(WasmError::InvalidOpcode(opcode)),
        }
    }

    fn handle_call(&mut self, func_idx: u32) -> WasmResult<()> {
        // For now, placeholder
        let _ = func_idx;
        Err(WasmError::Trap("call not yet implemented".to_string()))
    }

    fn load_i32(&mut self, _align: u32) -> WasmResult<()> {
        let offset = self.pop()?.as_i32() as usize;
        let mem = &self.memory[0];
        if offset + 4 > mem.len() {
            return Err(WasmError::Trap("out of bounds memory access".to_string()));
        }
        let val = u32::from_le_bytes([
            mem[offset], mem[offset + 1], mem[offset + 2], mem[offset + 3],
        ]);
        self.push(Value::I32(val as i32))?;
        Ok(())
    }

    fn store_i32(&mut self, _align: u32) -> WasmResult<()> {
        let value = self.pop()?.as_i32();
        let offset = self.pop()?.as_i32() as usize;
        let mem = &mut self.memory[0];
        if offset + 4 > mem.len() {
            return Err(WasmError::Trap("out of bounds memory access".to_string()));
        }
        let bytes = (value as u32).to_le_bytes();
        mem[offset] = bytes[0];
        mem[offset + 1] = bytes[1];
        mem[offset + 2] = bytes[2];
        mem[offset + 3] = bytes[3];
        Ok(())
    }

    pub fn push(&mut self, value: Value) -> WasmResult<()> {
        if self.stack.len() >= STACK_SIZE {
            return Err(WasmError::StackOverflow);
        }
        self.stack.push(value);
        Ok(())
    }

    pub fn pop(&mut self) -> WasmResult<Value> {
        self.stack.pop().ok_or(WasmError::StackOverflow)
    }

    pub fn peek(&self) -> WasmResult<Value> {
        self.stack.last().copied().ok_or(WasmError::StackOverflow)
    }

    fn read_leb_u32(&mut self) -> WasmResult<u32> {
        let frame = self.call_stack.last_mut().unwrap();
        super::leb128::Reader::new(&frame.code).read_u32() // Simplified
    }

    fn read_leb_i32(&mut self) -> WasmResult<i32> {
        let frame = self.call_stack.last_mut().unwrap();
        super::leb128::Reader::new(&frame.code).read_i32() // Simplified
    }

    fn read_leb_i64(&mut self) -> WasmResult<i64> {
        let frame = self.call_stack.last_mut().unwrap();
        super::leb128::Reader::new(&frame.code).read_i64() // Simplified
    }

    fn read_u32(&mut self) -> WasmResult<u32> {
        let frame = self.call_stack.last_mut().unwrap();
        let pos = frame.pc;
        if pos + 4 > frame.code.len() { return Err(WasmError::UnexpectedEof); }
        let val = u32::from_le_bytes([frame.code[pos], frame.code[pos+1], frame.code[pos+2], frame.code[pos+3]]);
        frame.pc += 4;
        Ok(val)
    }

    fn read_u64(&mut self) -> WasmResult<u64> {
        let frame = self.call_stack.last_mut().unwrap();
        let pos = frame.pc;
        if pos + 8 > frame.code.len() { return Err(WasmError::UnexpectedEof); }
        let val = u64::from_le_bytes([
            frame.code[pos], frame.code[pos+1], frame.code[pos+2], frame.code[pos+3],
            frame.code[pos+4], frame.code[pos+5], frame.code[pos+6], frame.code[pos+7],
        ]);
        frame.pc += 8;
        Ok(val)
    }
}

impl Default for Interpreter {
    fn default() -> Self {
        Self::new()
    }
}
