//! WASM v2 - Professional WebAssembly Engine
//! Generated by Python
//!
//! Features:
//! - MVP (WebAssembly 1.0) complete
//! - SIMD 128-bit operations
//! - Atomic operations
//! - Multi-value returns
//! - Bulk memory operations
//! - Reference types
//! - Module validation
//! - JIT compilation (Cranelift-style)
//! - Arena-based memory management
//! - WASI (WebAssembly System Interface) preview

#![allow(dead_code)]

pub mod types;
pub mod value;
pub mod arena;
pub mod leb128;
pub mod decoder;
pub mod validator;
pub mod opcodes;
pub mod interpreter;
pub mod jit;
pub mod compiler;
pub mod runtime;
pub mod wasi;

pub use types::{WasmError, WasmResult, ValueType, FuncType, Limits, MemoryType, GlobalType, TableType};
pub use value::Value;
pub use arena::Arena;
pub use decoder::Module;
pub use runtime::{Runtime, Instance, CompilationMode};
pub use compiler::Compiler;
