//! Runtime - High-level interface to execute WASM
//! Generated by Python

use super::types::*;
use super::value::Value;
use super::decoder::Module;
use super::interpreter::Interpreter;
use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CompilationMode {
    Interpretation,  // Direct interpretation
    Jit,             // JIT compiled then run
    Aot,             // Ahead-of-time compiled
}

pub struct Runtime {
    pub interpreter: Interpreter,
    pub instances: Vec<Instance>,
    pub max_fuel: u64,
    pub host_functions: HashMap<String, Box<dyn Fn(&[Value]) -> WasmResult<Vec<Value>>>>,
}

pub struct Instance {
    pub module: Module,
    pub memory: Vec<u8>,
    pub globals: Vec<Value>,
    pub tables: Vec<Vec<u32>>,
    pub exports: HashMap<String, Value>,
}

impl Runtime {
    pub fn new() -> Self {
        Self {
            interpreter: Interpreter::new(),
            instances: Vec::new(),
            max_fuel: 10_000_000,
            host_functions: HashMap::new(),
        }
    }

    /// Register a host function
    pub fn register_host_function<F>(&mut self, name: &str, func: F)
    where F: Fn(&[Value]) -> WasmResult<Vec<Value>> + 'static
    {
        self.host_functions.insert(name.to_string(), Box::new(func));
    }

    /// Instantiate a module
    pub fn instantiate(&mut self, module: &Module) -> WasmResult<&mut Instance> {
        // Allocate memory
        let mut memory = Vec::new();
        for mem in &module.memories {
            let size = (mem.limits.min as usize) * 65536;
            memory = vec![0; size];
        }

        // Initialize globals
        let mut globals = Vec::new();
        for global in &module.globals {
            // Execute init expression
            globals.push(Value::I32(0)); // Simplified
        }

        // Initialize tables
        let mut tables = Vec::new();
        for table in &module.tables {
            let size = table.limits.min as usize;
            tables.push(vec![0; size]);
        }

        // Set up exports
        let mut exports = HashMap::new();
        for export in &module.exports {
            match export.kind {
                super::decoder::ExportKind::Function(idx) => {
                    exports.insert(export.name.clone(), Value::I32(idx as i32));
                }
                super::decoder::ExportKind::Memory(idx) => {
                    exports.insert(export.name.clone(), Value::I32(idx as i32));
                }
                _ => {}
            }
        }

        self.interpreter.memory = vec![memory.clone()];
        self.interpreter.globals = globals.clone();
        self.interpreter.tables = tables.clone();

        self.instances.push(Instance {
            module: module.clone(),
            memory,
            globals,
            tables,
            exports,
        });

        Ok(self.instances.last_mut().unwrap())
    }

    /// Call an exported function
    pub fn call(&mut self, instance_idx: usize, name: &str, args: &[Value]) -> WasmResult<Vec<Value>> {
        let instance = self.instances.get(instance_idx)
            .ok_or(WasmError::Link(format!("Instance {} not found", instance_idx)))?;

        // Find function index
        let func_idx = match instance.exports.get(name) {
            Some(Value::I32(idx)) => *idx as u32,
            _ => return Err(WasmError::Link(format!("Export not found: {}", name))),
        };

        // Setup interpreter state
        self.interpreter.memory = vec![instance.memory.clone()];
        self.interpreter.globals = instance.globals.clone();
        self.interpreter.fuel = 0;
        self.interpreter.max_fuel = self.max_fuel;

        // Execute
        self.interpreter.execute(&instance.module, func_idx, args)
    }

    /// Get statistics
    pub fn stats(&self) -> RuntimeStats {
        RuntimeStats {
            fuel_used: self.interpreter.fuel,
            max_fuel: self.interpreter.max_fuel,
            instance_count: self.instances.len(),
            host_function_count: self.host_functions.len(),
        }
    }
}

pub struct RuntimeStats {
    pub fuel_used: u64,
    pub max_fuel: u64,
    pub instance_count: usize,
    pub host_function_count: usize,
}

impl Default for Runtime {
    fn default() -> Self {
        Self::new()
    }
}
