//! Runtime values for WASM
//! Generated by Python

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Value {
    I32(i32),
    I64(i64),
    F32(f32),
    F64(f64),
    V128(u128),  // SIMD
}

impl Value {
    pub fn type_of(&self) -> super::types::ValueType {
        match self {
            Value::I32(_) => super::types::ValueType::I32,
            Value::I64(_) => super::types::ValueType::I64,
            Value::F32(_) => super::types::ValueType::F32,
            Value::F64(_) => super::types::ValueType::F64,
            Value::V128(_) => super::types::ValueType::V128,
        }
    }

    pub fn as_i32(&self) -> i32 {
        match self {
            Value::I32(v) => *v,
            Value::I64(v) => *v as i32,
            _ => 0,
        }
    }

    pub fn as_i64(&self) -> i64 {
        match self {
            Value::I64(v) => *v,
            Value::I32(v) => *v as i64,
            _ => 0,
        }
    }

    pub fn as_f32(&self) -> f32 {
        match self {
            Value::F32(v) => *v,
            Value::F64(v) => *v as f32,
            _ => 0.0,
        }
    }

    pub fn as_f64(&self) -> f64 {
        match self {
            Value::F64(v) => *v,
            Value::F32(v) => *v as f64,
            _ => 0.0,
        }
    }

    pub fn as_u128(&self) -> u128 {
        match self {
            Value::V128(v) => *v,
            Value::I64(v) => *v as u128,
            Value::I32(v) => *v as u128,
            _ => 0,
        }
    }

    pub fn default_for(ty: super::types::ValueType) -> Self {
        match ty {
            super::types::ValueType::I32 => Value::I32(0),
            super::types::ValueType::I64 => Value::I64(0),
            super::types::ValueType::F32 => Value::F32(0.0),
            super::types::ValueType::F64 => Value::F64(0.0),
            super::types::ValueType::V128 => Value::V128(0),
            _ => Value::I32(0),
        }
    }
}
