#!/usr/bin/env python3
"""
Generador de WASM Decoder para Noir Browser
Genera un decoder WASM MVP en Rust (~1000 lineas).
"""

from pathlib import Path

class WasmGenerator:
    def __init__(self, output_dir: str = "src/wasm_engine"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_types(self):
        """Genera los tipos de datos WASM"""
        code = '''//! Auto-generated WASM Types
//! Generated by Python - do not edit manually

use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq)]
pub enum ValueType {
    I32,
    I64,
    F32,
    F64,
    V128,
    FuncRef,
    ExternRef,
}

#[derive(Debug, Clone)]
pub struct FuncType {
    pub params: Vec<ValueType>,
    pub results: Vec<ValueType>,
}

#[derive(Debug, Clone)]
pub struct Limits {
    pub min: u32,
    pub max: Option<u32>,
}

#[derive(Debug, Clone)]
pub struct MemoryType {
    pub limits: Limits,
}

#[derive(Debug, Clone)]
pub struct GlobalType {
    pub value_type: ValueType,
    pub mutable: bool,
}

#[derive(Debug, Clone)]
pub enum ExternalKind {
    Function(u32),
    Table,
    Memory,
    Global,
}

#[derive(Debug, Clone)]
pub struct Export {
    pub name: String,
    pub kind: ExternalKind,
}

#[derive(Debug, Clone)]
pub struct Import {
    pub module: String,
    pub field: String,
    pub kind: ExternalKind,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Value {
    I32(i32),
    I64(i64),
    F32(f32),
    F64(f64),
    V128(u128),
}

#[derive(Debug, Clone, PartialEq)]
pub enum WasmError {
    InvalidMagic,
    InvalidVersion,
    UnexpectedEof,
    InvalidSection(u8),
    InvalidOpcode(u8),
    InvalidValueType(u8),
    InvalidFunction(u32),
    Validation(String),
    Trap(String),
}

impl std::fmt::Display for WasmError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            WasmError::InvalidMagic => write!(f, "Invalid magic number"),
            WasmError::InvalidVersion => write!(f, "Invalid version"),
            WasmError::UnexpectedEof => write!(f, "Unexpected end of file"),
            WasmError::InvalidSection(id) => write!(f, "Invalid section ID: {}", id),
            WasmError::InvalidOpcode(op) => write!(f, "Invalid opcode: 0x{:02x}", op),
            WasmError::InvalidValueType(t) => write!(f, "Invalid value type: 0x{:02x}", t),
            WasmError::InvalidFunction(idx) => write!(f, "Invalid function index: {}", idx),
            WasmError::Validation(msg) => write!(f, "Validation error: {}", msg),
            WasmError::Trap(msg) => write!(f, "Trap: {}", msg),
        }
    }
}

impl std::error::Error for WasmError {}

pub type WasmResult<T> = Result<T, WasmError>;
'''
        output = self.output_dir / "types.rs"
        output.write_text(code)
        print(f"Generated: {output}")

    def generate_leb128(self):
        """Genera el LEB128 decoder"""
        code = '''//! Auto-generated LEB128 decoder
//! Generated by Python - do not edit manually

use super::types::{WasmResult, WasmError};

pub struct Reader<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    pub fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, pos: 0 }
    }

    pub fn pos(&self) -> usize {
        self.pos
    }

    pub fn remaining(&self) -> usize {
        self.bytes.len().saturating_sub(self.pos)
    }

    pub fn read_u8(&mut self) -> WasmResult<u8> {
        if self.remaining() < 1 {
            return Err(WasmError::UnexpectedEof);
        }
        let b = self.bytes[self.pos];
        self.pos += 1;
        Ok(b)
    }

    pub fn read_u32(&mut self) -> WasmResult<u32> {
        self.read_leb128_u32()
    }

    pub fn read_u64(&mut self) -> WasmResult<u64> {
        self.read_leb128_u64()
    }

    pub fn read_leb128_u32(&mut self) -> WasmResult<u32> {
        let mut result: u32 = 0;
        let mut shift = 0;
        loop {
            let byte = self.read_u8()?;
            result |= ((byte & 0x7F) as u32) << shift;
            if byte & 0x80 == 0 {
                return Ok(result);
            }
            shift += 7;
            if shift >= 35 {
                return Err(WasmError::Validation("LEB128 overflow".to_string()));
            }
        }
    }

    pub fn read_leb128_u64(&mut self) -> WasmResult<u64> {
        let mut result: u64 = 0;
        let mut shift = 0;
        loop {
            let byte = self.read_u8()?;
            result |= ((byte & 0x7F) as u64) << shift;
            if byte & 0x80 == 0 {
                return Ok(result);
            }
            shift += 7;
            if shift >= 70 {
                return Err(WasmError::Validation("LEB128 overflow".to_string()));
            }
        }
    }

    pub fn read_leb128_i32(&mut self) -> WasmResult<i32> {
        let mut result: i32 = 0;
        let mut shift = 0;
        loop {
            let byte = self.read_u8()?;
            result |= ((byte & 0x7F) as i32) << shift;
            shift += 7;
            if byte & 0x80 == 0 {
                if shift < 32 && (byte & 0x40) != 0 {
                    result |= -(1 << shift);
                }
                return Ok(result);
            }
        }
    }

    pub fn read_leb128_i64(&mut self) -> WasmResult<i64> {
        let mut result: i64 = 0;
        let mut shift = 0;
        loop {
            let byte = self.read_u8()?;
            result |= ((byte & 0x7F) as i64) << shift;
            shift += 7;
            if byte & 0x80 == 0 {
                if shift < 64 && (byte & 0x40) != 0 {
                    result |= -(1 << shift);
                }
                return Ok(result);
            }
        }
    }

    pub fn read_bytes(&mut self, n: usize) -> WasmResult<&'a [u8]> {
        if self.remaining() < n {
            return Err(WasmError::UnexpectedEof);
        }
        let bytes = &self.bytes[self.pos..self.pos + n];
        self.pos += n;
        Ok(bytes)
    }

    pub fn read_name(&mut self) -> WasmResult<String> {
        let len = self.read_leb128_u32()? as usize;
        let bytes = self.read_bytes(len)?;
        String::from_utf8(bytes.to_vec())
            .map_err(|_| WasmError::Validation("Invalid UTF-8".to_string()))
    }

    pub fn read_vector<T, F>(&mut self, f: F) -> WasmResult<Vec<T>>
    where
        F: Fn(&mut Self) -> WasmResult<T>,
    {
        let len = self.read_leb128_u32()? as usize;
        let mut vec = Vec::with_capacity(len);
        for _ in 0..len {
            vec.push(f(self)?);
        }
        Ok(vec)
    }
}
'''
        output = self.output_dir / "reader.rs"
        output.write_text(code)
        print(f"Generated: {output}")

    def generate_decoder(self):
        """Genera el decoder principal"""
        code = '''//! Auto-generated WASM Decoder
//! Generated by Python - do not edit manually

use super::reader::Reader;
use super::types::*;

const WASM_MAGIC: [u8; 4] = [0x00, 0x61, 0x73, 0x6D];
const WASM_VERSION: [u8; 4] = [0x01, 0x00, 0x00, 0x00];

#[derive(Debug, Clone)]
pub struct Module {
    pub types: Vec<FuncType>,
    pub imports: Vec<Import>,
    pub functions: Vec<u32>, // type indices
    pub memories: Vec<MemoryType>,
    pub globals: Vec<Global>,
    pub exports: Vec<Export>,
    pub start: Option<u32>,
    pub table: Vec<u32>, // type indices
    pub code: Vec<FunctionBody>,
    pub data: Vec<DataSegment>,
}

#[derive(Debug, Clone)]
pub struct Global {
    pub ty: GlobalType,
    pub init: Vec<u8>, // init expr
}

#[derive(Debug, Clone)]
pub struct FunctionBody {
    pub locals: Vec<(u32, ValueType)>,
    pub code: Vec<u8>,
}

#[derive(Debug, Clone)]
pub struct DataSegment {
    pub memory_index: u32,
    pub offset: Vec<u8>,
    pub data: Vec<u8>,
}

pub struct Decoder<'a> {
    reader: Reader<'a>,
}

impl<'a> Decoder<'a> {
    pub fn new(bytes: &'a [u8]) -> Self {
        Self {
            reader: Reader::new(bytes),
        }
    }

    pub fn decode(mut self) -> WasmResult<Module> {
        // Magic number
        let magic = self.reader.read_bytes(4)?;
        if magic != WASM_MAGIC {
            return Err(WasmError::InvalidMagic);
        }

        // Version
        let version = self.reader.read_bytes(4)?;
        if version != WASM_VERSION {
            return Err(WasmError::InvalidVersion);
        }

        let mut module = Module {
            types: Vec::new(),
            imports: Vec::new(),
            functions: Vec::new(),
            memories: Vec::new(),
            globals: Vec::new(),
            exports: Vec::new(),
            start: None,
            table: Vec::new(),
            code: Vec::new(),
            data: Vec::new(),
        };

        // Sections
        while self.reader.remaining() > 0 {
            let section_id = self.reader.read_u8()?;
            let _section_size = self.reader.read_leb128_u32()?;

            match section_id {
                1 => module.types = self.read_type_section()?,
                2 => module.imports = self.read_import_section()?,
                3 => module.functions = self.read_function_section()?,
                4 => module.table = self.read_table_section()?,
                5 => module.memories = self.read_memory_section()?,
                6 => module.globals = self.read_global_section()?,
                7 => module.exports = self.read_export_section()?,
                8 => module.start = self.read_start_section()?,
                9 => module.code = self.read_code_section()?,
                10 => module.data = self.read_data_section()?,
                _ => {
                    // Skip unknown section
                    let size = self.reader.read_leb128_u32()? as usize;
                    self.reader.read_bytes(size)?;
                }
            }
        }

        Ok(module)
    }

    fn read_type_section(&mut self) -> WasmResult<Vec<FuncType>> {
        self.reader.read_vector(|r| {
            r.read_u8()?; // function type marker (0x60)
            let params = r.read_vector(Self::read_value_type)?;
            let results = r.read_vector(Self::read_value_type)?;
            Ok(FuncType { params, results })
        })
    }

    fn read_value_type(reader: &mut Reader) -> WasmResult<ValueType> {
        match reader.read_u8()? {
            0x7F => Ok(ValueType::I32),
            0x7E => Ok(ValueType::I64),
            0x7D => Ok(ValueType::F32),
            0x7C => Ok(ValueType::F64),
            0x7B => Ok(ValueType::V128),
            0x70 => Ok(ValueType::FuncRef),
            0x6F => Ok(ValueType::ExternRef),
            t => Err(WasmError::InvalidValueType(t)),
        }
    }

    fn read_import_section(&mut self) -> WasmResult<Vec<Import>> {
        self.reader.read_vector(|r| {
            let module = r.read_name()?;
            let field = r.read_name()?;
            let kind_byte = r.read_u8()?;
            let kind = match kind_byte {
                0x00 => ExternalKind::Function(r.read_leb128_u32()?),
                0x01 => {
                    let _ = Self::read_value_type(r)?;
                    let _ = r.read_leb128_u32()?; // limits min
                    ExternalKind::Table
                }
                0x02 => {
                    let _ = r.read_leb128_u32()?; // limits min
                    ExternalKind::Memory
                }
                0x03 => {
                    let _ = Self::read_value_type(r)?;
                    r.read_u8()?; // mut
                    ExternalKind::Global
                }
                _ => return Err(WasmError::Validation("Invalid import kind".to_string())),
            };
            Ok(Import { module, field, kind })
        })
    }

    fn read_function_section(&mut self) -> WasmResult<Vec<u32>> {
        self.reader.read_vector(|r| r.read_leb128_u32())
    }

    fn read_table_section(&mut self) -> WasmResult<Vec<u32>> {
        self.reader.read_vector(|r| {
            let _ = Self::read_value_type(r)?;
            r.read_leb128_u32()?;
            Ok(0)
        })
    }

    fn read_memory_section(&mut self) -> WasmResult<Vec<MemoryType>> {
        self.reader.read_vector(|r| {
            let flags = r.read_u8()?;
            let min = r.read_leb128_u32()?;
            let max = if flags & 0x01 != 0 {
                Some(r.read_leb128_u32()?)
            } else {
                None
            };
            Ok(MemoryType { limits: Limits { min, max } })
        })
    }

    fn read_global_section(&mut self) -> WasmResult<Vec<Global>> {
        self.reader.read_vector(|r| {
            let value_type = Self::read_value_type(r)?;
            let mutable = r.read_u8()? != 0;
            let init_size = r.read_leb128_u32()? as usize;
            let init = r.read_bytes(init_size)?.to_vec();
            Ok(Global {
                ty: GlobalType { value_type, mutable },
                init,
            })
        })
    }

    fn read_export_section(&mut self) -> WasmResult<Vec<Export>> {
        self.reader.read_vector(|r| {
            let name = r.read_name()?;
            let kind_byte = r.read_u8()?;
            let index = r.read_leb128_u32()?;
            let kind = match kind_byte {
                0x00 => ExternalKind::Function(index),
                0x01 => ExternalKind::Table,
                0x02 => ExternalKind::Memory,
                0x03 => ExternalKind::Global,
                _ => return Err(WasmError::Validation("Invalid export kind".to_string())),
            };
            Ok(Export { name, kind })
        })
    }

    fn read_start_section(&mut self) -> WasmResult<Option<u32>> {
        let idx = self.reader.read_leb128_u32()?;
        Ok(Some(idx))
    }

    fn read_code_section(&mut self) -> WasmResult<Vec<FunctionBody>> {
        self.reader.read_vector(|r| {
            let body_size = r.read_leb128_u32()? as usize;
            let _body_start = r.pos();
            let locals = r.read_vector(|r2| {
                let count = r2.read_leb128_u32()?;
                let ty = Self::read_value_type(r2)?;
                Ok((count, ty))
            })?;
            let remaining = body_size - (r.pos() - _body_start);
            let code = r.read_bytes(remaining)?.to_vec();
            Ok(FunctionBody { locals, code })
        })
    }

    fn read_data_section(&mut self) -> WasmResult<Vec<DataSegment>> {
        self.reader.read_vector(|r| {
            let flags = r.read_u8()?;
            let memory_index = if flags & 0x02 != 0 {
                r.read_leb128_u32()?
            } else {
                0
            };
            let offset_size = r.read_leb128_u32()? as usize;
            let offset = r.read_bytes(offset_size)?.to_vec();
            let data = r.read_vector(|r2| r2.read_u8())?;
            Ok(DataSegment { memory_index, offset, data })
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_decode_magic() {
        // Minimal WASM module: (module)
        let wasm = vec![0x00, 0x61, 0x73, 0x6D, 0x01, 0x00, 0x00, 0x00];
        let decoder = Decoder::new(&wasm);
        let result = decoder.decode();
        assert!(result.is_ok());
    }

    #[test]
    fn test_decode_invalid_magic() {
        let wasm = vec![0xFF, 0xFF, 0xFF, 0xFF, 0x01, 0x00, 0x00, 0x00];
        let decoder = Decoder::new(&wasm);
        let result = decoder.decode();
        assert!(result.is_err());
    }
}
'''
        output = self.output_dir / "decoder.rs"
        output.write_text(code)
        print(f"Generated: {output}")

    def generate_executor(self):
        """Genera el executor (interpreter)"""
        code = '''//! Auto-generated WASM Executor
//! Generated by Python - do not edit manually

use super::types::*;
use super::decoder::*;
use std::collections::HashMap;

pub struct Instance {
    pub module: Module,
    pub memory: Vec<u8>,
    pub globals: Vec<Value>,
    pub functions: HashMap<String, Value>,
    pub stack: Vec<Value>,
}

impl Instance {
    pub fn new(module: Module) -> Self {
        let mut globals = Vec::new();
        for global in &module.globals {
            globals.push(Value::I32(0)); // Simplified
        }

        let mut memory = Vec::new();
        for mem in &module.memories {
            let size = (mem.limits.min as usize) * 65536;
            memory = vec![0; size];
        }

        let mut functions = HashMap::new();
        for (i, export) in module.exports.iter().enumerate() {
            if let ExternalKind::Function(idx) = export.kind {
                functions.insert(export.name.clone(), Value::I32(idx as i32));
            }
        }

        Self {
            module,
            memory,
            globals,
            functions,
            stack: Vec::new(),
        }
    }

    pub fn call(&mut self, name: &str, args: &[Value]) -> WasmResult<Vec<Value>> {
        if let Some(func_idx) = self.functions.get(name).cloned() {
            if let Value::I32(idx) = func_idx {
                self.call_function(idx as u32, args)
            } else {
                Err(WasmError::Trap("Not a function".to_string()))
            }
        } else {
            Err(WasmError::Trap(format!("Function not found: {}", name)))
        }
    }

    fn call_function(&mut self, func_idx: u32, args: &[Value]) -> WasmResult<Vec<Value>> {
        let body = self.module.code.get(func_idx as usize)
            .ok_or(WasmError::InvalidFunction(func_idx))?
            .clone();

        let func_type_idx = self.module.functions.get(func_idx as usize)
            .copied()
            .ok_or(WasmError::InvalidFunction(func_idx))?;
        let func_type = self.module.types.get(func_type_idx as usize)
            .ok_or(WasmError::Validation("Invalid type index".to_string()))?
            .clone();

        // Push args onto stack
        for arg in args {
            self.stack.push(arg.clone());
        }

        // Execute bytecode
        self.execute(&body.code)?;

        // Pop results
        let mut results = Vec::new();
        for _ in &func_type.results {
            results.push(self.stack.pop().unwrap_or(Value::I32(0)));
        }
        results.reverse();

        Ok(results)
    }

    fn execute(&mut self, code: &[u8]) -> WasmResult<()> {
        let mut pc = 0;
        let mut locals: Vec<Value> = Vec::new();
        let mut blocks: Vec<BlockFrame> = Vec::new();

        while pc < code.len() {
            let opcode = code[pc];
            pc += 1;

            match opcode {
                0x00 => {
                    // unreachable
                    return Err(WasmError::Trap("unreachable".to_string()));
                }
                0x01 => {
                    // nop
                }
                0x41 => {
                    // i32.const
                    let (val, new_pc) = self.read_leb128_i32(code, pc)?;
                    self.stack.push(Value::I32(val));
                    pc = new_pc;
                }
                0x6A => {
                    // i32.add
                    let b = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    let a = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    if let (Value::I32(x), Value::I32(y)) = (a, b) {
                        self.stack.push(Value::I32(x.wrapping_add(y)));
                    } else {
                        return Err(WasmError::Trap("Type mismatch".to_string()));
                    }
                }
                0x6B => {
                    // i32.sub
                    let b = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    let a = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    if let (Value::I32(x), Value::I32(y)) = (a, b) {
                        self.stack.push(Value::I32(x.wrapping_sub(y)));
                    } else {
                        return Err(WasmError::Trap("Type mismatch".to_string()));
                    }
                }
                0x6C => {
                    // i32.mul
                    let b = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    let a = self.stack.pop().ok_or(WasmError::Trap("Stack underflow".to_string()))?;
                    if let (Value::I32(x), Value::I32(y)) = (a, b) {
                        self.stack.push(Value::I32(x.wrapping_mul(y)));
                    } else {
                        return Err(WasmError::Trap("Type mismatch".to_string()));
                    }
                }
                0x0B => {
                    // end
                    if blocks.is_empty() {
                        return Ok(());
                    }
                    blocks.pop();
                }
                0x1A => {
                    // drop
                    self.stack.pop();
                }
                0x1B => {
                    // select
                    let c = self.stack.pop().unwrap_or(Value::I32(0));
                    let b = self.stack.pop().unwrap_or(Value::I32(0));
                    let a = self.stack.pop().unwrap_or(Value::I32(0));
                    if let Value::I32(cond) = c {
                        self.stack.push(if cond != 0 { a } else { b });
                    }
                }
                _ => {
                    return Err(WasmError::InvalidOpcode(opcode));
                }
            }
        }

        Ok(())
    }

    fn read_leb128_i32(&self, code: &[u8], start: usize) -> WasmResult<(i32, usize)> {
        let mut result: i32 = 0;
        let mut shift = 0;
        let mut pc = start;

        loop {
            if pc >= code.len() {
                return Err(WasmError::UnexpectedEof);
            }
            let byte = code[pc];
            pc += 1;
            result |= ((byte & 0x7F) as i32) << shift;
            shift += 7;
            if byte & 0x80 == 0 {
                if shift < 32 && (byte & 0x40) != 0 {
                    result |= -(1 << shift);
                }
                return Ok((result, pc));
            }
        }
    }
}

struct BlockFrame {
    block_type: u8,
    start: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_instance_creation() {
        let module = Module {
            types: Vec::new(),
            imports: Vec::new(),
            functions: Vec::new(),
            memories: Vec::new(),
            globals: Vec::new(),
            exports: Vec::new(),
            start: None,
            table: Vec::new(),
            code: Vec::new(),
            data: Vec::new(),
        };
        let instance = Instance::new(module);
        assert_eq!(instance.globals.len(), 0);
    }
}
'''
        output = self.output_dir / "executor.rs"
        output.write_text(code)
        print(f"Generated: {output}")

    def generate_mod(self):
        """Genera el mod.rs del WASM engine"""
        code = '''//! Auto-generated WASM Engine
//! Generated by Python - do not edit manually
//!
//! Minimal WebAssembly implementation
//! Supports WASM MVP + basic opcodes

pub mod decoder;
pub mod executor;
pub mod reader;
pub mod types;

pub use decoder::{Decoder, Module, FunctionBody, Global, DataSegment};
pub use executor::Instance;
pub use types::{Value, ValueType, FuncType, WasmError, WasmResult};
'''
        output = self.output_dir / "mod.rs"
        output.write_text(code)
        print(f"Generated: {output}")


def main():
    print("=" * 60)
    print("  Noir Browser - WASM Engine Generator")
    print("  Minimal WASM MVP decoder + executor")
    print("=" * 60)

    gen = WasmGenerator()
    gen.generate_types()
    gen.generate_leb128()
    gen.generate_decoder()
    gen.generate_executor()
    gen.generate_mod()

    print()
    print("WASM Engine generated successfully!")
    print("Components:")
    print("  - types.rs      (Value types, errors)")
    print("  - reader.rs     (LEB128 decoder)")
    print("  - decoder.rs    (WASM binary parser)")
    print("  - executor.rs   (Interpreter)")


if __name__ == "__main__":
    main()
