#!/usr/bin/env python3
"""
Generador de JS Engine Minimalista para Noir Browser
Genera un subset de ES2024 optimizado para ~2000 líneas de Rust.
"""

from pathlib import Path
from typing import List, Dict

class JSEngineGenerator:
    def __init__(self, output_dir: str = "src/js_engine_v2"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_lexer(self):
        """Genera el lexer (tokenizer)"""
        tokens = [
            ("Keyword", ["let", "const", "var", "function", "return", "if", "else", "while", "for", "class", "new", "this", "true", "false", "null", "undefined"]),
            ("Operator", ["+", "-", "*", "/", "%", "=", "==", "===", "!=", "!==", "<", ">", "<=", ">=", "&&", "||", "!", "&", "|", "^", "~", "<<", ">>", ">>>"]),
            ("Punctuation", ["(", ")", "{", "}", "[", "]", ";", ",", ".", ":", "?"]),
            ("Literal", ["Number", "String", "Template", "Regex"]),
        ]

        code = r'''//! Auto-generated JS Lexer
//! Generated by Python - do not edit manually

use std::iter::Peekable;
use std::str::Chars;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
'''

        for category, names in tokens:
            for name in names:
                if category == "Keyword":
                    code += f"    Kw{name.capitalize()},\n"
                elif category == "Operator":
                    code += f"    Op{name},\n"
                elif category == "Punctuation":
                    code += f"    Punct{name},\n"
                elif category == "Literal":
                    code += f"    {name.capitalize()},\n"

        code += r'''    Identifier,
    Whitespace,
    Comment,
    Eof,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub value: String,
    pub line: u32,
    pub col: u32,
}

pub struct Lexer<'a> {
    input: Peekable<Chars<'a>>,
    line: u32,
    col: u32,
}

impl<'a> Lexer<'a> {
    pub fn new(input: &'a str) -> Self {
        Self {
            input: input.chars().peekable(),
            line: 1,
            col: 1,
        }
    }

    pub fn tokenize(&mut self) -> Vec<Token> {
        let mut tokens = Vec::new();
        while let Some(token) = self.next_token() {
            let is_ws = matches!(token.kind, TokenKind::Whitespace | TokenKind::Comment);
            if !is_ws {
                tokens.push(token.clone());
            }
            if matches!(token.kind, TokenKind::Eof) {
                break;
            }
        }
        tokens
    }

    fn next_token(&mut self) -> Option<Token> {
        let ch = *self.input.peek()?;

        if ch.is_whitespace() {
            return Some(self.read_whitespace());
        }

        if ch == '/' {
            return Some(self.read_comment_or_div());
        }

        if ch.is_ascii_digit() {
            return Some(self.read_number());
        }

        if ch == '"' || ch == '\'' {
            return Some(self.read_string());
        }

        if ch.is_alphabetic() || ch == '_' || ch == '$' {
            return Some(self.read_identifier());
        }

        Some(self.read_operator())
    }

    fn read_whitespace(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_whitespace() {
                if ch == '\n' {
                    self.line += 1;
                    self.col = 1;
                } else {
                    self.col += 1;
                }
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }
        Token { kind: TokenKind::Whitespace, value, line, col }
    }

    fn read_comment_or_div(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        value.push(self.input.next().unwrap());

        if self.input.peek() == Some(&'/') {
            value.push(self.input.next().unwrap());
            while let Some(&ch) = self.input.peek() {
                if ch == '\n' { break; }
                value.push(self.input.next().unwrap());
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else if self.input.peek() == Some(&'*') {
            value.push(self.input.next().unwrap());
            while let Some(ch) = self.input.next() {
                value.push(ch);
                if ch == '*' && self.input.peek() == Some(&'/') {
                    value.push(self.input.next().unwrap());
                    break;
                }
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else {
            Token { kind: TokenKind::Op("/".to_string()), value: "/".to_string(), line, col }
        }
    }

    fn read_number(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_ascii_digit() || ch == '.' {
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }
        Token { kind: TokenKind::Number, value, line, col }
    }

    fn read_string(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let quote = self.input.next().unwrap();
        let mut value = String::new();
        value.push(quote);
        while let Some(ch) = self.input.next() {
            value.push(ch);
            if ch == quote {
                break;
            }
            if ch == '\\' {
                if let Some(escaped) = self.input.next() {
                    value.push(escaped);
                }
            }
        }
        Token { kind: TokenKind::String, value, line, col }
    }

    fn read_identifier(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_alphanumeric() || ch == '_' || ch == '$' {
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }

        let kind = match value.as_str() {
'''

        for name in tokens[0][1]:
            code += f'            "{name}" => TokenKind::Kw{name.capitalize()},\n'

        code += r'''            "true" => TokenKind::KwTrue,
            "false" => TokenKind::KwFalse,
            "null" => TokenKind::KwNull,
            "undefined" => TokenKind::KwUndefined,
            "this" => TokenKind::KwThis,
            _ => TokenKind::Identifier,
        };

        Token { kind, value, line, col }
    }

    fn read_operator(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let ch = self.input.next().unwrap();
        let mut value = ch.to_string();

        if let Some(&next) = self.input.peek() {
            let two = format!("{}{}", ch, next);
            let two_char_ops = ["==", "!=", "<=", ">=", "&&", "||", "<<", ">>", "**", "=>", "++", "--", "+=", "-=", "*=", "/="];
            if two_char_ops.contains(&two.as_str()) {
                value.push(self.input.next().unwrap());
                if let Some(&next2) = self.input.peek() {
                    let three = format!("{}{}", value, next2);
                    let three_char_ops = ["===", "!==", ">>>", "**="];
                    if three_char_ops.contains(&three.as_str()) {
                        value.push(self.input.next().unwrap());
                    }
                }
            }
        }

        let kind = TokenKind::Op(value.clone());
        Token { kind, value, line, col }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tokenize_let() {
        let mut lexer = Lexer::new("let x = 42;");
        let tokens = lexer.tokenize();
        assert!(tokens.len() >= 5);
        assert!(matches!(tokens[0].kind, TokenKind::KwLet));
    }

    #[test]
    fn test_tokenize_function() {
        let mut lexer = Lexer::new("function foo() { return 1; }");
        let tokens = lexer.tokenize();
        assert!(tokens.len() > 5);
    }
}
'''

        output = self.output_dir / "lexer.rs"
        output.write_text(code)
        print(f"Generated: {output}")

    def generate_ast(self):
        """Genera el AST (Abstract Syntax Tree)"""
        code = '''//! Auto-generated JS AST
//! Generated by Python - do not edit manually

use std::boxed::Box;

#[derive(Debug, Clone)]
pub enum Expr {
    Number(f64),
    String(String),
    Bool(bool),
    Null,
    Undefined,
    Identifier(String),
    Binary {
        op: BinaryOp,
        left: Box<Expr>,
        right: Box<Expr>,
    },
    Unary {
        op: UnaryOp,
        operand: Box<Expr>,
    },
    Call {
        callee: Box<Expr>,
        args: Vec<Expr>,
    },
    Member {
        object: Box<Expr>,
        property: String,
    },
    Array(Vec<Expr>),
    Object(Vec<(String, Expr)>),
    Function {
        params: Vec<String>,
        body: Vec<Stmt>,
    },
    Assign {
        target: Box<Expr>,
        value: Box<Expr>,
    },
    New(Box<Expr>),
    This,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BinaryOp {
    Add, Sub, Mul, Div, Mod,
    Eq, Ne, StrictEq, StrictNe,
    Lt, Gt, LtEq, GtEq,
    And, Or,
    BitAnd, BitOr, BitXor,
    Shl, Shr,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum UnaryOp {
    Neg, Not, BitNot,
    TypeOf, Void, Delete,
}

#[derive(Debug, Clone)]
pub enum Stmt {
    VarDecl {
        name: String,
        value: Option<Expr>,
        is_const: bool,
    },
    Expr(Expr),
    If {
        condition: Expr,
        then_branch: Vec<Stmt>,
        else_branch: Option<Vec<Stmt>>,
    },
    While {
        condition: Expr,
        body: Vec<Stmt>,
    },
    For {
        init: Option<Box<Stmt>>,
        condition: Option<Expr>,
        update: Option<Expr>,
        body: Vec<Stmt>,
    },
    Return(Option<Expr>),
    Block(Vec<Stmt>),
    FunctionDecl {
        name: String,
        params: Vec<String>,
        body: Vec<Stmt>,
    },
    Break,
    Continue,
}

#[derive(Debug, Clone)]
pub struct Program {
    pub body: Vec<Stmt>,
}
'''
        output = self.output_dir / "ast.rs"
        output.write_text(code)
        print(f"Generated: {output}")

    def generate_interpreter(self):
        """Genera el interpreter (tree-walking)"""
        code = '''//! Auto-generated JS Interpreter
//! Generated by Python - do not edit manually

use std::collections::HashMap;
use std::rc::Rc;
use std::cell::RefCell;
use super::ast::*;

#[derive(Debug, Clone)]
pub enum Value {
    Number(f64),
    String(String),
    Bool(bool),
    Null,
    Undefined,
    Object(Rc<RefCell<HashMap<String, Value>>>),
    Function {
        params: Vec<String>,
        body: Vec<Stmt>,
        closure: Rc<RefCell<Env>>,
    },
    NativeFunction(fn(&[Value]) -> Result<Value, String>),
}

impl PartialEq for Value {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Value::Number(a), Value::Number(b)) => a == b,
            (Value::String(a), Value::String(b)) => a == b,
            (Value::Bool(a), Value::Bool(b)) => a == b,
            (Value::Null, Value::Null) => true,
            (Value::Undefined, Value::Undefined) => true,
            _ => false,
        }
    }
}

pub struct Env {
    variables: HashMap<String, Value>,
    parent: Option<Rc<RefCell<Env>>>,
}

impl Env {
    pub fn new() -> Self {
        Self {
            variables: HashMap::new(),
            parent: None,
        }
    }

    pub fn with_parent(parent: Rc<RefCell<Env>>) -> Self {
        Self {
            variables: HashMap::new(),
            parent: Some(parent),
        }
    }

    pub fn get(&self, name: &str) -> Option<Value> {
        if let Some(v) = self.variables.get(name) {
            return Some(v.clone());
        }
        if let Some(parent) = &self.parent {
            return parent.borrow().get(name);
        }
        None
    }

    pub fn set(&mut self, name: String, value: Value) {
        self.variables.insert(name, value);
    }
}

pub struct Interpreter {
    env: Rc<RefCell<Env>>,
    globals: Rc<RefCell<Env>>,
}

impl Interpreter {
    pub fn new() -> Self {
        let env = Rc::new(RefCell::new(Env::new()));
        let globals = env.clone();
        Self { env, globals }
    }

    pub fn interpret(&mut self, program: &Program) -> Result<Value, String> {
        let mut result = Value::Undefined;
        for stmt in &program.body {
            result = self.exec_stmt(stmt)?;
        }
        Ok(result)
    }

    fn exec_stmt(&mut self, stmt: &Stmt) -> Result<Value, String> {
        match stmt {
            Stmt::VarDecl { name, value, .. } => {
                let v = if let Some(expr) = value {
                    self.eval_expr(expr)?
                } else {
                    Value::Undefined
                };
                self.env.borrow_mut().set(name.clone(), v);
                Ok(Value::Undefined)
            }
            Stmt::Expr(expr) => self.eval_expr(expr),
            Stmt::Return(expr) => {
                let v = if let Some(e) = expr {
                    Some(self.eval_expr(e)?)
                } else {
                    None
                };
                Err(format!("return:{:?}", v))
            }
            Stmt::Block(stmts) => {
                let new_env = Rc::new(RefCell::new(Env::with_parent(self.env.clone())));
                let old_env = self.env.clone();
                self.env = new_env;
                let mut result = Value::Undefined;
                for s in stmts {
                    result = self.exec_stmt(s)?;
                }
                self.env = old_env;
                Ok(result)
            }
            Stmt::If { condition, then_branch, else_branch } => {
                let cond = self.eval_expr(condition)?;
                if self.is_truthy(&cond) {
                    for s in then_branch {
                        self.exec_stmt(s)?;
                    }
                } else if let Some(else_stmts) = else_branch {
                    for s in else_stmts {
                        self.exec_stmt(s)?;
                    }
                }
                Ok(Value::Undefined)
            }
            Stmt::While { condition, body } => {
                while self.is_truthy(&self.eval_expr(condition)?) {
                    for s in body {
                        match self.exec_stmt(s) {
                            Err(e) if e.starts_with("break:") => break,
                            Err(e) if e.starts_with("continue:") => continue,
                            Err(e) => return Err(e),
                            _ => {}
                        }
                    }
                }
                Ok(Value::Undefined)
            }
            _ => Ok(Value::Undefined),
        }
    }

    fn eval_expr(&mut self, expr: &Expr) -> Result<Value, String> {
        match expr {
            Expr::Number(n) => Ok(Value::Number(*n)),
            Expr::String(s) => Ok(Value::String(s.clone())),
            Expr::Bool(b) => Ok(Value::Bool(*b)),
            Expr::Null => Ok(Value::Null),
            Expr::Undefined => Ok(Value::Undefined),
            Expr::Identifier(name) => {
                self.env.borrow().get(name)
                    .ok_or_else(|| format!("Undefined variable: {}", name))
            }
            Expr::Binary { op, left, right } => {
                let l = self.eval_expr(left)?;
                let r = self.eval_expr(right)?;
                self.eval_binary(*op, &l, &r)
            }
            Expr::Unary { op, operand } => {
                let v = self.eval_expr(operand)?;
                self.eval_unary(*op, &v)
            }
            Expr::Call { callee, args } => {
                let func = self.eval_expr(callee)?;
                let evaluated_args: Result<Vec<Value>, String> = args.iter()
                    .map(|a| self.eval_expr(a))
                    .collect();
                self.call_function(&func, &evaluated_args?)
            }
            Expr::Member { object, property } => {
                let obj = self.eval_expr(object)?;
                if let Value::Object(map) = obj {
                    map.borrow().get(property)
                        .cloned()
                        .ok_or_else(|| format!("Property not found: {}", property))
                } else {
                    Err("Cannot access property of non-object".to_string())
                }
            }
            Expr::Assign { target, value } => {
                let v = self.eval_expr(value)?;
                if let Expr::Identifier(name) = &**target {
                    self.env.borrow_mut().set(name.clone(), v.clone());
                    Ok(v)
                } else {
                    Err("Invalid assignment target".to_string())
                }
            }
            _ => Ok(Value::Undefined),
        }
    }

    fn eval_binary(&self, op: BinaryOp, l: &Value, r: &Value) -> Result<Value, String> {
        match (l, r) {
            (Value::Number(a), Value::Number(b)) => {
                let result = match op {
                    BinaryOp::Add => a + b,
                    BinaryOp::Sub => a - b,
                    BinaryOp::Mul => a * b,
                    BinaryOp::Div => a / b,
                    BinaryOp::Mod => a % b,
                    BinaryOp::Lt => return Ok(Value::Bool(a < b)),
                    BinaryOp::Gt => return Ok(Value::Bool(a > b)),
                    BinaryOp::LtEq => return Ok(Value::Bool(a <= b)),
                    BinaryOp::GtEq => return Ok(Value::Bool(a >= b)),
                    BinaryOp::Eq | BinaryOp::StrictEq => return Ok(Value::Bool(a == b)),
                    BinaryOp::Ne | BinaryOp::StrictNe => return Ok(Value::Bool(a != b)),
                    _ => return Err("Invalid numeric operator".to_string()),
                };
                Ok(Value::Number(result))
            }
            (Value::String(a), Value::String(b)) if op == BinaryOp::Add => {
                Ok(Value::String(format!("{}{}", a, b)))
            }
            (Value::String(a), Value::Number(b)) if op == BinaryOp::Add => {
                Ok(Value::String(format!("{}{}", a, b)))
            }
            _ => Ok(Value::Bool(false)),
        }
    }

    fn eval_unary(&self, op: UnaryOp, v: &Value) -> Result<Value, String> {
        match op {
            UnaryOp::Neg => {
                if let Value::Number(n) = v {
                    Ok(Value::Number(-n))
                } else {
                    Err("Cannot negate non-number".to_string())
                }
            }
            UnaryOp::Not => Ok(Value::Bool(!self.is_truthy(v))),
            UnaryOp::TypeOf => Ok(Value::String(self.type_of(v))),
            _ => Ok(Value::Undefined),
        }
    }

    fn call_function(&mut self, func: &Value, args: &[Value]) -> Result<Value, String> {
        match func {
            Value::Function { params, body, closure } => {
                if args.len() != params.len() {
                    return Err(format!("Expected {} args, got {}", params.len(), args.len()));
                }
                let new_env = Rc::new(RefCell::new(Env::with_parent(closure.clone())));
                for (param, arg) in params.iter().zip(args.iter()) {
                    new_env.borrow_mut().set(param.clone(), arg.clone());
                }
                let old_env = self.env.clone();
                self.env = new_env;
                let result = self.interpret(&Program { body: body.clone() });
                self.env = old_env;
                match result {
                    Ok(v) => Ok(v),
                    Err(e) if e.starts_with("return:") => {
                        let v_str = &e[7..];
                        Ok(Value::Undefined) // Simplified
                    }
                    Err(e) => Err(e),
                }
            }
            Value::NativeFunction(f) => f(args),
            _ => Err("Not a function".to_string()),
        }
    }

    fn is_truthy(&self, v: &Value) -> bool {
        match v {
            Value::Bool(b) => *b,
            Value::Number(n) => *n != 0.0 && !n.is_nan(),
            Value::String(s) => !s.is_empty(),
            Value::Null | Value::Undefined => false,
            _ => true,
        }
    }

    fn type_of(&self, v: &Value) -> String {
        match v {
            Value::Number(_) => "number",
            Value::String(_) => "string",
            Value::Bool(_) => "boolean",
            Value::Null => "object",
            Value::Undefined => "undefined",
            Value::Object(_) => "object",
            Value::Function { .. } => "function",
            Value::NativeFunction(_) => "function",
        }.to_string()
    }
}
'''
        output = self.output_dir / "interpreter.rs"
        output.write_text(code)
        print(f"Generated: {output}")

    def generate_parser(self):
        """Genera el parser (AST builder)"""
        code = '''//! Auto-generated JS Parser
//! Generated by Python - do not edit manually

use super::ast::*;
use super::lexer::*;

pub struct Parser {
    tokens: Vec<Token>,
    pos: usize,
}

impl Parser {
    pub fn new(tokens: Vec<Token>) -> Self {
        Self { tokens, pos: 0 }
    }

    pub fn parse(&mut self) -> Result<Program, String> {
        let mut body = Vec::new();
        while !self.is_eof() {
            body.push(self.parse_stmt()?);
        }
        Ok(Program { body })
    }

    fn parse_stmt(&mut self) -> Result<Stmt, String> {
        let token = self.peek().clone();

        match &token.kind {
            TokenKind::KwLet | TokenKind::KwConst | TokenKind::KwVar => {
                self.parse_var_decl()
            }
            TokenKind::KwFunction => self.parse_function_decl(),
            TokenKind::KwIf => self.parse_if(),
            TokenKind::KwWhile => self.parse_while(),
            TokenKind::KwFor => self.parse_for(),
            TokenKind::KwReturn => {
                self.advance();
                let expr = if !self.is_eof() && !matches!(self.peek().kind, TokenKind::Punct(";".to_string())) {
                    Some(self.parse_expr()?)
                } else {
                    None
                };
                self.expect(TokenKind::Punct(";".to_string()))?;
                Ok(Stmt::Return(expr))
            }
            TokenKind::Punct("{".to_string()) => self.parse_block(),
            _ => {
                let expr = self.parse_expr()?;
                self.expect(TokenKind::Punct(";".to_string()))?;
                Ok(Stmt::Expr(expr))
            }
        }
    }

    fn parse_var_decl(&mut self) -> Result<Stmt, String> {
        let is_const = matches!(self.peek().kind, TokenKind::KwConst);
        self.advance();
        let name = self.expect_identifier()?;
        let value = if matches!(self.peek().kind, TokenKind::Op("=".to_string())) {
            self.advance();
            Some(self.parse_expr()?)
        } else {
            None
        };
        self.expect(TokenKind::Punct(";".to_string()))?;
        Ok(Stmt::VarDecl { name, value, is_const })
    }

    fn parse_function_decl(&mut self) -> Result<Stmt, String> {
        self.advance();
        let name = self.expect_identifier()?;
        self.expect(TokenKind::Punct("(".to_string()))?;
        let mut params = Vec::new();
        while !matches!(self.peek().kind, TokenKind::Punct(")".to_string())) {
            params.push(self.expect_identifier()?);
            if matches!(self.peek().kind, TokenKind::Punct(",".to_string())) {
                self.advance();
            } else {
                break;
            }
        }
        self.expect(TokenKind::Punct(")".to_string()))?;
        let body = self.parse_block()?;
        if let Stmt::Block(stmts) = body {
            Ok(Stmt::FunctionDecl { name, params, body: stmts })
        } else {
            Err("Expected function body".to_string())
        }
    }

    fn parse_if(&mut self) -> Result<Stmt, String> {
        self.advance();
        self.expect(TokenKind::Punct("(".to_string()))?;
        let condition = self.parse_expr()?;
        self.expect(TokenKind::Punct(")".to_string()))?;
        let then_branch = if let Stmt::Block(stmts) = self.parse_stmt()? {
            stmts
        } else {
            return Err("Expected block after if".to_string());
        };
        let else_branch = if matches!(self.peek().kind, TokenKind::KwElse) {
            self.advance();
            if let Stmt::Block(stmts) = self.parse_stmt()? {
                Some(stmts)
            } else {
                return Err("Expected block after else".to_string());
            }
        } else {
            None
        };
        Ok(Stmt::If { condition, then_branch, else_branch })
    }

    fn parse_while(&mut self) -> Result<Stmt, String> {
        self.advance();
        self.expect(TokenKind::Punct("(".to_string()))?;
        let condition = self.parse_expr()?;
        self.expect(TokenKind::Punct(")".to_string()))?;
        let body = if let Stmt::Block(stmts) = self.parse_stmt()? {
            stmts
        } else {
            return Err("Expected block after while".to_string());
        };
        Ok(Stmt::While { condition, body })
    }

    fn parse_for(&mut self) -> Result<Stmt, String> {
        self.advance();
        self.expect(TokenKind::Punct("(".to_string()))?;
        let init = if matches!(self.peek().kind, TokenKind::Punct(";".to_string())) {
            None
        } else {
            Some(Box::new(self.parse_var_decl()?))
        };
        let condition = if matches!(self.peek().kind, TokenKind::Punct(";".to_string())) {
            None
        } else {
            Some(self.parse_expr()?)
        };
        self.expect(TokenKind::Punct(";".to_string()))?;
        let update = if matches!(self.peek().kind, TokenKind::Punct(")".to_string())) {
            None
        } else {
            Some(self.parse_expr()?)
        };
        self.expect(TokenKind::Punct(")".to_string()))?;
        let body = if let Stmt::Block(stmts) = self.parse_stmt()? {
            stmts
        } else {
            return Err("Expected block after for".to_string());
        };
        Ok(Stmt::For { init, condition, update, body })
    }

    fn parse_block(&mut self) -> Result<Stmt, String> {
        self.expect(TokenKind::Punct("{".to_string()))?;
        let mut stmts = Vec::new();
        while !matches!(self.peek().kind, TokenKind::Punct("}".to_string())) && !self.is_eof() {
            stmts.push(self.parse_stmt()?);
        }
        self.expect(TokenKind::Punct("}".to_string()))?;
        Ok(Stmt::Block(stmts))
    }

    fn parse_expr(&mut self) -> Result<Expr, String> {
        self.parse_assignment()
    }

    fn parse_assignment(&mut self) -> Result<Expr, String> {
        let left = self.parse_additive()?;
        if matches!(self.peek().kind, TokenKind::Op("=".to_string())) {
            self.advance();
            let value = self.parse_assignment()?;
            return Ok(Expr::Assign {
                target: Box::new(left),
                value: Box::new(value),
            });
        }
        Ok(left)
    }

    fn parse_additive(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_multiplicative()?;
        while matches!(self.peek().kind, TokenKind::Op("+".to_string()) | TokenKind::Op("-".to_string())) {
            let op = if matches!(self.peek().kind, TokenKind::Op("+".to_string())) {
                BinaryOp::Add
            } else {
                BinaryOp::Sub
            };
            self.advance();
            let right = self.parse_multiplicative()?;
            left = Expr::Binary {
                op,
                left: Box::new(left),
                right: Box::new(right),
            };
        }
        Ok(left)
    }

    fn parse_multiplicative(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_unary()?;
        while matches!(self.peek().kind,
            TokenKind::Op("*".to_string()) | TokenKind::Op("/".to_string()) | TokenKind::Op("%".to_string())) {
            let op = match self.peek().kind {
                TokenKind::Op(s) if s == "*" => BinaryOp::Mul,
                TokenKind::Op(s) if s == "/" => BinaryOp::Div,
                _ => BinaryOp::Mod,
            };
            self.advance();
            let right = self.parse_unary()?;
            left = Expr::Binary {
                op,
                left: Box::new(left),
                right: Box::new(right),
            };
        }
        Ok(left)
    }

    fn parse_unary(&mut self) -> Result<Expr, String> {
        match &self.peek().kind {
            TokenKind::Op(s) if s == "!" => {
                self.advance();
                let operand = self.parse_unary()?;
                Ok(Expr::Unary { op: UnaryOp::Not, operand: Box::new(operand) })
            }
            TokenKind::Op(s) if s == "-" => {
                self.advance();
                let operand = self.parse_unary()?;
                Ok(Expr::Unary { op: UnaryOp::Neg, operand: Box::new(operand) })
            }
            _ => self.parse_call(),
        }
    }

    fn parse_call(&mut self) -> Result<Expr, String> {
        let mut expr = self.parse_primary()?;
        loop {
            match &self.peek().kind {
                TokenKind::Punct("(".to_string()) => {
                    self.advance();
                    let mut args = Vec::new();
                    while !matches!(self.peek().kind, TokenKind::Punct(")".to_string())) {
                        args.push(self.parse_expr()?);
                        if matches!(self.peek().kind, TokenKind::Punct(",".to_string())) {
                            self.advance();
                        } else {
                            break;
                        }
                    }
                    self.expect(TokenKind::Punct(")".to_string()))?;
                    expr = Expr::Call { callee: Box::new(expr), args };
                }
                TokenKind::Punct(".".to_string()) => {
                    self.advance();
                    let prop = self.expect_identifier()?;
                    expr = Expr::Member { object: Box::new(expr), property: prop };
                }
                _ => break,
            }
        }
        Ok(expr)
    }

    fn parse_primary(&mut self) -> Result<Expr, String> {
        let token = self.peek().clone();
        match token.kind {
            TokenKind::Number => {
                self.advance();
                let n: f64 = token.value.parse().map_err(|_| "Invalid number".to_string())?;
                Ok(Expr::Number(n))
            }
            TokenKind::String => {
                self.advance();
                Ok(Expr::String(token.value))
            }
            TokenKind::KwTrue => { self.advance(); Ok(Expr::Bool(true)) }
            TokenKind::KwFalse => { self.advance(); Ok(Expr::Bool(false)) }
            TokenKind::KwNull => { self.advance(); Ok(Expr::Null) }
            TokenKind::KwUndefined => { self.advance(); Ok(Expr::Undefined) }
            TokenKind::KwThis => { self.advance(); Ok(Expr::This) }
            TokenKind::Identifier => {
                self.advance();
                Ok(Expr::Identifier(token.value))
            }
            TokenKind::Punct(s) if s == "(" => {
                self.advance();
                let expr = self.parse_expr()?;
                self.expect(TokenKind::Punct(")".to_string()))?;
                Ok(expr)
            }
            _ => Err(format!("Unexpected token: {:?}", token)),
        }
    }

    fn peek(&self) -> &Token {
        &self.tokens[self.pos]
    }

    fn advance(&mut self) {
        if self.pos < self.tokens.len() - 1 {
            self.pos += 1;
        }
    }

    fn is_eof(&self) -> bool {
        matches!(self.peek().kind, TokenKind::Eof)
    }

    fn expect(&mut self, kind: TokenKind) -> Result<(), String> {
        if std::mem::discriminant(&self.peek().kind) == std::mem::discriminant(&kind) {
            self.advance();
            Ok(())
        } else {
            Err(format!("Expected {:?}, got {:?}", kind, self.peek().kind))
        }
    }

    fn expect_identifier(&mut self) -> Result<String, String> {
        let token = self.peek().clone();
        if matches!(token.kind, TokenKind::Identifier) {
            self.advance();
            Ok(token.value)
        } else {
            Err(format!("Expected identifier, got {:?}", token.kind))
        }
    }
}
'''
        output = self.output_dir / "parser.rs"
        output.write_text(code)
        print(f"Generated: {output}")


def main():
    print("=" * 60)
    print("  Noir Browser - JS Engine Generator")
    print("  Subset ES2024 minimalista (~2000 lineas)")
    print("=" * 60)

    gen = JSEngineGenerator()
    gen.generate_lexer()
    gen.generate_ast()
    gen.generate_parser()
    gen.generate_interpreter()

    print()
    print("JS Engine generated successfully!")
    print("Components:")
    print("  - lexer.rs       (Tokenizador)")
    print("  - ast.rs         (Abstract Syntax Tree)")
    print("  - parser.rs      (Parser)")
    print("  - interpreter.rs (Tree-walking interpreter)")


if __name__ == "__main__":
    main()
