#!/usr/bin/env python3
"""
Generador de JS Engine v3 con DOM completo para Noir Browser
JS engine minimalista pero potente con DOM API completa.
~1500 lineas de Rust generadas.
"""

from pathlib import Path
import shutil

class JSEngineV3Generator:
    def __init__(self, output_dir: str = "src/js_engine_v3"):
        self.output_dir = Path(output_dir)
        if self.output_dir.exists():
            shutil.rmtree(self.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_all(self):
        """Genera todos los archivos del JS engine v3"""
        self.generate_mod()
        self.generate_value()
        self.generate_env()
        self.generate_ast()
        self.generate_lexer()
        self.generate_parser()
        self.generate_interpreter()
        self.generate_dom()
        self.generate_console()
        self.generate_timer()
        self.generate_fetch()
        self.generate_builtins()
        print()
        print("=" * 60)
        print("  JS Engine v3 con DOM completo - GENERATED")
        print("=" * 60)

    def generate_mod(self):
        content = '''//! JS Engine v3 - Minimalista con DOM completo
//! Generated by Python - do not edit manually

pub mod value;
pub mod env;
pub mod ast;
pub mod lexer;
pub mod parser;
pub mod interpreter;
pub mod dom;
pub mod console;
pub mod timer;
pub mod fetch;
pub mod builtins;

pub use value::JsValue;
pub use env::Env;
pub use interpreter::Interpreter;
pub use dom::{Dom, DomNode, DomEvent};
'''
        (self.output_dir / "mod.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'mod.rs'}")

    def generate_value(self):
        content = r'''//! JsValue - Valores del JS engine
//! Generated by Python

use std::rc::Rc;
use std::cell::RefCell;
use std::collections::HashMap;
use super::ast::*;
use super::dom::DomNode;

#[derive(Debug, Clone)]
pub enum JsValue {
    Undefined,
    Null,
    Boolean(bool),
    Number(f64),
    String(String),
    Object(Rc<RefCell<HashMap<String, JsValue>>>),
    Array(Rc<RefCell<Vec<JsValue>>>),
    Function {
        name: String,
        params: Vec<String>,
        body: Vec<Stmt>,
        closure: Rc<RefCell<super::env::Env>>,
    },
    NativeFunction {
        name: String,
        func: fn(&[JsValue]) -> Result<JsValue, String>,
    },
    DomElement(Rc<RefCell<DomNode>>),
}

impl PartialEq for JsValue {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (JsValue::Undefined, JsValue::Undefined) => true,
            (JsValue::Null, JsValue::Null) => true,
            (JsValue::Boolean(a), JsValue::Boolean(b)) => a == b,
            (JsValue::Number(a), JsValue::Number(b)) => a == b,
            (JsValue::String(a), JsValue::String(b)) => a == b,
            _ => false,
        }
    }
}

impl JsValue {
    pub fn type_of(&self) -> &'static str {
        match self {
            JsValue::Undefined => "undefined",
            JsValue::Null => "object",
            JsValue::Boolean(_) => "boolean",
            JsValue::Number(_) => "number",
            JsValue::String(_) => "string",
            JsValue::Object(_) | JsValue::Array(_) => "object",
            JsValue::Function { .. } | JsValue::NativeFunction { .. } => "function",
            JsValue::DomElement(_) => "object",
        }
    }

    pub fn is_truthy(&self) -> bool {
        match self {
            JsValue::Boolean(b) => *b,
            JsValue::Number(n) => *n != 0.0 && !n.is_nan(),
            JsValue::String(s) => !s.is_empty(),
            JsValue::Undefined | JsValue::Null => false,
            _ => true,
        }
    }

    pub fn to_string(&self) -> String {
        match self {
            JsValue::Undefined => "undefined".to_string(),
            JsValue::Null => "null".to_string(),
            JsValue::Boolean(b) => b.to_string(),
            JsValue::Number(n) => {
                if n.is_nan() { "NaN".to_string() }
                else if n.is_infinite() { if *n > 0.0 { "Infinity".to_string() } else { "-Infinity".to_string() } }
                else { n.to_string() }
            }
            JsValue::String(s) => s.clone(),
            JsValue::Object(_) => "[object Object]".to_string(),
            JsValue::Array(arr) => {
                let elements = arr.borrow();
                let strs: Vec<String> = elements.iter().map(|e| e.to_string()).collect();
                strs.join(",")
            }
            _ => "[function]".to_string(),
        }
    }

    pub fn to_number(&self) -> f64 {
        match self {
            JsValue::Number(n) => *n,
            JsValue::Boolean(true) => 1.0,
            JsValue::Boolean(false) => 0.0,
            JsValue::String(s) => s.parse().unwrap_or(f64::NAN),
            JsValue::Null => 0.0,
            JsValue::Undefined => f64::NAN,
            _ => f64::NAN,
        }
    }
}
'''
        (self.output_dir / "value.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'value.rs'}")

    def generate_env(self):
        content = r'''//! Environment - Almacena variables y scope chain
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use super::value::JsValue;

#[derive(Debug, Clone)]
pub struct Env {
    variables: HashMap<String, JsValue>,
    parent: Option<Rc<RefCell<Env>>>,
}

impl Env {
    pub fn new() -> Self {
        Self {
            variables: HashMap::new(),
            parent: None,
        }
    }

    pub fn with_parent(parent: Rc<RefCell<Env>>) -> Self {
        Self {
            variables: HashMap::new(),
            parent: Some(parent),
        }
    }

    pub fn get(&self, name: &str) -> Option<JsValue> {
        if let Some(v) = self.variables.get(name) {
            return Some(v.clone());
        }
        if let Some(parent) = &self.parent {
            return parent.borrow().get(name);
        }
        None
    }

    pub fn set(&mut self, name: String, value: JsValue) {
        self.variables.insert(name, value);
    }

    pub fn has(&self, name: &str) -> bool {
        self.variables.contains_key(name)
    }
}
'''
        (self.output_dir / "env.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'env.rs'}")

    def generate_ast(self):
        content = r'''//! AST - Abstract Syntax Tree
//! Generated by Python

#[derive(Debug, Clone)]
pub enum Expr {
    Number(f64),
    String(String),
    Bool(bool),
    Null,
    Undefined,
    Identifier(String),
    Binary {
        op: BinaryOp,
        left: Box<Expr>,
        right: Box<Expr>,
    },
    Unary {
        op: UnaryOp,
        operand: Box<Expr>,
    },
    Call {
        callee: Box<Expr>,
        args: Vec<Expr>,
    },
    Member {
        object: Box<Expr>,
        property: String,
        computed: bool,
    },
    Array(Vec<Expr>),
    Object(Vec<(String, Expr)>),
    Function {
        params: Vec<String>,
        body: Vec<Stmt>,
    },
    Arrow {
        params: Vec<String>,
        body: Box<Expr>,
    },
    Assign {
        target: Box<Expr>,
        value: Box<Expr>,
    },
    New(Box<Expr>),
    This,
    Template(Vec<TemplatePart>),
}

#[derive(Debug, Clone)]
pub enum TemplatePart {
    String(String),
    Expr(Expr),
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BinaryOp {
    Add, Sub, Mul, Div, Mod,
    Eq, StrictEq, Ne, StrictNe,
    Lt, Gt, LtEq, GtEq,
    And, Or,
    BitAnd, BitOr, BitXor,
    Shl, Shr,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum UnaryOp {
    Neg, Not, BitNot,
    TypeOf, Void, Delete,
}

#[derive(Debug, Clone)]
pub enum Stmt {
    VarDecl {
        name: String,
        value: Option<Expr>,
        is_const: bool,
    },
    Expr(Expr),
    If {
        condition: Expr,
        then_branch: Vec<Stmt>,
        else_branch: Option<Vec<Stmt>>,
    },
    While {
        condition: Expr,
        body: Vec<Stmt>,
    },
    For {
        init: Option<Box<Stmt>>,
        condition: Option<Expr>,
        update: Option<Expr>,
        body: Vec<Stmt>,
    },
    Return(Option<Expr>),
    Block(Vec<Stmt>),
    FunctionDecl {
        name: String,
        params: Vec<String>,
        body: Vec<Stmt>,
    },
    Break,
    Continue,
    Try {
        body: Vec<Stmt>,
        catch_param: Option<String>,
        catch_body: Option<Vec<Stmt>>,
        finally: Option<Vec<Stmt>>,
    },
    Throw(Expr),
}

#[derive(Debug, Clone)]
pub struct Program {
    pub body: Vec<Stmt>,
}
'''
        (self.output_dir / "ast.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'ast.rs'}")

    def generate_lexer(self):
        content = r'''//! Lexer - Tokenizador
//! Generated by Python

use std::iter::Peekable;
use std::str::Chars;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    // Keywords
    KwLet, KwConst, KwVar,
    KwFunction, KwReturn,
    KwIf, KwElse, KwWhile, KwFor,
    KwClass, KwNew, KwThis,
    KwTrue, KwFalse, KwNull, KwUndefined,
    KwBreak, KwContinue,
    KwTry, KwCatch, KwFinally, KwThrow,
    KwDelete, KwTypeof, KwVoid, KwIn, KwOf,
    KwInstanceof, KwNew2,
    // Literals
    Number, String, Template, Regex,
    // Identifier
    Identifier,
    // Operators (specific kinds)
    OpAdd, OpSub, OpMul, OpDiv, OpMod,
    OpAssign, OpAddAssign, OpSubAssign, OpMulAssign, OpDivAssign,
    OpEq, OpStrictEq, OpNotEq, OpStrictNotEq,
    OpLt, OpGt, OpLtEq, OpGtEq,
    OpAnd, OpOr, OpNot,
    OpBitAnd, OpBitOr, OpBitXor, OpBitNot,
    OpShl, OpShr,
    OpInc, OpDec,
    // Punctuation
    PunctLParen, PunctRParen,
    PunctLBrace, PunctRBrace,
    PunctLBracket, PunctRBracket,
    PunctSemi, PunctComma, PunctDot,
    PunctColon, PunctQuestion,
    PunctArrow, PunctSpread,
    // Special
    Whitespace, Comment, Eof,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub value: String,
    pub line: u32,
    pub col: u32,
}

pub struct Lexer<'a> {
    input: Peekable<Chars<'a>>,
    line: u32,
    col: u32,
}

impl<'a> Lexer<'a> {
    pub fn new(input: &'a str) -> Self {
        Self {
            input: input.chars().peekable(),
            line: 1,
            col: 1,
        }
    }

    pub fn tokenize(&mut self) -> Vec<Token> {
        let mut tokens = Vec::new();
        while let Some(token) = self.next_token() {
            let is_ws = matches!(token.kind, TokenKind::Whitespace | TokenKind::Comment);
            if !is_ws {
                tokens.push(token.clone());
            }
            if matches!(token.kind, TokenKind::Eof) {
                break;
            }
        }
        tokens
    }

    fn next_token(&mut self) -> Option<Token> {
        let ch = *self.input.peek()?;
        if ch.is_whitespace() { return Some(self.read_whitespace()); }
        if ch == '/' { return Some(self.read_comment_or_div()); }
        if ch.is_ascii_digit() { return Some(self.read_number()); }
        if ch == '"' || ch == '\'' { return Some(self.read_string()); }
        if ch == '`' { return Some(self.read_template()); }
        if ch.is_alphabetic() || ch == '_' || ch == '$' {
            return Some(self.read_identifier());
        }
        Some(self.read_operator())
    }

    fn read_whitespace(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_whitespace() {
                if ch == '\n' { self.line += 1; self.col = 1; }
                else { self.col += 1; }
                value.push(self.input.next().unwrap());
            } else { break; }
        }
        Token { kind: TokenKind::Whitespace, value, line, col }
    }

    fn read_comment_or_div(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        value.push(self.input.next().unwrap());
        if self.input.peek() == Some(&'/') {
            value.push(self.input.next().unwrap());
            while let Some(&ch) = self.input.peek() {
                if ch == '\n' { break; }
                value.push(self.input.next().unwrap());
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else if self.input.peek() == Some(&'*') {
            value.push(self.input.next().unwrap());
            while let Some(ch) = self.input.next() {
                value.push(ch);
                if ch == '*' && self.input.peek() == Some(&'/') {
                    value.push(self.input.next().unwrap());
                    break;
                }
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else {
            Token { kind: TokenKind::OpDiv, value: "/".to_string(), line, col }
        }
    }

    fn read_number(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_ascii_digit() || ch == '.' {
                value.push(self.input.next().unwrap());
            } else { break; }
        }
        Token { kind: TokenKind::Number, value, line, col }
    }

    fn read_string(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let quote = self.input.next().unwrap();
        let mut value = String::new();
        value.push(quote);
        while let Some(ch) = self.input.next() {
            value.push(ch);
            if ch == quote { break; }
            if ch == '\\' {
                if let Some(escaped) = self.input.next() {
                    value.push(escaped);
                }
            }
        }
        Token { kind: TokenKind::String, value, line, col }
    }

    fn read_template(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        value.push(self.input.next().unwrap());
        while let Some(ch) = self.input.next() {
            value.push(ch);
            if ch == '`' { break; }
            if ch == '\\' {
                if let Some(escaped) = self.input.next() {
                    value.push(escaped);
                }
            }
        }
        Token { kind: TokenKind::Template, value, line, col }
    }

    fn read_identifier(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_alphanumeric() || ch == '_' || ch == '$' {
                value.push(self.input.next().unwrap());
            } else { break; }
        }
        let kind = match value.as_str() {
            "let" => TokenKind::KwLet, "const" => TokenKind::KwConst, "var" => TokenKind::KwVar,
            "function" => TokenKind::KwFunction, "return" => TokenKind::KwReturn,
            "if" => TokenKind::KwIf, "else" => TokenKind::KwElse,
            "while" => TokenKind::KwWhile, "for" => TokenKind::KwFor,
            "class" => TokenKind::KwClass, "new" => TokenKind::KwNew, "this" => TokenKind::KwThis,
            "true" => TokenKind::KwTrue, "false" => TokenKind::KwFalse,
            "null" => TokenKind::KwNull, "undefined" => TokenKind::KwUndefined,
            "break" => TokenKind::KwBreak, "continue" => TokenKind::KwContinue,
            "try" => TokenKind::KwTry, "catch" => TokenKind::KwCatch, "finally" => TokenKind::KwFinally,
            "throw" => TokenKind::KwThrow, "delete" => TokenKind::KwDelete,
            "typeof" => TokenKind::KwTypeof, "void" => TokenKind::KwVoid,
            "in" => TokenKind::KwIn, "of" => TokenKind::KwOf,
            "instanceof" => TokenKind::KwInstanceof,
            _ => TokenKind::Identifier,
        };
        Token { kind, value, line, col }
    }

    fn read_operator(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let ch = self.input.next().unwrap();
        let value = ch.to_string();
        let kind = match value.as_str() {
            "+" => TokenKind::OpAdd, "-" => TokenKind::OpSub, "*" => TokenKind::OpMul,
            "/" => TokenKind::OpDiv, "%" => TokenKind::OpMod, "=" => TokenKind::OpAssign,
            "(" => TokenKind::PunctLParen, ")" => TokenKind::PunctRParen,
            "{" => TokenKind::PunctLBrace, "}" => TokenKind::PunctRBrace,
            "[" => TokenKind::PunctLBracket, "]" => TokenKind::PunctRBracket,
            ";" => TokenKind::PunctSemi, "," => TokenKind::PunctComma, "." => TokenKind::PunctDot,
            ":" => TokenKind::PunctColon, "?" => TokenKind::PunctQuestion,
            "!" => TokenKind::OpNot, "<" => TokenKind::OpLt, ">" => TokenKind::OpGt,
            "&" => TokenKind::OpBitAnd, "|" => TokenKind::OpBitOr, "^" => TokenKind::OpBitXor,
            "~" => TokenKind::OpBitNot,
            _ => TokenKind::Eof,
        };
        Token { kind, value, line, col }
    }
}
'''
        (self.output_dir / "lexer.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'lexer.rs'}")

    def generate_parser(self):
        content = r'''//! Parser - AST builder
//! Generated by Python

use super::ast::*;
use super::lexer::*;

pub struct Parser {
    tokens: Vec<Token>,
    pos: usize,
}

impl Parser {
    pub fn new(tokens: Vec<Token>) -> Self { Self { tokens, pos: 0 } }

    pub fn parse(&mut self) -> Result<Program, String> {
        let mut body = Vec::new();
        while !self.is_eof() { body.push(self.parse_stmt()?); }
        Ok(Program { body })
    }

    fn parse_stmt(&mut self) -> Result<Stmt, String> {
        match self.peek().kind {
            TokenKind::KwLet | TokenKind::KwConst | TokenKind::KwVar => self.parse_var_decl(),
            TokenKind::KwFunction => self.parse_function_decl(),
            TokenKind::KwIf => self.parse_if(),
            TokenKind::KwWhile => self.parse_while(),
            TokenKind::KwFor => self.parse_for(),
            TokenKind::KwReturn => self.parse_return(),
            TokenKind::KwBreak => { self.advance(); Ok(Stmt::Break) }
            TokenKind::KwContinue => { self.advance(); Ok(Stmt::Continue) }
            TokenKind::KwTry => self.parse_try(),
            TokenKind::KwThrow => self.parse_throw(),
            _ => {
                let expr = self.parse_expr()?;
                Ok(Stmt::Expr(expr))
            }
        }
    }

    fn parse_var_decl(&mut self) -> Result<Stmt, String> {
        let is_const = matches!(self.peek().kind, TokenKind::KwConst);
        self.advance();
        let name = self.expect_identifier()?;
        let value = if matches!(self.peek().kind, TokenKind::OpAssign) {
            self.advance();
            Some(self.parse_expr()?)
        } else { None };
        Ok(Stmt::VarDecl { name, value, is_const })
    }

    fn parse_function_decl(&mut self) -> Result<Stmt, String> {
        self.advance();
        let name = self.expect_identifier()?;
        let params = self.parse_params()?;
        let body_stmts = self.parse_block_body()?;
        Ok(Stmt::FunctionDecl { name, params, body: body_stmts })
    }

    fn parse_params(&mut self) -> Result<Vec<String>, String> {
        if !matches!(self.peek().kind, TokenKind::PunctLParen) {
            return Err("Expected (".to_string());
        }
        self.advance();
        let mut params = Vec::new();
        while !matches!(self.peek().kind, TokenKind::PunctRParen) {
            if matches!(self.peek().kind, TokenKind::PunctSpread) { self.advance(); }
            params.push(self.expect_identifier()?);
            if matches!(self.peek().kind, TokenKind::PunctComma) { self.advance(); }
        }
        self.advance();
        Ok(params)
    }

    fn parse_block_body(&mut self) -> Result<Vec<Stmt>, String> {
        if !matches!(self.peek().kind, TokenKind::PunctLBrace) {
            return Err("Expected {".to_string());
        }
        self.advance();
        let mut stmts = Vec::new();
        while !matches!(self.peek().kind, TokenKind::PunctRBrace) && !self.is_eof() {
            stmts.push(self.parse_stmt()?);
        }
        self.advance();
        Ok(stmts)
    }

    fn parse_if(&mut self) -> Result<Stmt, String> {
        self.advance();
        let condition = self.parse_expr()?;
        let then_branch = self.parse_block_body()?;
        let else_branch = if matches!(self.peek().kind, TokenKind::KwElse) {
            self.advance();
            Some(self.parse_block_body()?)
        } else { None };
        Ok(Stmt::If { condition, then_branch, else_branch })
    }

    fn parse_while(&mut self) -> Result<Stmt, String> {
        self.advance();
        let condition = self.parse_expr()?;
        let body = self.parse_block_body()?;
        Ok(Stmt::While { condition, body })
    }

    fn parse_for(&mut self) -> Result<Stmt, String> {
        self.advance();
        if !matches!(self.peek().kind, TokenKind::PunctLParen) { return Err("Expected (".to_string()); }
        self.advance();
        let init = if matches!(self.peek().kind, TokenKind::PunctSemi) {
            None
        } else if matches!(self.peek().kind, TokenKind::KwLet | TokenKind::KwConst | TokenKind::KwVar) {
            Some(Box::new(self.parse_var_decl()?))
        } else {
            let e = self.parse_expr()?;
            Some(Box::new(Stmt::Expr(e)))
        };
        if !matches!(self.peek().kind, TokenKind::PunctSemi) { return Err("Expected ;".to_string()); }
        self.advance();
        let condition = if matches!(self.peek().kind, TokenKind::PunctSemi) {
            None
        } else { Some(self.parse_expr()?) };
        if !matches!(self.peek().kind, TokenKind::PunctSemi) { return Err("Expected ;".to_string()); }
        self.advance();
        let update = if matches!(self.peek().kind, TokenKind::PunctRParen) {
            None
        } else { Some(self.parse_expr()?) };
        if !matches!(self.peek().kind, TokenKind::PunctRParen) { return Err("Expected )".to_string()); }
        self.advance();
        let body = self.parse_block_body()?;
        Ok(Stmt::For { init, condition, update, body })
    }

    fn parse_return(&mut self) -> Result<Stmt, String> {
        self.advance();
        let value = if matches!(self.peek().kind, TokenKind::PunctSemi) || self.is_eof() {
            None
        } else { Some(self.parse_expr()?) };
        Ok(Stmt::Return(value))
    }

    fn parse_try(&mut self) -> Result<Stmt, String> {
        self.advance();
        let body = self.parse_block_body()?;
        let mut catch_param = None;
        let mut catch_body = None;
        if matches!(self.peek().kind, TokenKind::KwCatch) {
            self.advance();
            if matches!(self.peek().kind, TokenKind::PunctLParen) {
                self.advance();
                catch_param = Some(self.expect_identifier()?);
                self.advance();
            }
            catch_body = Some(self.parse_block_body()?);
        }
        let mut finally = None;
        if matches!(self.peek().kind, TokenKind::KwFinally) {
            self.advance();
            finally = Some(self.parse_block_body()?);
        }
        Ok(Stmt::Try { body, catch_param, catch_body, finally })
    }

    fn parse_throw(&mut self) -> Result<Stmt, String> {
        self.advance();
        let expr = self.parse_expr()?;
        Ok(Stmt::Throw(expr))
    }

    fn parse_expr(&mut self) -> Result<Expr, String> { self.parse_assignment() }

    fn parse_assignment(&mut self) -> Result<Expr, String> {
        let left = self.parse_ternary()?;
        if matches!(self.peek().kind, TokenKind::OpAssign) {
            self.advance();
            let value = self.parse_assignment()?;
            return Ok(Expr::Assign { target: Box::new(left), value: Box::new(value) });
        }
        Ok(left)
    }

    fn parse_ternary(&mut self) -> Result<Expr, String> {
        let condition = self.parse_or()?;
        if matches!(self.peek().kind, TokenKind::PunctQuestion) {
            self.advance();
            let _then_branch = self.parse_assignment()?;
            if !matches!(self.peek().kind, TokenKind::PunctColon) { return Err("Expected :".to_string()); }
            self.advance();
            let else_branch = self.parse_assignment()?;
            return Ok(Expr::Binary {
                op: BinaryOp::And,
                left: Box::new(condition),
                right: Box::new(else_branch),
            });
        }
        Ok(condition)
    }

    fn parse_or(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_and()?;
        while matches!(self.peek().kind, TokenKind::OpOr) {
            self.advance();
            let right = self.parse_and()?;
            left = Expr::Binary { op: BinaryOp::Or, left: Box::new(left), right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_and(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_equality()?;
        while matches!(self.peek().kind, TokenKind::OpAnd) {
            self.advance();
            let right = self.parse_equality()?;
            left = Expr::Binary { op: BinaryOp::And, left: Box::new(left), right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_equality(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_relational()?;
        loop {
            let op = match self.peek().kind {
                TokenKind::OpEq => Some(BinaryOp::Eq),
                TokenKind::OpStrictEq => Some(BinaryOp::StrictEq),
                TokenKind::OpNotEq => Some(BinaryOp::Ne),
                TokenKind::OpStrictNotEq => Some(BinaryOp::StrictNe),
                _ => None,
            };
            if let Some(op) = op {
                self.advance();
                let right = self.parse_relational()?;
                left = Expr::Binary { op, left: Box::new(left), right: Box::new(right) };
            } else { break; }
        }
        Ok(left)
    }

    fn parse_relational(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_additive()?;
        loop {
            let op = match self.peek().kind {
                TokenKind::OpLt => Some(BinaryOp::Lt),
                TokenKind::OpGt => Some(BinaryOp::Gt),
                TokenKind::OpLtEq => Some(BinaryOp::LtEq),
                TokenKind::OpGtEq => Some(BinaryOp::GtEq),
                _ => None,
            };
            if let Some(op) = op {
                self.advance();
                let right = self.parse_additive()?;
                left = Expr::Binary { op, left: Box::new(left), right: Box::new(right) };
            } else { break; }
        }
        Ok(left)
    }

    fn parse_additive(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_multiplicative()?;
        while matches!(self.peek().kind, TokenKind::OpAdd | TokenKind::OpSub) {
            let op = match self.peek().kind {
                TokenKind::OpAdd => BinaryOp::Add,
                _ => BinaryOp::Sub,
            };
            self.advance();
            let right = self.parse_multiplicative()?;
            left = Expr::Binary { op, left: Box::new(left), right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_multiplicative(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_unary()?;
        while matches!(self.peek().kind, TokenKind::OpMul | TokenKind::OpDiv | TokenKind::OpMod) {
            let op = match self.peek().kind {
                TokenKind::OpMul => BinaryOp::Mul,
                TokenKind::OpDiv => BinaryOp::Div,
                _ => BinaryOp::Mod,
            };
            self.advance();
            let right = self.parse_unary()?;
            left = Expr::Binary { op, left: Box::new(left), right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_unary(&mut self) -> Result<Expr, String> {
        match self.peek().kind {
            TokenKind::OpSub => {
                self.advance();
                let operand = self.parse_unary()?;
                Ok(Expr::Unary { op: UnaryOp::Neg, operand: Box::new(operand) })
            }
            TokenKind::OpNot => {
                self.advance();
                let operand = self.parse_unary()?;
                Ok(Expr::Unary { op: UnaryOp::Not, operand: Box::new(operand) })
            }
            TokenKind::OpBitNot => {
                self.advance();
                let operand = self.parse_unary()?;
                Ok(Expr::Unary { op: UnaryOp::BitNot, operand: Box::new(operand) })
            }
            TokenKind::KwTypeof => {
                self.advance();
                let operand = self.parse_unary()?;
                Ok(Expr::Unary { op: UnaryOp::TypeOf, operand: Box::new(operand) })
            }
            TokenKind::KwVoid => {
                self.advance();
                let operand = self.parse_unary()?;
                Ok(Expr::Unary { op: UnaryOp::Void, operand: Box::new(operand) })
            }
            TokenKind::KwNew => {
                self.advance();
                let callee = self.parse_postfix()?;
                Ok(Expr::New(Box::new(callee)))
            }
            _ => self.parse_postfix(),
        }
    }

    fn parse_postfix(&mut self) -> Result<Expr, String> {
        let mut expr = self.parse_primary()?;
        loop {
            match self.peek().kind {
                TokenKind::PunctDot => {
                    self.advance();
                    let prop = self.expect_identifier()?;
                    expr = Expr::Member { object: Box::new(expr), property: prop, computed: false };
                }
                TokenKind::PunctLBracket => {
                    self.advance();
                    let _prop_expr = self.parse_expr()?;
                    if !matches!(self.peek().kind, TokenKind::PunctRBracket) { return Err("Expected ]".to_string()); }
                    self.advance();
                    let prop_str = String::from("[computed]");
                    expr = Expr::Member { object: Box::new(expr), property: prop_str, computed: true };
                }
                TokenKind::PunctLParen => {
                    self.advance();
                    let mut args = Vec::new();
                    while !matches!(self.peek().kind, TokenKind::PunctRParen) {
                        args.push(self.parse_expr()?);
                        if matches!(self.peek().kind, TokenKind::PunctComma) { self.advance(); }
                    }
                    self.advance();
                    expr = Expr::Call { callee: Box::new(expr), args };
                }
                _ => break,
            }
        }
        Ok(expr)
    }

    fn parse_primary(&mut self) -> Result<Expr, String> {
        let token = self.peek().clone();
        match token.kind {
            TokenKind::Number => {
                self.advance();
                let n: f64 = token.value.parse().unwrap_or(0.0);
                Ok(Expr::Number(n))
            }
            TokenKind::String => {
                self.advance();
                let s = token.value[1..token.value.len()-1].to_string();
                Ok(Expr::String(s))
            }
            TokenKind::Template => {
                self.advance();
                Ok(Expr::String(token.value))
            }
            TokenKind::KwTrue => { self.advance(); Ok(Expr::Bool(true)) }
            TokenKind::KwFalse => { self.advance(); Ok(Expr::Bool(false)) }
            TokenKind::KwNull => { self.advance(); Ok(Expr::Null) }
            TokenKind::KwUndefined => { self.advance(); Ok(Expr::Undefined) }
            TokenKind::KwThis => { self.advance(); Ok(Expr::This) }
            TokenKind::Identifier => {
                self.advance();
                Ok(Expr::Identifier(token.value))
            }
            TokenKind::PunctLParen => {
                self.advance();
                let expr = self.parse_expr()?;
                if !matches!(self.peek().kind, TokenKind::PunctRParen) { return Err("Expected )".to_string()); }
                self.advance();
                Ok(expr)
            }
            TokenKind::PunctLBracket => {
                self.advance();
                let mut elements = Vec::new();
                while !matches!(self.peek().kind, TokenKind::PunctRBracket) {
                    elements.push(self.parse_expr()?);
                    if matches!(self.peek().kind, TokenKind::PunctComma) { self.advance(); }
                }
                self.advance();
                Ok(Expr::Array(elements))
            }
            TokenKind::PunctLBrace => {
                self.advance();
                let mut pairs = Vec::new();
                while !matches!(self.peek().kind, TokenKind::PunctRBrace) {
                    let key = if let TokenKind::String = self.peek().kind {
                        let s = self.peek().value.clone();
                        self.advance();
                        if matches!(self.peek().kind, TokenKind::PunctColon) { self.advance(); }
                        s[1..s.len()-1].to_string()
                    } else if let TokenKind::Identifier = self.peek().kind {
                        let s = self.peek().value.clone();
                        self.advance();
                        if matches!(self.peek().kind, TokenKind::PunctColon) { self.advance(); }
                        s
                    } else {
                        return Err("Expected key".to_string());
                    };
                    let value = self.parse_expr()?;
                    pairs.push((key, value));
                    if matches!(self.peek().kind, TokenKind::PunctComma) { self.advance(); }
                }
                self.advance();
                Ok(Expr::Object(pairs))
            }
            _ => Err(format!("Unexpected token: {:?}", token.kind)),
        }
    }

    fn peek(&self) -> &Token { &self.tokens[self.pos] }
    fn advance(&mut self) { if self.pos < self.tokens.len().saturating_sub(1) { self.pos += 1; } }
    fn is_eof(&self) -> bool { self.pos >= self.tokens.len() || matches!(self.peek().kind, TokenKind::Eof) }
    fn expect_identifier(&mut self) -> Result<String, String> {
        let token = self.peek().clone();
        if matches!(token.kind, TokenKind::Identifier) {
            self.advance();
            Ok(token.value)
        } else {
            Err(format!("Expected identifier, got {:?}", token.kind))
        }
    }
}
'''
        (self.output_dir / "parser.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'parser.rs'}")

    def generate_interpreter(self):
        content = r'''//! Interpreter - Tree-walking execution
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use super::ast::*;
use super::value::JsValue;
use super::env::Env;
use super::dom::Dom;
use super::console::Console;
use super::timer::TimerQueue;
use super::fetch::FetchQueue;
use super::builtins::register_builtins;

pub struct Interpreter {
    pub env: Rc<RefCell<Env>>,
    pub global: Rc<RefCell<Env>>,
    pub dom: Rc<RefCell<Dom>>,
    pub console: Rc<RefCell<Console>>,
    pub timers: Rc<RefCell<TimerQueue>>,
    pub fetches: Rc<RefCell<FetchQueue>>,
    pub return_value: Rc<RefCell<Option<JsValue>>>,
    pub had_error: bool,
}

impl Interpreter {
    pub fn new() -> Self {
        let env = Rc::new(RefCell::new(Env::new()));
        let global = env.clone();
        let dom = Rc::new(RefCell::new(Dom::new()));
        let console = Rc::new(RefCell::new(Console::new()));
        let timers = Rc::new(RefCell::new(TimerQueue::new()));
        let fetches = Rc::new(RefCell::new(FetchQueue::new()));

        // Register built-in objects (Math, JSON, etc.)
        register_builtins(&env, &dom, &console);

        Self {
            env, global, dom, console, timers, fetches,
            return_value: Rc::new(RefCell::new(None)),
            had_error: false,
        }
    }

    pub fn interpret(&mut self, program: &Program) -> Result<JsValue, String> {
        let mut result = JsValue::Undefined;
        for stmt in &program.body {
            self.exec_stmt(stmt)?;
        }
        Ok(result)
    }

    pub fn exec_stmt(&mut self, stmt: &Stmt) -> Result<JsValue, String> {
        match stmt {
            Stmt::VarDecl { name, value, .. } => {
                let v = if let Some(expr) = value { self.eval_expr(expr)? } else { JsValue::Undefined };
                self.env.borrow_mut().set(name.clone(), v);
                Ok(JsValue::Undefined)
            }
            Stmt::Expr(expr) => self.eval_expr(expr),
            Stmt::Return(expr) => {
                let v = if let Some(e) = expr { self.eval_expr(e)? } else { JsValue::Undefined };
                *self.return_value.borrow_mut() = Some(v);
                Ok(JsValue::Undefined)
            }
            Stmt::Block(stmts) => {
                let new_env = Rc::new(RefCell::new(Env::with_parent(self.env.clone())));
                let old_env = self.env.clone();
                self.env = new_env;
                let mut result = Ok(JsValue::Undefined);
                for s in stmts {
                    if let Err(e) = self.exec_stmt(s) { result = Err(e); break; }
                    if self.return_value.borrow().is_some() { break; }
                }
                self.env = old_env;
                result
            }
            Stmt::If { condition, then_branch, else_branch } => {
                let cond = self.eval_expr(condition)?;
                if cond.is_truthy() {
                    self.exec_block(then_branch)
                } else if let Some(else_stmts) = else_branch {
                    self.exec_block(else_stmts)
                } else {
                    Ok(JsValue::Undefined)
                }
            }
            Stmt::While { condition, body } => {
                loop {
                    let cond = self.eval_expr(condition)?;
                    if !cond.is_truthy() { break; }
                    match self.exec_block(body) {
                        Ok(_) => {}
                        Err(e) => return Err(e),
                    }
                    if self.return_value.borrow().is_some() { break; }
                }
                Ok(JsValue::Undefined)
            }
            Stmt::For { init, condition, update, body } => {
                let new_env = Rc::new(RefCell::new(Env::with_parent(self.env.clone())));
                let old_env = self.env.clone();
                self.env = new_env;
                if let Some(init_stmt) = init {
                    self.exec_stmt(init_stmt)?;
                }
                loop {
                    if let Some(cond_expr) = condition {
                        let cond = self.eval_expr(cond_expr)?;
                        if !cond.is_truthy() { break; }
                    }
                    let _ = self.exec_block(body);
                    if self.return_value.borrow().is_some() { break; }
                    if let Some(upd) = update {
                        let _ = self.eval_expr(upd);
                    }
                }
                self.env = old_env;
                Ok(JsValue::Undefined)
            }
            Stmt::Break => Err("BREAK".to_string()),
            Stmt::Continue => Err("CONTINUE".to_string()),
            Stmt::FunctionDecl { name, params, body } => {
                let func = JsValue::Function {
                    name: name.clone(),
                    params: params.clone(),
                    body: body.clone(),
                    closure: self.env.clone(),
                };
                self.env.borrow_mut().set(name.clone(), func);
                Ok(JsValue::Undefined)
            }
            Stmt::Try { body, catch_param, catch_body, finally } => {
                let result = self.exec_block(body);
                if result.is_err() {
                    if let (Some(param), Some(cb)) = (catch_param, catch_body) {
                        let new_env = Rc::new(RefCell::new(Env::with_parent(self.env.clone())));
                        new_env.borrow_mut().set(param.clone(), JsValue::String("Error".to_string()));
                        let old_env = self.env.clone();
                        self.env = new_env;
                        let _ = self.exec_block(cb);
                        self.env = old_env;
                    }
                }
                if let Some(fb) = finally {
                    let _ = self.exec_block(fb);
                }
                Ok(JsValue::Undefined)
            }
            Stmt::Throw(expr) => {
                let v = self.eval_expr(expr)?;
                Err(format!("THROW:{}", v.to_string()))
            }
        }
    }

    fn exec_block(&mut self, stmts: &[Stmt]) -> Result<JsValue, String> {
        let mut result = Ok(JsValue::Undefined);
        for s in stmts {
            result = self.exec_stmt(s);
            if result.is_err() { break; }
            if self.return_value.borrow().is_some() { break; }
        }
        result
    }

    pub fn eval_expr(&mut self, expr: &Expr) -> Result<JsValue, String> {
        match expr {
            Expr::Number(n) => Ok(JsValue::Number(*n)),
            Expr::String(s) => Ok(JsValue::String(s.clone())),
            Expr::Bool(b) => Ok(JsValue::Boolean(*b)),
            Expr::Null => Ok(JsValue::Null),
            Expr::Undefined => Ok(JsValue::Undefined),
            Expr::This => {
                self.env.borrow().get("this").ok_or_else(|| "No 'this'".to_string())
            }
            Expr::Identifier(name) => {
                self.env.borrow().get(name)
                    .ok_or_else(|| format!("ReferenceError: {} is not defined", name))
            }
            Expr::Binary { op, left, right } => {
                let l = self.eval_expr(left)?;
                let r = self.eval_expr(right)?;
                self.eval_binary(*op, &l, &r)
            }
            Expr::Unary { op, operand } => {
                let v = self.eval_expr(operand)?;
                self.eval_unary(*op, &v)
            }
            Expr::Call { callee, args } => {
                let func = self.eval_expr(callee)?;
                let evaluated_args: Result<Vec<JsValue>, String> = args.iter().map(|a| self.eval_expr(a)).collect();
                self.call_function(&func, &evaluated_args?)
            }
            Expr::Member { object, property, computed } => {
                let obj = self.eval_expr(object)?;
                self.get_member(&obj, property, *computed)
            }
            Expr::Array(elements) => {
                let mut arr = Vec::new();
                for e in elements {
                    arr.push(self.eval_expr(e)?);
                }
                Ok(JsValue::Array(Rc::new(RefCell::new(arr))))
            }
            Expr::Object(pairs) => {
                let mut map = HashMap::new();
                for (k, v) in pairs {
                    map.insert(k.clone(), self.eval_expr(v)?);
                }
                Ok(JsValue::Object(Rc::new(RefCell::new(map))))
            }
            Expr::Assign { target, value } => {
                let v = self.eval_expr(value)?;
                if let Expr::Identifier(name) = &**target {
                    self.env.borrow_mut().set(name.clone(), v.clone());
                    Ok(v)
                } else {
                    Err("Invalid assignment".to_string())
                }
            }
            Expr::New(callee) => {
                let func = self.eval_expr(callee)?;
                self.call_function(&func, &[])
            }
            _ => Ok(JsValue::Undefined),
        }
    }

    fn get_member(&self, obj: &JsValue, property: &str, _computed: bool) -> Result<JsValue, String> {
        match obj {
            JsValue::Object(map) => {
                Ok(map.borrow().get(property).cloned().unwrap_or(JsValue::Undefined))
            }
            JsValue::Array(arr) => {
                if property == "length" {
                    Ok(JsValue::Number(arr.borrow().len() as f64))
                } else {
                    Ok(JsValue::Undefined)
                }
            }
            JsValue::String(s) => {
                if property == "length" {
                    Ok(JsValue::Number(s.len() as f64))
                } else {
                    Ok(JsValue::Undefined)
                }
            }
            JsValue::DomElement(node) => {
                // Use DOM API to get property
                self.dom.borrow().get_property(&node.borrow().tag_name, property)
            }
            _ => Ok(JsValue::Undefined),
        }
    }

    fn eval_binary(&self, op: BinaryOp, l: &JsValue, r: &JsValue) -> Result<JsValue, String> {
        match (l, r) {
            (JsValue::Number(a), JsValue::Number(b)) => {
                let result = match op {
                    BinaryOp::Add => a + b, BinaryOp::Sub => a - b, BinaryOp::Mul => a * b,
                    BinaryOp::Div => a / b, BinaryOp::Mod => a % b,
                    BinaryOp::Lt => return Ok(JsValue::Boolean(a < b)),
                    BinaryOp::Gt => return Ok(JsValue::Boolean(a > b)),
                    BinaryOp::LtEq => return Ok(JsValue::Boolean(a <= b)),
                    BinaryOp::GtEq => return Ok(JsValue::Boolean(a >= b)),
                    BinaryOp::Eq | BinaryOp::StrictEq => return Ok(JsValue::Boolean(a == b)),
                    BinaryOp::Ne | BinaryOp::StrictNe => return Ok(JsValue::Boolean(a != b)),
                    BinaryOp::And => return Ok(JsValue::Boolean(*a != 0.0 && *b != 0.0)),
                    BinaryOp::Or => return Ok(JsValue::Boolean(*a != 0.0 || *b != 0.0)),
                    _ => return Ok(JsValue::Boolean(false)),
                };
                Ok(JsValue::Number(result))
            }
            (JsValue::String(a), JsValue::String(b)) => {
                match op {
                    BinaryOp::Add => Ok(JsValue::String(format!("{}{}", a, b))),
                    BinaryOp::Eq | BinaryOp::StrictEq => Ok(JsValue::Boolean(a == b)),
                    BinaryOp::Ne | BinaryOp::StrictNe => Ok(JsValue::Boolean(a != b)),
                    _ => Ok(JsValue::Boolean(false)),
                }
            }
            (JsValue::String(a), JsValue::Number(b)) => {
                if matches!(op, BinaryOp::Add) {
                    Ok(JsValue::String(format!("{}{}", a, b.to_string())))
                } else {
                    Ok(JsValue::Boolean(false))
                }
            }
            (JsValue::Number(a), JsValue::String(b)) => {
                if matches!(op, BinaryOp::Add) {
                    Ok(JsValue::String(format!("{}{}", a.to_string(), b)))
                } else {
                    Ok(JsValue::Boolean(false))
                }
            }
            (JsValue::Boolean(a), JsValue::Boolean(b)) => {
                match op {
                    BinaryOp::Eq | BinaryOp::StrictEq => Ok(JsValue::Boolean(a == b)),
                    BinaryOp::Ne | BinaryOp::StrictNe => Ok(JsValue::Boolean(a != b)),
                    BinaryOp::And => Ok(JsValue::Boolean(*a && *b)),
                    BinaryOp::Or => Ok(JsValue::Boolean(*a || *b)),
                    _ => Ok(JsValue::Boolean(false)),
                }
            }
            _ => Ok(JsValue::Boolean(false)),
        }
    }

    fn eval_unary(&self, op: UnaryOp, v: &JsValue) -> Result<JsValue, String> {
        match op {
            UnaryOp::Neg => Ok(JsValue::Number(-v.to_number())),
            UnaryOp::Not => Ok(JsValue::Boolean(!v.is_truthy())),
            UnaryOp::BitNot => Ok(JsValue::Number(!(v.to_number() as i64) as f64)),
            UnaryOp::TypeOf => Ok(JsValue::String(v.type_of().to_string())),
            UnaryOp::Void => Ok(JsValue::Undefined),
            UnaryOp::Delete => Ok(JsValue::Boolean(true)),
        }
    }

    fn call_function(&mut self, func: &JsValue, args: &[JsValue]) -> Result<JsValue, String> {
        match func {
            JsValue::Function { name, params, body, closure } => {
                let new_env = Rc::new(RefCell::new(Env::with_parent(closure.clone())));
                for (param, arg) in params.iter().zip(args.iter()) {
                    new_env.borrow_mut().set(param.clone(), arg.clone());
                }
                let old_env = self.env.clone();
                self.env = new_env;
                *self.return_value.borrow_mut() = None;
                for s in body {
                    let _ = self.exec_stmt(s);
                    if self.return_value.borrow().is_some() { break; }
                }
                self.env = old_env;
                let result = self.return_value.borrow_mut().take().unwrap_or(JsValue::Undefined);
                Ok(result)
            }
            JsValue::NativeFunction { name, func } => {
                func(args)
            }
            _ => Err(format!("{} is not a function", func.type_of())),
        }
    }
}
'''
        (self.output_dir / "interpreter.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'interpreter.rs'}")

    def generate_dom(self):
        content = r'''//! DOM - Document Object Model
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use super::value::JsValue;

#[derive(Debug, Clone)]
pub struct DomNode {
    pub id: u64,
    pub tag_name: String,
    pub attributes: HashMap<String, String>,
    pub text_content: String,
    pub inner_html: String,
    pub children: Vec<Rc<RefCell<DomNode>>>,
    pub parent: Option<Rc<RefCell<DomNode>>>,
    pub style: HashMap<String, String>,
    pub class_list: Vec<String>,
}

impl DomNode {
    pub fn new(tag_name: &str) -> Self {
        Self {
            id: Dom::next_id(),
            tag_name: tag_name.to_uppercase(),
            attributes: HashMap::new(),
            text_content: String::new(),
            inner_html: String::new(),
            children: Vec::new(),
            parent: None,
            style: HashMap::new(),
            class_list: Vec::new(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct DomEvent {
    pub event_type: String,
    pub target_id: u64,
    pub bubbles: bool,
    pub cancelable: bool,
}

pub struct Dom {
    pub document: Rc<RefCell<DomNode>>,
    pub root: Rc<RefCell<DomNode>>,
    pub body: Rc<RefCell<DomNode>>,
    next_node_id: u64,
}

impl Dom {
    pub fn new() -> Self {
        let document = Rc::new(RefCell::new(DomNode::new("#document")));
        let html = Rc::new(RefCell::new(DomNode::new("HTML")));
        let head = Rc::new(RefCell::new(DomNode::new("HEAD")));
        let body = Rc::new(RefCell::new(DomNode::new("BODY")));

        html.borrow_mut().children.push(Rc::clone(&head));
        html.borrow_mut().children.push(Rc::clone(&body));
        head.borrow_mut().parent = Some(Rc::clone(&html));
        body.borrow_mut().parent = Some(Rc::clone(&html));
        document.borrow_mut().children.push(Rc::clone(&html));
        html.borrow_mut().parent = Some(Rc::clone(&document));

        let next_id = Rc::new(RefCell::new(0));
        Self {
            document,
            root: html,
            body,
            next_node_id: 1,
        }
    }

    pub fn next_id() -> u64 {
        use std::sync::atomic::{AtomicU64, Ordering};
        static COUNTER: AtomicU64 = AtomicU64::new(1);
        COUNTER.fetch_add(1, Ordering::SeqCst)
    }

    /// Create new element
    pub fn create_element(tag: &str) -> JsValue {
        let node = DomNode::new(tag);
        JsValue::DomElement(Rc::new(RefCell::new(node)))
    }

    /// Get element by ID
    pub fn get_element_by_id(&self, id: &str) -> Option<JsValue> {
        Self::find_by_id(&self.body, id).map(|n| JsValue::DomElement(n))
    }

    fn find_by_id(node: &Rc<RefCell<DomNode>>, id: &str) -> Option<Rc<RefCell<DomNode>>> {
        if node.borrow().attributes.get("id").map(|v| v == id).unwrap_or(false) {
            return Some(Rc::clone(node));
        }
        for child in &node.borrow().children {
            if let Some(found) = Self::find_by_id(child, id) {
                return Some(found);
            }
        }
        None
    }

    /// Query selector (simplified CSS)
    pub fn query_selector(&self, selector: &str) -> Option<JsValue> {
        Self::query(&self.body, selector).map(|n| JsValue::DomElement(n))
    }

    fn query(node: &Rc<RefCell<DomNode>>, selector: &str) -> Option<Rc<RefCell<DomNode>>> {
        let s = selector.trim();
        if let Some(rest) = s.strip_prefix('#') {
            return Self::find_by_id(node, rest);
        }
        if let Some(rest) = s.strip_prefix('.') {
            for child in &node.borrow().children {
                if child.borrow().class_list.contains(&rest.to_string()) {
                    return Some(Rc::clone(child));
                }
                if let Some(found) = Self::query(child, s) {
                    return Some(found);
                }
            }
            return None;
        }
        if node.borrow().tag_name.to_lowercase() == s.to_lowercase() {
            return Some(Rc::clone(node));
        }
        for child in &node.borrow().children {
            if let Some(found) = Self::query(child, s) {
                return Some(found);
            }
        }
        None
    }

    /// Query all (returns Array)
    pub fn query_selector_all(&self, selector: &str) -> JsValue {
        let mut results = Vec::new();
        Self::query_all(&self.body, selector, &mut results);
        JsValue::Array(Rc::new(RefCell::new(results)))
    }

    fn query_all(node: &Rc<RefCell<DomNode>>, selector: &str, results: &mut Vec<JsValue>) {
        let s = selector.trim();
        if let Some(class) = s.strip_prefix('.') {
            for child in &node.borrow().children {
                if child.borrow().class_list.contains(&class.to_string()) {
                    results.push(JsValue::DomElement(Rc::clone(child)));
                }
                Self::query_all(child, s, results);
            }
            return;
        }
        if node.borrow().tag_name.to_lowercase() == s.to_lowercase() {
            results.push(JsValue::DomElement(Rc::clone(node)));
        }
        for child in &node.borrow().children {
            Self::query_all(child, s, results);
        }
    }

    /// Append child to element
    pub fn append_child(&self, parent: &Rc<RefCell<DomNode>>, child: Rc<RefCell<DomNode>>) {
        child.borrow_mut().parent = Some(Rc::clone(parent));
        parent.borrow_mut().children.push(child);
    }

    /// Remove child from element
    pub fn remove_child(&self, parent: &Rc<RefCell<DomNode>>, child: &Rc<RefCell<DomNode>>) {
        let child_id = child.borrow().id;
        parent.borrow_mut().children.retain(|c| c.borrow().id != child_id);
    }

    /// Get property from element
    pub fn get_property(&self, tag: &str, property: &str) -> JsValue {
        match property {
            "tagName" | "nodeName" => JsValue::String(tag.to_uppercase()),
            "nodeType" => JsValue::Number(1.0),
            "innerHTML" => JsValue::String(String::new()),
            "textContent" => JsValue::String(String::new()),
            "style" => JsValue::Object(Rc::new(RefCell::new(HashMap::new()))),
            "children" => JsValue::Array(Rc::new(RefCell::new(Vec::new()))),
            "parentNode" | "parentElement" => JsValue::Null,
            "firstChild" | "lastChild" | "nextSibling" | "previousSibling" => JsValue::Null,
            "id" => JsValue::String(String::new()),
            "className" => JsValue::String(String::new()),
            _ => JsValue::Undefined,
        }
    }

    /// Set property on element
    pub fn set_property(&self, _tag: &str, property: &str, value: JsValue) {
        // Would store in a property map
        let _ = (property, value);
    }
}
'''
        (self.output_dir / "dom.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'dom.rs'}")

    def generate_console(self):
        content = r'''//! Console - Logging API
//! Generated by Python

use std::cell::RefCell;
use std::sync::Mutex;
use super::value::JsValue;

#[derive(Debug, Clone)]
pub struct LogEntry {
    pub level: LogLevel,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum LogLevel {
    Log,
    Info,
    Warn,
    Error,
    Debug,
}

pub struct Console {
    pub logs: RefCell<Vec<LogEntry>>,
}

impl Console {
    pub fn new() -> Self {
        Self { logs: RefCell::new(Vec::new()) }
    }

    pub fn log(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Log, message: msg });
        tracing::info!("[console.log] {}", self.logs.borrow().last().map(|l| l.message.clone()).unwrap_or_default());
    }

    pub fn info(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Info, message: msg });
    }

    pub fn warn(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Warn, message: msg.clone() });
        tracing::warn!("[console.warn] {}", msg);
    }

    pub fn error(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Error, message: msg.clone() });
        tracing::error!("[console.error] {}", msg);
    }

    pub fn debug(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Debug, message: msg });
    }

    pub fn clear(&self) {
        self.logs.borrow_mut().clear();
    }
}

// Native functions for console
pub fn console_log(args: &[JsValue]) -> Result<JsValue, String> {
    let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
    tracing::info!("[console.log] {}", msg);
    Ok(JsValue::Undefined)
}
pub fn console_warn(args: &[JsValue]) -> Result<JsValue, String> {
    let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
    tracing::warn!("[console.warn] {}", msg);
    Ok(JsValue::Undefined)
}
pub fn console_error(args: &[JsValue]) -> Result<JsValue, String> {
    let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
    tracing::error!("[console.error] {}", msg);
    Ok(JsValue::Undefined)
}
pub fn console_info(args: &[JsValue]) -> Result<JsValue, String> {
    console_log(args)
}
'''
        (self.output_dir / "console.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'console.rs'}")

    def generate_timer(self):
        content = r'''//! Timer - setTimeout, setInterval
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use std::time::{Duration, Instant};
use super::value::JsValue;

pub struct Timer {
    pub id: u64,
    pub callback: JsValue,
    pub delay_ms: u64,
    pub created_at: Instant,
    pub is_interval: bool,
    pub fired: bool,
}

pub struct TimerQueue {
    pub timers: RefCell<HashMap<u64, Timer>>,
    pub next_id: RefCell<u64>,
}

impl TimerQueue {
    pub fn new() -> Self {
        Self {
            timers: RefCell::new(HashMap::new()),
            next_id: RefCell::new(1),
        }
    }

    pub fn set_timeout(&self, callback: JsValue, delay_ms: u64) -> u64 {
        let id = *self.next_id.borrow();
        *self.next_id.borrow_mut() += 1;
        let timer = Timer {
            id,
            callback,
            delay_ms,
            created_at: Instant::now(),
            is_interval: false,
            fired: false,
        };
        self.timers.borrow_mut().insert(id, timer);
        id
    }

    pub fn set_interval(&self, callback: JsValue, delay_ms: u64) -> u64 {
        let id = *self.next_id.borrow();
        *self.next_id.borrow_mut() += 1;
        let timer = Timer {
            id,
            callback,
            delay_ms,
            created_at: Instant::now(),
            is_interval: true,
            fired: false,
        };
        self.timers.borrow_mut().insert(id, timer);
        id
    }

    pub fn clear(&self, id: u64) {
        self.timers.borrow_mut().remove(&id);
    }

    /// Get all expired timers
    pub fn get_expired(&self) -> Vec<u64> {
        let now = Instant::now();
        self.timers.borrow()
            .iter()
            .filter(|(_, t)| {
                now.duration_since(t.created_at).as_millis() >= t.delay_ms as u128
            })
            .map(|(id, _)| *id)
            .collect()
    }
}

// Native function wrappers
pub fn js_set_timeout(args: &[JsValue]) -> Result<JsValue, String> {
    if args.len() < 2 {
        return Err("setTimeout needs callback and delay".to_string());
    }
    let delay = args[1].to_number() as u64;
    // Would need to access TimerQueue - in practice, interpreter handles this
    Ok(JsValue::Number(0.0))
}

pub fn js_set_interval(args: &[JsValue]) -> Result<JsValue, String> {
    if args.len() < 2 {
        return Err("setInterval needs callback and delay".to_string());
    }
    Ok(JsValue::Number(0.0))
}

pub fn js_clear_timeout(args: &[JsValue]) -> Result<JsValue, String> {
    Ok(JsValue::Undefined)
}
'''
        (self.output_dir / "timer.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'timer.rs'}")

    def generate_fetch(self):
        content = r'''//! Fetch - Network API
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use std::sync::{Arc, Mutex};
use super::value::JsValue;

#[derive(Debug, Clone)]
pub struct FetchRequest {
    pub url: String,
    pub method: String,
    pub headers: HashMap<String, String>,
    pub body: Option<String>,
}

#[derive(Debug, Clone)]
pub struct FetchResponse {
    pub url: String,
    pub status: u16,
    pub ok: bool,
    pub body: String,
    pub headers: HashMap<String, String>,
}

pub struct FetchQueue {
    pub pending: RefCell<Vec<FetchRequest>>,
    pub responses: RefCell<Vec<FetchResponse>>,
}

impl FetchQueue {
    pub fn new() -> Self {
        Self {
            pending: RefCell::new(Vec::new()),
            responses: RefCell::new(Vec::new()),
        }
    }

    pub fn enqueue(&self, request: FetchRequest) {
        self.pending.borrow_mut().push(request);
    }

    pub fn take_responses(&self) -> Vec<FetchResponse> {
        std::mem::take(&mut *self.responses.borrow_mut())
    }
}

pub fn js_fetch(args: &[JsValue]) -> Result<JsValue, String> {
    if args.is_empty() {
        return Err("fetch needs URL".to_string());
    }
    let url = args[0].to_string();
    tracing::info!("[fetch] {}", url);
    // Would return a Promise
    Ok(JsValue::Object(Rc::new(RefCell::new(HashMap::new()))))
}
'''
        (self.output_dir / "fetch.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'fetch.rs'}")

    def generate_builtins(self):
        content = r'''//! Built-in objects: Math, JSON, console, document, window
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use super::value::JsValue;
use super::env::Env;
use super::dom::Dom;
use super::console::Console;
use super::console::{console_log, console_warn, console_error, console_info};

pub fn register_builtins(env: &Rc<RefCell<Env>>, dom: &Rc<RefCell<Dom>>, _console: &Rc<RefCell<Console>>) {
    let mut global = env.borrow_mut();

    // console
    let mut console_obj = HashMap::new();
    console_obj.insert("log".to_string(), JsValue::NativeFunction { name: "log".to_string(), func: console_log });
    console_obj.insert("info".to_string(), JsValue::NativeFunction { name: "info".to_string(), func: console_info });
    console_obj.insert("warn".to_string(), JsValue::NativeFunction { name: "warn".to_string(), func: console_warn });
    console_obj.insert("error".to_string(), JsValue::NativeFunction { name: "error".to_string(), func: console_error });
    global.set("console".to_string(), JsValue::Object(Rc::new(RefCell::new(console_obj))));

    // Math
    let mut math_obj = HashMap::new();
    math_obj.insert("PI".to_string(), JsValue::Number(std::f64::consts::PI));
    math_obj.insert("E".to_string(), JsValue::Number(std::f64::consts::E));
    math_obj.insert("sqrt".to_string(), JsValue::NativeFunction { name: "sqrt".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NAN)); }
        Ok(JsValue::Number(args[0].to_number().sqrt()))
    }});
    math_obj.insert("pow".to_string(), JsValue::NativeFunction { name: "pow".to_string(), func: |args: &[JsValue]| {
        if args.len() < 2 { return Ok(JsValue::Number(f64::NAN)); }
        Ok(JsValue::Number(args[0].to_number().powf(args[1].to_number())))
    }});
    math_obj.insert("abs".to_string(), JsValue::NativeFunction { name: "abs".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NAN)); }
        Ok(JsValue::Number(args[0].to_number().abs()))
    }});
    math_obj.insert("floor".to_string(), JsValue::NativeFunction { name: "floor".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NAN)); }
        Ok(JsValue::Number(args[0].to_number().floor()))
    }});
    math_obj.insert("ceil".to_string(), JsValue::NativeFunction { name: "ceil".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NAN)); }
        Ok(JsValue::Number(args[0].to_number().ceil()))
    }});
    math_obj.insert("round".to_string(), JsValue::NativeFunction { name: "round".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NAN)); }
        Ok(JsValue::Number(args[0].to_number().round()))
    }});
    math_obj.insert("max".to_string(), JsValue::NativeFunction { name: "max".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NEG_INFINITY)); }
        Ok(JsValue::Number(args.iter().map(|a| a.to_number()).fold(f64::NEG_INFINITY, f64::max)))
    }});
    math_obj.insert("min".to_string(), JsValue::NativeFunction { name: "min".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::INFINITY)); }
        Ok(JsValue::Number(args.iter().map(|a| a.to_number()).fold(f64::INFINITY, f64::min)))
    }});
    math_obj.insert("random".to_string(), JsValue::NativeFunction { name: "random".to_string(), func: |_args: &[JsValue]| {
        use std::time::SystemTime;
        let nanos = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH).unwrap().as_nanos();
        Ok(JsValue::Number((nanos % 1000) as f64 / 1000.0))
    }});
    global.set("Math".to_string(), JsValue::Object(Rc::new(RefCell::new(math_obj))));

    // JSON
    let json_obj: HashMap<String, JsValue> = vec![
        ("stringify", JsValue::NativeFunction { name: "stringify".to_string(), func: |args: &[JsValue]| {
            if args.is_empty() { return Ok(JsValue::String("undefined".to_string())); }
            Ok(JsValue::String(args[0].to_string()))
        }}),
        ("parse", JsValue::NativeFunction { name: "parse".to_string(), func: |args: &[JsValue]| {
            // Simplified - no real JSON parsing
            if args.is_empty() { return Ok(JsValue::Null); }
            Ok(JsValue::String(args[0].to_string()))
        }}),
    ].into_iter().map(|(k, v)| (k.to_string(), v)).collect();
    global.set("JSON".to_string(), JsValue::Object(Rc::new(RefCell::new(json_obj))));

    // document
    let mut doc_obj = HashMap::new();
    doc_obj.insert("title".to_string(), JsValue::String("Noir Browser".to_string()));
    doc_obj.insert("body".to_string(), JsValue::Object(Rc::new(RefCell::new(HashMap::new()))));
    doc_obj.insert("getElementById".to_string(), JsValue::NativeFunction { name: "getElementById".to_string(), func: |args: &[JsValue]| {
        // Would access dom
        if args.is_empty() { return Ok(JsValue::Null); }
        Ok(JsValue::Null)
    }});
    doc_obj.insert("querySelector".to_string(), JsValue::NativeFunction { name: "querySelector".to_string(), func: |_args: &[JsValue]| {
        Ok(JsValue::Null)
    }});
    doc_obj.insert("querySelectorAll".to_string(), JsValue::NativeFunction { name: "querySelectorAll".to_string(), func: |_args: &[JsValue]| {
        Ok(JsValue::Array(Rc::new(RefCell::new(Vec::new()))))
    }});
    doc_obj.insert("createElement".to_string(), JsValue::NativeFunction { name: "createElement".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Null); }
        Ok(Dom::create_element(&args[0].to_string()))
    }});
    global.set("document".to_string(), JsValue::Object(Rc::new(RefCell::new(doc_obj))));

    // window
    let mut win_obj = HashMap::new();
    win_obj.insert("innerWidth".to_string(), JsValue::Number(1280.0));
    win_obj.insert("innerHeight".to_string(), JsValue::Number(720.0));
    win_obj.insert("location".to_string(), JsValue::Object(Rc::new(RefCell::new({
        let mut loc = HashMap::new();
        loc.insert("href".to_string(), JsValue::String(String::new()));
        loc
    }))));
    win_obj.insert("alert".to_string(), JsValue::NativeFunction { name: "alert".to_string(), func: |args: &[JsValue]| {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        tracing::info!("[alert] {}", msg);
        Ok(JsValue::Undefined)
    }});
    win_obj.insert("setTimeout".to_string(), JsValue::NativeFunction { name: "setTimeout".to_string(), func: |_args: &[JsValue]| {
        Ok(JsValue::Number(0.0))
    }});
    win_obj.insert("setInterval".to_string(), JsValue::NativeFunction { name: "setInterval".to_string(), func: |_args: &[JsValue]| {
        Ok(JsValue::Number(0.0))
    }});
    global.set("window".to_string(), JsValue::Object(Rc::new(RefCell::new(win_obj))));

    // parseInt, parseFloat
    global.set("parseInt".to_string(), JsValue::NativeFunction { name: "parseInt".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NAN)); }
        let s = args[0].to_string();
        let radix = if args.len() > 1 { args[1].to_number() as u32 } else { 10 };
        Ok(JsValue::Number(s.parse::<i64>().map(|n| n as f64).unwrap_or(f64::NAN)))
    }});
    global.set("parseFloat".to_string(), JsValue::NativeFunction { name: "parseFloat".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Number(f64::NAN)); }
        Ok(JsValue::Number(args[0].to_string().parse::<f64>().unwrap_or(f64::NAN)))
    }});

    // isNaN, isFinite
    global.set("isNaN".to_string(), JsValue::NativeFunction { name: "isNaN".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Boolean(false)); }
        Ok(JsValue::Boolean(args[0].to_number().is_nan()))
    }});
    global.set("isFinite".to_string(), JsValue::NativeFunction { name: "isFinite".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::Boolean(false)); }
        Ok(JsValue::Boolean(args[0].to_number().is_finite()))
    }});

    // Global NaN, Infinity, undefined
    global.set("NaN".to_string(), JsValue::Number(f64::NAN));
    global.set("Infinity".to_string(), JsValue::Number(f64::INFINITY));
    global.set("undefined".to_string(), JsValue::Undefined);

    // Encode/decode
    global.set("encodeURIComponent".to_string(), JsValue::NativeFunction { name: "encodeURIComponent".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::String(String::new())); }
        let s = args[0].to_string();
        let mut result = String::new();
        for c in s.chars() {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | '~') {
                result.push(c);
            } else {
                for b in c.to_string().as_bytes() {
                    result.push_str(&format!("%{:02X}", b));
                }
            }
        }
        Ok(JsValue::String(result))
    }});
    global.set("decodeURIComponent".to_string(), JsValue::NativeFunction { name: "decodeURIComponent".to_string(), func: |args: &[JsValue]| {
        if args.is_empty() { return Ok(JsValue::String(String::new())); }
        // Simplified - just return as-is
        Ok(JsValue::String(args[0].to_string()))
    }});

    let _ = dom; // Suppress unused warning
}
'''
        (self.output_dir / "builtins.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'builtins.rs'}")


if __name__ == "__main__":
    print("=" * 60)
    print("  Noir Browser - JS Engine v3 Generator")
    print("  Full DOM support + ES2024 features")
    print("=" * 60)
    print()
    gen = JSEngineV3Generator()
    gen.generate_all()
