#!/usr/bin/env python3
"""
Generador MEJORADO de JS Engine para Noir Browser
Usa r''' ''' (raw strings) para evitar problemas de escape.
"""

from pathlib import Path
import shutil

class JSEngineGeneratorV2:
    def __init__(self, output_dir: str = "src/js_engine_v2"):
        self.output_dir = Path(output_dir)
        if self.output_dir.exists():
            shutil.rmtree(self.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_all(self):
        """Genera todos los archivos del JS engine"""
        self.generate_lexer()
        self.generate_ast()
        self.generate_parser()
        self.generate_interpreter()
        self.generate_mod()
        print("JS Engine v2 generated successfully!")

    def generate_mod(self):
        """Genera mod.rs"""
        content = '''//! JS Engine v2 - Minimal ES2024 subset
//! Generated by Python - do not edit manually

pub mod ast;
pub mod interpreter;
pub mod lexer;
pub mod parser;
'''
        (self.output_dir / "mod.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'mod.rs'}")

    def generate_lexer(self):
        """Genera el lexer usando r-strings para evitar escapes"""
        content = r'''//! Auto-generated JS Lexer
//! Generated by Python - do not edit manually

use std::iter::Peekable;
use std::str::Chars;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    KwLet,
    KwConst,
    KwVar,
    KwFunction,
    KwReturn,
    KwIf,
    KwElse,
    KwWhile,
    KwFor,
    KwClass,
    KwNew,
    KwThis,
    KwTrue,
    KwFalse,
    KwNull,
    KwUndefined,
    OpAdd,
    OpSub,
    OpMul,
    OpDiv,
    OpMod,
    OpAssign,
    OpEq,
    OpStrictEq,
    OpNotEq,
    OpStrictNotEq,
    OpLt,
    OpGt,
    OpLtEq,
    OpGtEq,
    OpAnd,
    OpOr,
    OpNot,
    PunctLParen,
    PunctRParen,
    PunctLBrace,
    PunctRBrace,
    PunctLBracket,
    PunctRBracket,
    PunctSemi,
    PunctComma,
    PunctDot,
    PunctColon,
    PunctQuestion,
    Number,
    String,
    Identifier,
    Whitespace,
    Comment,
    Eof,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub value: String,
    pub line: u32,
    pub col: u32,
}

pub struct Lexer<'a> {
    input: Peekable<Chars<'a>>,
    line: u32,
    col: u32,
}

impl<'a> Lexer<'a> {
    pub fn new(input: &'a str) -> Self {
        Self {
            input: input.chars().peekable(),
            line: 1,
            col: 1,
        }
    }

    pub fn tokenize(&mut self) -> Vec<Token> {
        let mut tokens = Vec::new();
        while let Some(token) = self.next_token() {
            let is_ws = matches!(token.kind, TokenKind::Whitespace | TokenKind::Comment);
            if !is_ws {
                tokens.push(token.clone());
            }
            if matches!(token.kind, TokenKind::Eof) {
                break;
            }
        }
        tokens
    }

    fn next_token(&mut self) -> Option<Token> {
        let ch = *self.input.peek()?;

        if ch.is_whitespace() {
            return Some(self.read_whitespace());
        }

        if ch == '/' {
            return Some(self.read_comment_or_div());
        }

        if ch.is_ascii_digit() {
            return Some(self.read_number());
        }

        if ch == '"' || ch == '\'' {
            return Some(self.read_string());
        }

        if ch.is_alphabetic() || ch == '_' || ch == '$' {
            return Some(self.read_identifier());
        }

        Some(self.read_operator())
    }

    fn read_whitespace(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_whitespace() {
                if ch == '\n' {
                    self.line += 1;
                    self.col = 1;
                } else {
                    self.col += 1;
                }
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }
        Token { kind: TokenKind::Whitespace, value, line, col }
    }

    fn read_comment_or_div(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        value.push(self.input.next().unwrap());

        if self.input.peek() == Some(&'/') {
            value.push(self.input.next().unwrap());
            while let Some(&ch) = self.input.peek() {
                if ch == '\n' { break; }
                value.push(self.input.next().unwrap());
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else if self.input.peek() == Some(&'*') {
            value.push(self.input.next().unwrap());
            while let Some(ch) = self.input.next() {
                value.push(ch);
                if ch == '*' && self.input.peek() == Some(&'/') {
                    value.push(self.input.next().unwrap());
                    break;
                }
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else {
            Token { kind: TokenKind::OpDiv, value: "/".to_string(), line, col }
        }
    }

    fn read_number(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_ascii_digit() || ch == '.' {
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }
        Token { kind: TokenKind::Number, value, line, col }
    }

    fn read_string(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let quote = self.input.next().unwrap();
        let mut value = String::new();
        value.push(quote);
        while let Some(ch) = self.input.next() {
            value.push(ch);
            if ch == quote {
                break;
            }
            if ch == '\\' {
                if let Some(escaped) = self.input.next() {
                    value.push(escaped);
                }
            }
        }
        Token { kind: TokenKind::String, value, line, col }
    }

    fn read_identifier(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_alphanumeric() || ch == '_' || ch == '$' {
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }

        let kind = match value.as_str() {
            "let" => TokenKind::KwLet,
            "const" => TokenKind::KwConst,
            "var" => TokenKind::KwVar,
            "function" => TokenKind::KwFunction,
            "return" => TokenKind::KwReturn,
            "if" => TokenKind::KwIf,
            "else" => TokenKind::KwElse,
            "while" => TokenKind::KwWhile,
            "for" => TokenKind::KwFor,
            "class" => TokenKind::KwClass,
            "new" => TokenKind::KwNew,
            "this" => TokenKind::KwThis,
            "true" => TokenKind::KwTrue,
            "false" => TokenKind::KwFalse,
            "null" => TokenKind::KwNull,
            "undefined" => TokenKind::KwUndefined,
            _ => TokenKind::Identifier,
        };

        Token { kind, value, line, col }
    }

    fn read_operator(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let ch = self.input.next().unwrap();
        let mut value = ch.to_string();

        let (kind, _): (TokenKind, ()) = match value.as_str() {
            "+" => (TokenKind::OpAdd, ()),
            "-" => (TokenKind::OpSub, ()),
            "*" => (TokenKind::OpMul, ()),
            "/" => (TokenKind::OpDiv, ()),
            "%" => (TokenKind::OpMod, ()),
            "=" => (TokenKind::OpAssign, ()),
            "(" => (TokenKind::PunctLParen, ()),
            ")" => (TokenKind::PunctRParen, ()),
            "{" => (TokenKind::PunctLBrace, ()),
            "}" => (TokenKind::PunctRBrace, ()),
            "[" => (TokenKind::PunctLBracket, ()),
            "]" => (TokenKind::PunctRBracket, ()),
            ";" => (TokenKind::PunctSemi, ()),
            "," => (TokenKind::PunctComma, ()),
            "." => (TokenKind::PunctDot, ()),
            ":" => (TokenKind::PunctColon, ()),
            "?" => (TokenKind::PunctQuestion, ()),
            _ => (TokenKind::Eof, ()),
        };

        Token { kind, value, line, col }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tokenize_let() {
        let mut lexer = Lexer::new("let x = 42;");
        let tokens = lexer.tokenize();
        assert!(tokens.len() >= 5);
        assert!(matches!(tokens[0].kind, TokenKind::KwLet));
    }

    #[test]
    fn test_tokenize_function() {
        let mut lexer = Lexer::new("function foo() { return 1; }");
        let tokens = lexer.tokenize();
        assert!(tokens.len() > 5);
    }

    #[test]
    fn test_tokenize_arithmetic() {
        let mut lexer = Lexer::new("a + b * c");
        let tokens = lexer.tokenize();
        assert!(tokens.len() >= 5);
    }
}
'''
        (self.output_dir / "lexer.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'lexer.rs'}")

    def generate_ast(self):
        """Genera el AST"""
        content = r'''//! Auto-generated JS AST
//! Generated by Python - do not edit manually

use std::boxed::Box;

#[derive(Debug, Clone)]
pub enum Expr {
    Number(f64),
    String(String),
    Bool(bool),
    Null,
    Undefined,
    Identifier(String),
    Binary {
        op: BinaryOp,
        left: Box<Expr>,
        right: Box<Expr>,
    },
    Unary {
        op: UnaryOp,
        operand: Box<Expr>,
    },
    Call {
        callee: Box<Expr>,
        args: Vec<Expr>,
    },
    Member {
        object: Box<Expr>,
        property: String,
    },
    Array(Vec<Expr>),
    Assign {
        target: Box<Expr>,
        value: Box<Expr>,
    },
    This,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BinaryOp {
    Add, Sub, Mul, Div, Mod,
    Eq, StrictEq, Ne, StrictNe,
    Lt, Gt, LtEq, GtEq,
    And, Or,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum UnaryOp {
    Neg, Not,
}

#[derive(Debug, Clone)]
pub enum Stmt {
    VarDecl {
        name: String,
        value: Option<Expr>,
    },
    Expr(Expr),
    If {
        condition: Expr,
        then_branch: Vec<Stmt>,
        else_branch: Option<Vec<Stmt>>,
    },
    While {
        condition: Expr,
        body: Vec<Stmt>,
    },
    Return(Option<Expr>),
    Block(Vec<Stmt>),
}

#[derive(Debug, Clone)]
pub struct Program {
    pub body: Vec<Stmt>,
}
'''
        (self.output_dir / "ast.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'ast.rs'}")

    def generate_parser(self):
        """Genera el parser"""
        content = r'''//! Auto-generated JS Parser
//! Generated by Python - do not edit manually

use super::ast::*;
use super::lexer::*;

pub struct Parser {
    tokens: Vec<Token>,
    pos: usize,
}

impl Parser {
    pub fn new(tokens: Vec<Token>) -> Self {
        Self { tokens, pos: 0 }
    }

    pub fn parse(&mut self) -> Result<Program, String> {
        let mut body = Vec::new();
        while !self.is_eof() {
            body.push(self.parse_stmt()?);
        }
        Ok(Program { body })
    }

    fn parse_stmt(&mut self) -> Result<Stmt, String> {
        let token = self.peek().clone();

        match token.kind {
            TokenKind::KwLet | TokenKind::KwConst | TokenKind::KwVar => {
                self.parse_var_decl()
            }
            TokenKind::KwReturn => {
                self.advance();
                let expr = if !self.is_eof() {
                    Some(self.parse_expr()?)
                } else {
                    None
                };
                Ok(Stmt::Return(expr))
            }
            TokenKind::KwIf => self.parse_if(),
            TokenKind::KwWhile => self.parse_while(),
            _ => {
                let expr = self.parse_expr()?;
                Ok(Stmt::Expr(expr))
            }
        }
    }

    fn parse_var_decl(&mut self) -> Result<Stmt, String> {
        self.advance();
        let name = self.expect_identifier()?;
        let value = if matches!(self.peek().kind, TokenKind::OpAssign) {
            self.advance();
            Some(self.parse_expr()?)
        } else {
            None
        };
        Ok(Stmt::VarDecl { name, value })
    }

    fn parse_if(&mut self) -> Result<Stmt, String> {
        self.advance();
        let condition = self.parse_expr()?;
        let then_branch = self.parse_block()?;
        let else_branch = if matches!(self.peek().kind, TokenKind::KwElse) {
            self.advance();
            Some(self.parse_block()?)
        } else {
            None
        };
        Ok(Stmt::If { condition, then_branch, else_branch })
    }

    fn parse_while(&mut self) -> Result<Stmt, String> {
        self.advance();
        let condition = self.parse_expr()?;
        let body = self.parse_block()?;
        Ok(Stmt::While { condition, body })
    }

    fn parse_block(&mut self) -> Result<Vec<Stmt>, String> {
        if !matches!(self.peek().kind, TokenKind::PunctLBrace) {
            return Err("Expected block".to_string());
        }
        self.advance();
        let mut stmts = Vec::new();
        while !matches!(self.peek().kind, TokenKind::PunctRBrace) && !self.is_eof() {
            stmts.push(self.parse_stmt()?);
        }
        self.advance();
        Ok(stmts)
    }

    fn parse_expr(&mut self) -> Result<Expr, String> {
        self.parse_additive()
    }

    fn parse_additive(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_multiplicative()?;
        while matches!(self.peek().kind, TokenKind::OpAdd | TokenKind::OpSub) {
            let op = match self.peek().kind {
                TokenKind::OpAdd => BinaryOp::Add,
                _ => BinaryOp::Sub,
            };
            self.advance();
            let right = self.parse_multiplicative()?;
            left = Expr::Binary {
                op,
                left: Box::new(left),
                right: Box::new(right),
            };
        }
        Ok(left)
    }

    fn parse_multiplicative(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_unary()?;
        while matches!(self.peek().kind,
            TokenKind::OpMul | TokenKind::OpDiv | TokenKind::OpMod) {
            let op = match self.peek().kind {
                TokenKind::OpMul => BinaryOp::Mul,
                TokenKind::OpDiv => BinaryOp::Div,
                _ => BinaryOp::Mod,
            };
            self.advance();
            let right = self.parse_unary()?;
            left = Expr::Binary {
                op,
                left: Box::new(left),
                right: Box::new(right),
            };
        }
        Ok(left)
    }

    fn parse_unary(&mut self) -> Result<Expr, String> {
        if matches!(self.peek().kind, TokenKind::OpSub) {
            self.advance();
            let operand = self.parse_unary()?;
            return Ok(Expr::Unary { op: UnaryOp::Neg, operand: Box::new(operand) });
        }
        if matches!(self.peek().kind, TokenKind::OpNot) {
            self.advance();
            let operand = self.parse_unary()?;
            return Ok(Expr::Unary { op: UnaryOp::Not, operand: Box::new(operand) });
        }
        self.parse_call()
    }

    fn parse_call(&mut self) -> Result<Expr, String> {
        let mut expr = self.parse_primary()?;
        loop {
            if matches!(self.peek().kind, TokenKind::PunctLParen) {
                self.advance();
                let mut args = Vec::new();
                while !matches!(self.peek().kind, TokenKind::PunctRParen) {
                    args.push(self.parse_expr()?);
                    if matches!(self.peek().kind, TokenKind::PunctComma) {
                        self.advance();
                    } else {
                        break;
                    }
                }
                self.advance();
                expr = Expr::Call { callee: Box::new(expr), args };
            } else {
                break;
            }
        }
        Ok(expr)
    }

    fn parse_primary(&mut self) -> Result<Expr, String> {
        let token = self.peek().clone();
        match token.kind {
            TokenKind::Number => {
                self.advance();
                let n: f64 = token.value.parse().map_err(|_| "Invalid number".to_string())?;
                Ok(Expr::Number(n))
            }
            TokenKind::String => {
                self.advance();
                Ok(Expr::String(token.value))
            }
            TokenKind::KwTrue => { self.advance(); Ok(Expr::Bool(true)) }
            TokenKind::KwFalse => { self.advance(); Ok(Expr::Bool(false)) }
            TokenKind::KwNull => { self.advance(); Ok(Expr::Null) }
            TokenKind::KwUndefined => { self.advance(); Ok(Expr::Undefined) }
            TokenKind::KwThis => { self.advance(); Ok(Expr::This) }
            TokenKind::Identifier => {
                self.advance();
                Ok(Expr::Identifier(token.value))
            }
            _ => Err(format!("Unexpected token: {:?}", token.kind)),
        }
    }

    fn peek(&self) -> &Token {
        &self.tokens[self.pos]
    }

    fn advance(&mut self) {
        if self.pos < self.tokens.len().saturating_sub(1) {
            self.pos += 1;
        }
    }

    fn is_eof(&self) -> bool {
        self.pos >= self.tokens.len() || matches!(self.peek().kind, TokenKind::Eof)
    }

    fn expect_identifier(&mut self) -> Result<String, String> {
        let token = self.peek().clone();
        if matches!(token.kind, TokenKind::Identifier) {
            self.advance();
            Ok(token.value)
        } else {
            Err(format!("Expected identifier, got {:?}", token.kind))
        }
    }
}
'''
        (self.output_dir / "parser.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'parser.rs'}")

    def generate_interpreter(self):
        """Genera el interpreter"""
        content = r'''//! Auto-generated JS Interpreter
//! Generated by Python - do not edit manually

use std::collections::HashMap;
use std::rc::Rc;
use std::cell::RefCell;
use super::ast::*;

#[derive(Debug, Clone)]
pub enum Value {
    Number(f64),
    String(String),
    Bool(bool),
    Null,
    Undefined,
    Object(Rc<RefCell<HashMap<String, Value>>>),
}

impl PartialEq for Value {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Value::Number(a), Value::Number(b)) => a == b,
            (Value::String(a), Value::String(b)) => a == b,
            (Value::Bool(a), Value::Bool(b)) => a == b,
            (Value::Null, Value::Null) => true,
            (Value::Undefined, Value::Undefined) => true,
            _ => false,
        }
    }
}

pub struct Env {
    variables: HashMap<String, Value>,
}

impl Env {
    pub fn new() -> Self {
        Self { variables: HashMap::new() }
    }

    pub fn get(&self, name: &str) -> Option<Value> {
        self.variables.get(name).cloned()
    }

    pub fn set(&mut self, name: String, value: Value) {
        self.variables.insert(name, value);
    }
}

pub struct Interpreter {
    env: Env,
}

impl Interpreter {
    pub fn new() -> Self {
        Self { env: Env::new() }
    }

    pub fn interpret(&mut self, program: &Program) -> Result<Value, String> {
        let mut result = Value::Undefined;
        for stmt in &program.body {
            self.exec_stmt(stmt)?;
        }
        Ok(result)
    }

    fn exec_stmt(&mut self, stmt: &Stmt) -> Result<Value, String> {
        match stmt {
            Stmt::VarDecl { name, value } => {
                let v = if let Some(expr) = value {
                    self.eval_expr(expr)?
                } else {
                    Value::Undefined
                };
                self.env.set(name.clone(), v);
                Ok(Value::Undefined)
            }
            Stmt::Expr(expr) => self.eval_expr(expr),
            Stmt::Return(expr) => {
                let v = if let Some(e) = expr {
                    Some(self.eval_expr(e)?)
                } else {
                    None
                };
                Err(format!("RETURN:{:?}", v))
            }
            _ => Ok(Value::Undefined),
        }
    }

    fn eval_expr(&mut self, expr: &Expr) -> Result<Value, String> {
        match expr {
            Expr::Number(n) => Ok(Value::Number(*n)),
            Expr::String(s) => Ok(Value::String(s.clone())),
            Expr::Bool(b) => Ok(Value::Bool(*b)),
            Expr::Null => Ok(Value::Null),
            Expr::Undefined => Ok(Value::Undefined),
            Expr::Identifier(name) => {
                self.env.get(name)
                    .ok_or_else(|| format!("Undefined variable: {}", name))
            }
            Expr::Binary { op, left, right } => {
                let l = self.eval_expr(left)?;
                let r = self.eval_expr(right)?;
                self.eval_binary(*op, &l, &r)
            }
            _ => Ok(Value::Undefined),
        }
    }

    fn eval_binary(&self, op: BinaryOp, l: &Value, r: &Value) -> Result<Value, String> {
        match (l, r) {
            (Value::Number(a), Value::Number(b)) => {
                let result = match op {
                    BinaryOp::Add => a + b,
                    BinaryOp::Sub => a - b,
                    BinaryOp::Mul => a * b,
                    BinaryOp::Div => a / b,
                    BinaryOp::Mod => a % b,
                    _ => return Ok(Value::Bool(false)),
                };
                Ok(Value::Number(result))
            }
            _ => Ok(Value::Bool(false)),
        }
    }
}
'''
        (self.output_dir / "interpreter.rs").write_text(content)
        print(f"Generated: {self.output_dir / 'interpreter.rs'}")


if __name__ == "__main__":
    gen = JSEngineGeneratorV2()
    gen.generate_all()
