#!/usr/bin/env python3
"""
Generador de Tests para Noir Browser
Genera tests Rust automáticamente basados en fixtures JSON.
"""

import json
import os
from pathlib import Path
from typing import List, Dict, Any

class TestGenerator:
    def __init__(self, output_dir: str = "src/tests"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_parser_tests(self, fixtures: List[Dict[str, Any]]):
        """Genera tests para parsers HTML/CSS/JS"""
        output = """//! Auto-generated parser tests
//! Generated by Python script - do not edit manually

#![cfg(test)]

use crate::parsers::{{
    dom_tree::parse_html,
    page_document::PageDocument,
    css_simple::CssCascade,
    css_lexer::tokenize_css,
    js_lexer::tokenize_js,
}};

"""
        for i, fixture in enumerate(fixtures):
            test_name = f"test_parse_{fixture['name']}_{i}"
            test_type = fixture.get('type', 'html')
            input_data = fixture['input']
            expected = fixture.get('expected', {})

            output += f"""
#[test]
fn {test_name}() {{
    let input = r#"{input_data}"#;
"""

            if test_type == 'html':
                output += f"""    let nodes = parse_html(input);
    assert!(nodes.len() > 0, "Should parse HTML");
    let page = PageDocument::from_html("https://test.com", input);
    assert_eq!(page.title.as_str(), "{expected.get('title', '')}");
"""
            elif test_type == 'css':
                output += f"""    let tokens = tokenize_css(input);
    assert!(tokens.len() > 0, "Should tokenize CSS");
    let cascade = CssCascade::new();
    assert!(cascade.parse(input).is_ok());
"""
            elif test_type == 'js':
                output += f"""    let tokens = tokenize_js(input);
    assert!(tokens.len() > 0, "Should tokenize JS");
"""

            output += "}\n"

        output_path = self.output_dir / "parser_tests.rs"
        output_path.write_text(output)
        print(f"Generated: {output_path} ({len(fixtures)} tests)")

    def generate_layout_tests(self, fixtures: List[Dict[str, Any]]):
        """Genera tests para layout engine"""
        output = """//! Auto-generated layout tests
//! Generated by Python script - do not edit manually

#![cfg(test)]

use crate::parsers::layout::{{
    layout_page, total_content_height, hit_test_link,
    LayoutItem,
}};
use crate::parsers::page_document::PageDocument;

"""
        for i, fixture in enumerate(fixtures):
            html = fixture['html']
            viewport = fixture.get('viewport', 1280)
            min_blocks = fixture.get('min_blocks', 1)

            output += f"""
#[test]
fn test_layout_{i}() {{
    let html = r#"{html}"#;
    let page = PageDocument::from_html("https://test.com", html);
    let blocks = layout_page(&page, {viewport}.0);
    assert!(blocks.len() >= {min_blocks});
    let total_h = total_content_height(&blocks);
    assert!(total_h > 0.0);
}}
"""

        output_path = self.output_dir / "layout_tests.rs"
        output_path.write_text(output)
        print(f"Generated: {output_path} ({len(fixtures)} tests)")

    def generate_image_tests(self, fixtures: List[Dict[str, Any]]):
        """Genera tests para image format detection"""
        output = """//! Auto-generated image format tests
//! Generated by Python script - do not edit manually

#![cfg(test)]

use crate::media::image_support::{{
    detect_format, decode_image_bytes, ImageFormat,
}};

"""
        formats = {
            'png': b'\x89PNG\r\n\x1a\n',
            'jpeg': b'\xff\xd8\xff\xe0',
            'gif87': b'GIF87a',
            'gif89': b'GIF89a',
            'webp': b'RIFF\x00\x00\x00\x00WEBP',
            'bmp': b'BM',
        }

        for name, magic in formats.items():
            padded = magic + b'\x00' * 16
            expected_format = {
                'png': 'Png',
                'jpeg': 'Jpeg',
                'gif87': 'Gif',
                'gif89': 'Gif',
                'webp': 'WebP',
                'bmp': 'Bmp',
            }[name]

            output += f"""
#[test]
fn test_detect_{name}() {{
    let bytes: &[u8] = &{list(padded)};
    assert_eq!(detect_format(bytes), ImageFormat::{expected_format});
}}
"""

        output_path = self.output_dir / "image_tests.rs"
        output_path.write_text(output)
        print(f"Generated: {output_path} ({len(formats)} tests)")


def main():
    print("=" * 60)
    print("  Noir Browser - Test Generator")
    print("=" * 60)

    gen = TestGenerator()

    # HTML parser tests
    html_fixtures = [
        {
            'name': 'simple_page',
            'type': 'html',
            'input': '<html><head><title>Test</title></head><body><h1>Hello</h1></body></html>',
            'expected': {'title': 'Test'}
        },
        {
            'name': 'with_links',
            'type': 'html',
            'input': '<a href="https://example.com">Link</a>',
            'expected': {}
        },
        {
            'name': 'with_images',
            'type': 'html',
            'input': '<img src="test.png" alt="Test">',
            'expected': {}
        },
    ]

    # CSS tests
    css_fixtures = [
        {
            'name': 'simple_selector',
            'type': 'css',
            'input': 'body { color: red; }',
        },
        {
            'name': 'class_selector',
            'type': 'css',
            'input': '.container { width: 100%; }',
        },
    ]

    # JS tests
    js_fixtures = [
        {
            'name': 'simple_var',
            'type': 'js',
            'input': 'let x = 42;',
        },
        {
            'name': 'function',
            'type': 'js',
            'input': 'function foo() { return 1; }',
        },
    ]

    # Layout tests
    layout_fixtures = [
        {
            'html': '<h1>Title</h1><p>Paragraph 1</p><p>Paragraph 2</p>',
            'viewport': 1280,
            'min_blocks': 3,
        },
        {
            'html': '<div><span>Hello</span> <span>World</span></div>',
            'viewport': 800,
            'min_blocks': 2,
        },
    ]

    gen.generate_parser_tests(html_fixtures + css_fixtures + js_fixtures)
    gen.generate_layout_tests(layout_fixtures)
    gen.generate_image_tests([])

    print()
    print("All tests generated successfully!")
    print("Run: cargo test")


if __name__ == "__main__":
    main()
