import os

class VulkanPipelineGen:
    def __init__(self, output_dir="No-Chromium/src/vulkan_engine"):
        self.output_dir = output_dir

    def run(self):
        print("[*] Generando módulo pipeline_gen.rs con RenderPass y Pipeline Builders...")
        code = [
            "// AUTO-GENERATED VULKAN PIPELINE BUILDERS",
            "use ash::{vk, Device};",
            "use std::ffi::CString;",
            "",
            "pub struct PipelineManager {",
            "    pub render_pass: vk::RenderPass,",
            "    pub descriptor_set_layout: vk::DescriptorSetLayout,",
            "    pub pipeline_layout: vk::PipelineLayout,",
            "    pub graphics_pipeline: vk::Pipeline,",
            "}",
            "",
            "impl PipelineManager {",
            "    pub fn new(",
            "        device: &Device,",
            "        surface_format: vk::SurfaceFormatKHR,",
            "        extent: vk::Extent2D,",
            "        vertex_shader_module: vk::ShaderModule,",
            "        fragment_shader_module: vk::ShaderModule,",
            "    ) -> Self {",
            "        println!(\"[*] Generando Descriptor Set Layout para la textura...\");",
            "        let sampler_layout_binding = vk::DescriptorSetLayoutBinding::builder()",
            "            .binding(0)",
            "            .descriptor_type(vk::DescriptorType::COMBINED_IMAGE_SAMPLER)",
            "            .descriptor_count(1)",
            "            .stage_flags(vk::ShaderStageFlags::FRAGMENT)",
            "            .build();",
            "            ",
            "        let layout_info = vk::DescriptorSetLayoutCreateInfo::builder()",
            "            .bindings(std::slice::from_ref(&sampler_layout_binding));",
            "            ",
            "        let descriptor_set_layout = unsafe { device.create_descriptor_set_layout(&layout_info, None).unwrap() };",
            "",
            "        println!(\"[*] Creando Render Pass...\");",
            "        let color_attachment = vk::AttachmentDescription::builder()",
            "            .format(surface_format.format)",
            "            .samples(vk::SampleCountFlags::TYPE_1)",
            "            .load_op(vk::AttachmentLoadOp::CLEAR)",
            "            .store_op(vk::AttachmentStoreOp::STORE)",
            "            .stencil_load_op(vk::AttachmentLoadOp::DONT_CARE)",
            "            .stencil_store_op(vk::AttachmentStoreOp::DONT_CARE)",
            "            .initial_layout(vk::ImageLayout::UNDEFINED)",
            "            .final_layout(vk::ImageLayout::PRESENT_SRC_KHR);",
            "            ",
            "        let color_attachment_ref = vk::AttachmentReference::builder()",
            "            .attachment(0)",
            "            .layout(vk::ImageLayout::COLOR_ATTACHMENT_OPTIMAL);",
            "            ",
            "        let subpass = vk::SubpassDescription::builder()",
            "            .pipeline_bind_point(vk::PipelineBindPoint::GRAPHICS)",
            "            .color_attachments(std::slice::from_ref(&color_attachment_ref));",
            "            ",
            "        let dependency = vk::SubpassDependency::builder()",
            "            .src_subpass(vk::SUBPASS_EXTERNAL)",
            "            .dst_subpass(0)",
            "            .src_stage_mask(vk::PipelineStageFlags::COLOR_ATTACHMENT_OUTPUT)",
            "            .src_access_mask(vk::AccessFlags::empty())",
            "            .dst_stage_mask(vk::PipelineStageFlags::COLOR_ATTACHMENT_OUTPUT)",
            "            .dst_access_mask(vk::AccessFlags::COLOR_ATTACHMENT_WRITE);",
            "            ",
            "        let render_pass_info = vk::RenderPassCreateInfo::builder()",
            "            .attachments(std::slice::from_ref(&color_attachment))",
            "            .subpasses(std::slice::from_ref(&subpass))",
            "            .dependencies(std::slice::from_ref(&dependency));",
            "            ",
            "        let render_pass = unsafe { device.create_render_pass(&render_pass_info, None).unwrap() };",
            "",
            "        println!(\"[*] Compilando el Graphics Pipeline...\");",
            "        let main_function_name = CString::new(\"main\").unwrap();",
            "        ",
            "        let vert_shader_stage_info = vk::PipelineShaderStageCreateInfo::builder()",
            "            .stage(vk::ShaderStageFlags::VERTEX)",
            "            .module(vertex_shader_module)",
            "            .name(&main_function_name);",
            "            ",
            "        let frag_shader_stage_info = vk::PipelineShaderStageCreateInfo::builder()",
            "            .stage(vk::ShaderStageFlags::FRAGMENT)",
            "            .module(fragment_shader_module)",
            "            .name(&main_function_name);",
            "            ",
            "        let shader_stages = [vert_shader_stage_info.build(), frag_shader_stage_info.build()];",
            "",
            "        // Binding description (vec2 pos, vec2 uv)",
            "        let vertex_binding_description = vk::VertexInputBindingDescription::builder()",
            "            .binding(0)",
            "            .stride(16) // 4 floats * 4 bytes",
            "            .input_rate(vk::VertexInputRate::VERTEX)",
            "            .build();",
            "            ",
            "        let vertex_attribute_descriptions = [",
            "            vk::VertexInputAttributeDescription::builder()",
            "                .binding(0)",
            "                .location(0)",
            "                .format(vk::Format::R32G32_SFLOAT)",
            "                .offset(0)",
            "                .build(),",
            "            vk::VertexInputAttributeDescription::builder()",
            "                .binding(0)",
            "                .location(1)",
            "                .format(vk::Format::R32G32_SFLOAT)",
            "                .offset(8)",
            "                .build(),",
            "        ];",
            "",
            "        let vertex_input_info = vk::PipelineVertexInputStateCreateInfo::builder()",
            "            .vertex_binding_descriptions(std::slice::from_ref(&vertex_binding_description))",
            "            .vertex_attribute_descriptions(&vertex_attribute_descriptions);",
            "",
            "        let input_assembly = vk::PipelineInputAssemblyStateCreateInfo::builder()",
            "            .topology(vk::PrimitiveTopology::TRIANGLE_LIST)",
            "            .primitive_restart_enable(false);",
            "",
            "        let viewport = vk::Viewport::builder()",
            "            .x(0.0)",
            "            .y(0.0)",
            "            .width(extent.width as f32)",
            "            .height(extent.height as f32)",
            "            .min_depth(0.0)",
            "            .max_depth(1.0);",
            "            ",
            "        let scissor = vk::Rect2D::builder()",
            "            .offset(vk::Offset2D { x: 0, y: 0 })",
            "            .extent(extent);",
            "            ",
            "        let viewport_state = vk::PipelineViewportStateCreateInfo::builder()",
            "            .viewports(std::slice::from_ref(&viewport))",
            "            .scissors(std::slice::from_ref(&scissor));",
            "",
            "        let rasterizer = vk::PipelineRasterizationStateCreateInfo::builder()",
            "            .depth_clamp_enable(false)",
            "            .rasterizer_discard_enable(false)",
            "            .polygon_mode(vk::PolygonMode::FILL)",
            "            .line_width(1.0)",
            "            .cull_mode(vk::CullModeFlags::BACK)",
            "            .front_face(vk::FrontFace::CLOCKWISE)",
            "            .depth_bias_enable(false);",
            "",
            "        let multisampling = vk::PipelineMultisampleStateCreateInfo::builder()",
            "            .sample_shading_enable(false)",
            "            .rasterization_samples(vk::SampleCountFlags::TYPE_1);",
            "",
            "        // Alpha blending configuration for the text",
            "        let color_blend_attachment = vk::PipelineColorBlendAttachmentState::builder()",
            "            .color_write_mask(",
            "                vk::ColorComponentFlags::R",
            "                    | vk::ColorComponentFlags::G",
            "                    | vk::ColorComponentFlags::B",
            "                    | vk::ColorComponentFlags::A,",
            "            )",
            "            .blend_enable(true)",
            "            .src_color_blend_factor(vk::BlendFactor::SRC_ALPHA)",
            "            .dst_color_blend_factor(vk::BlendFactor::ONE_MINUS_SRC_ALPHA)",
            "            .color_blend_op(vk::BlendOp::ADD)",
            "            .src_alpha_blend_factor(vk::BlendFactor::ONE)",
            "            .dst_alpha_blend_factor(vk::BlendFactor::ZERO)",
            "            .alpha_blend_op(vk::BlendOp::ADD);",
            "",
            "        let color_blending = vk::PipelineColorBlendStateCreateInfo::builder()",
            "            .logic_op_enable(false)",
            "            .attachments(std::slice::from_ref(&color_blend_attachment));",
            "",
            "        let pipeline_layout_info = vk::PipelineLayoutCreateInfo::builder()",
            "            .set_layouts(std::slice::from_ref(&descriptor_set_layout));",
            "            ",
            "        let pipeline_layout = unsafe { device.create_pipeline_layout(&pipeline_layout_info, None).unwrap() };",
            "",
            "        let pipeline_info = vk::GraphicsPipelineCreateInfo::builder()",
            "            .stages(&shader_stages)",
            "            .vertex_input_state(&vertex_input_info)",
            "            .input_assembly_state(&input_assembly)",
            "            .viewport_state(&viewport_state)",
            "            .rasterization_state(&rasterizer)",
            "            .multisample_state(&multisampling)",
            "            .color_blend_state(&color_blending)",
            "            .layout(pipeline_layout)",
            "            .render_pass(render_pass)",
            "            .subpass(0);",
            "",
            "        let graphics_pipeline = unsafe {",
            "            device.create_graphics_pipelines(",
            "                vk::PipelineCache::null(),",
            "                std::slice::from_ref(&pipeline_info),",
            "                None,",
            "            ).expect(\"Failed to create Graphics Pipeline\")[0]",
            "        };",
            "",
            "        Self {",
            "            render_pass,",
            "            descriptor_set_layout,",
            "            pipeline_layout,",
            "            graphics_pipeline,",
            "        }",
            "    }",
            "}",
        ]
        with open(os.path.join(self.output_dir, "pipeline_gen.rs"), "w", encoding='utf-8') as f:
            f.write("\n".join(code))
        
        # update mod.rs
        mod_file = os.path.join(self.output_dir, "mod.rs")
        if os.path.exists(mod_file):
            with open(mod_file, "r") as f:
                content = f.read()
            if "pub mod pipeline_gen;" not in content:
                with open(mod_file, "a") as f:
                    f.write("\npub mod pipeline_gen;\n")

if __name__ == "__main__":
    VulkanPipelineGen().run()
