import re
import os

class MasterCodegen:
    """
    The Architect: Automates the creation of the entire No-Chromium engine.
    It processes IDLs, Torque, and Networking specs to generate Rust code.
    """
    def __init__(self, data_dir="extracted_data", output_dir="generated_rust"):
        self.data_dir = data_dir
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_dom_from_idl(self):
        """Parses extracted IDLs and generates Rust DOM structures."""
        print("[*] Codegen: Generating DOM from IDLs...")
        idl_path = os.path.join(self.data_dir, "dom.idl")
        if not os.path.exists(idl_path): return

        with open(idl_path, "r", encoding='utf-8') as f:
            content = f.read()

        # Find interfaces: interface Name { ... } (handling decorators like [Exposed=Window])
        interfaces = re.findall(r'(?:\[[^\]]+\]\s*)?interface ([A-Za-z0-9_]+) (?:: ([A-Za-z0-9_]+) )?\{([\s\S]*?)\};', content)
        
        rust_code = [
            "// AUTO-GENERATED NATIVE DOM",
            "// Based on official WebIDL ADN",
            "",
            "#[allow(dead_code)]",
        ]
        
        for name, parent, body in interfaces:
            rust_code.append(f"/// {name} Interface (Inherits: {parent if parent else 'Base'})")
            rust_code.append(f"pub struct {name} {{")
            rust_code.append("    pub id: u64,")
            if parent:
                rust_code.append(f"    pub super_class: Box<{parent}>,")
            rust_code.append("}")
            rust_code.append("")
            
            # Simple attribute generation
            attrs = re.findall(r'attribute ([A-Za-z0-9_ ]+) ([A-Za-z0-9_]+);', body)
            rust_code.append(f"impl {name} {{")
            rust_code.append(f"    pub fn new(id: u64) -> Self {{")
            if parent:
                rust_code.append(f"        Self {{ id, super_class: Box::new({parent}::new(id)) }}")
            else:
                rust_code.append(f"        Self {{ id }}")
            rust_code.append("    }")
            
            for attr_type, attr_name in attrs:
                rust_code.append(f"    pub fn get_{attr_name}(&self) -> &str {{")
                rust_code.append(f'        "{attr_name}"')
                rust_code.append("    }")
            rust_code.append("}")
            rust_code.append("")

        with open(os.path.join(self.output_dir, "dom_native.rs"), "w", encoding='utf-8') as f:
            f.write("\n".join(rust_code))

    def generate_net_stack(self):
        """Generates a high-performance networking stack stub in Rust."""
        print("[*] Codegen: Generating Sovereign Network Stack...")
        rust_code = [
            "// AUTO-GENERATED SOVEREIGN NETWORK STACK",
            "pub struct NetClient {",
            "    pub user_agent: String,",
            "}",
            "",
            "impl NetClient {",
            "    pub fn new() -> Self {",
            '        Self { user_agent: "No-Chromium/1.0".to_string() }',
            "    }",
            "",
            "    pub async fn fetch(&self, url: &str) -> Result<String, String> {",
            '        println!("[NET] Fetching: {}", url);',
            '        Ok("<html>Generated by No-Chromium NET</html>".to_string())',
            "    }",
            "}",
        ]
        with open(os.path.join(self.output_dir, "net_stack.rs"), "w", encoding='utf-8') as f:
            f.write("\n".join(rust_code))

    def run(self):
        self.generate_dom_from_idl()
        self.generate_net_stack()
        
        # Update mod.rs
        with open(os.path.join(self.output_dir, "mod.rs"), "a") as f:
            f.write("pub mod dom_native;\n")
            f.write("pub mod net_stack;\n")

if __name__ == "__main__":
    gen = MasterCodegen()
    gen.run()
