import json
import os

class RustCodegen:
    """
    Transforms the V8 'Bible' data into functional Rust code.
    It automates the creation of structs, handles, and interfaces.
    """
    def __init__(self, map_path="No-Chromium/v8_reconstruction_map.json", output_dir="No-Chromium/generated_rust"):
        self.map_path = map_path
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_v8_core(self):
        """Generates the core V8 structures in Rust."""
        print("[*] Generating V8 Core Bindings in Rust...")
        with open(self.map_path, "r") as f:
            data = json.load(f)

        lines = [
            "// AUTO-GENERATED BY NO-CHROMIUM RUST CODEGEN",
            "// Based on the V8 'Bible' Extraction",
            "",
            "#[allow(dead_code)]",
            "pub struct V8Handle {",
            "    pub ptr: usize,",
            "}",
            "",
        ]

        # Process classes from the reconstruction map
        unique_classes = sorted(list(set(cls["name"] for cls in data["core_classes"])))
        
        for cls_name in unique_classes:
            lines.append(f"/// Native Rust handle for V8 {cls_name}")
            lines.append(f"pub struct {cls_name} {{")
            lines.append("    pub handle: V8Handle,")
            lines.append("}")
            lines.append("")
            
            lines.append(f"impl {cls_name} {{")
            lines.append(f"    pub fn from_raw(ptr: usize) -> Self {{")
            lines.append(f"        Self {{ handle: V8Handle {{ ptr }} }}")
            lines.append("    }")
            lines.append("}")
            lines.append("")

        output_path = os.path.join(self.output_dir, "v8_core.rs")
        with open(output_path, "w", encoding='utf-8') as f:
            f.write("\n".join(lines))
        
        # Create mod.rs
        with open(os.path.join(self.output_dir, "mod.rs"), "w") as f:
            f.write("pub mod v8_core;\n")
            
        print(f"[+] Rust Engine Base generated at {output_path}")

if __name__ == "__main__":
    codegen = RustCodegen()
    codegen.generate_v8_core()
