//! Auto-generated JS Interpreter
//! Generated by Python - do not edit manually

use std::collections::HashMap;
use std::rc::Rc;
use std::cell::RefCell;
use super::ast::*;

#[derive(Debug, Clone)]
pub enum Value {
    Number(f64),
    String(String),
    Bool(bool),
    Null,
    Undefined,
    Object(Rc<RefCell<HashMap<String, Value>>>),
}

impl PartialEq for Value {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Value::Number(a), Value::Number(b)) => a == b,
            (Value::String(a), Value::String(b)) => a == b,
            (Value::Bool(a), Value::Bool(b)) => a == b,
            (Value::Null, Value::Null) => true,
            (Value::Undefined, Value::Undefined) => true,
            _ => false,
        }
    }
}

pub struct Env {
    variables: HashMap<String, Value>,
}

impl Env {
    pub fn new() -> Self {
        Self { variables: HashMap::new() }
    }

    pub fn get(&self, name: &str) -> Option<Value> {
        self.variables.get(name).cloned()
    }

    pub fn set(&mut self, name: String, value: Value) {
        self.variables.insert(name, value);
    }
}

pub struct Interpreter {
    env: Env,
}

impl Interpreter {
    pub fn new() -> Self {
        Self { env: Env::new() }
    }

    pub fn interpret(&mut self, program: &Program) -> Result<Value, String> {
        let mut result = Value::Undefined;
        for stmt in &program.body {
            self.exec_stmt(stmt)?;
        }
        Ok(result)
    }

    fn exec_stmt(&mut self, stmt: &Stmt) -> Result<Value, String> {
        match stmt {
            Stmt::VarDecl { name, value } => {
                let v = if let Some(expr) = value {
                    self.eval_expr(expr)?
                } else {
                    Value::Undefined
                };
                self.env.set(name.clone(), v);
                Ok(Value::Undefined)
            }
            Stmt::Expr(expr) => self.eval_expr(expr),
            Stmt::Return(expr) => {
                let v = if let Some(e) = expr {
                    Some(self.eval_expr(e)?)
                } else {
                    None
                };
                Err(format!("RETURN:{:?}", v))
            }
            _ => Ok(Value::Undefined),
        }
    }

    fn eval_expr(&mut self, expr: &Expr) -> Result<Value, String> {
        match expr {
            Expr::Number(n) => Ok(Value::Number(*n)),
            Expr::String(s) => Ok(Value::String(s.clone())),
            Expr::Bool(b) => Ok(Value::Bool(*b)),
            Expr::Null => Ok(Value::Null),
            Expr::Undefined => Ok(Value::Undefined),
            Expr::Identifier(name) => {
                self.env.get(name)
                    .ok_or_else(|| format!("Undefined variable: {}", name))
            }
            Expr::Binary { op, left, right } => {
                let l = self.eval_expr(left)?;
                let r = self.eval_expr(right)?;
                self.eval_binary(*op, &l, &r)
            }
            _ => Ok(Value::Undefined),
        }
    }

    fn eval_binary(&self, op: BinaryOp, l: &Value, r: &Value) -> Result<Value, String> {
        match (l, r) {
            (Value::Number(a), Value::Number(b)) => {
                let result = match op {
                    BinaryOp::Add => a + b,
                    BinaryOp::Sub => a - b,
                    BinaryOp::Mul => a * b,
                    BinaryOp::Div => a / b,
                    BinaryOp::Mod => a % b,
                    _ => return Ok(Value::Bool(false)),
                };
                Ok(Value::Number(result))
            }
            _ => Ok(Value::Bool(false)),
        }
    }
}
