//! Auto-generated JS Lexer
//! Generated by Python - do not edit manually

use std::iter::Peekable;
use std::str::Chars;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    KwLet,
    KwConst,
    KwVar,
    KwFunction,
    KwReturn,
    KwIf,
    KwElse,
    KwWhile,
    KwFor,
    KwClass,
    KwNew,
    KwThis,
    KwTrue,
    KwFalse,
    KwNull,
    KwUndefined,
    OpAdd,
    OpSub,
    OpMul,
    OpDiv,
    OpMod,
    OpAssign,
    OpEq,
    OpStrictEq,
    OpNotEq,
    OpStrictNotEq,
    OpLt,
    OpGt,
    OpLtEq,
    OpGtEq,
    OpAnd,
    OpOr,
    OpNot,
    PunctLParen,
    PunctRParen,
    PunctLBrace,
    PunctRBrace,
    PunctLBracket,
    PunctRBracket,
    PunctSemi,
    PunctComma,
    PunctDot,
    PunctColon,
    PunctQuestion,
    Number,
    String,
    Identifier,
    Whitespace,
    Comment,
    Eof,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub value: String,
    pub line: u32,
    pub col: u32,
}

pub struct Lexer<'a> {
    input: Peekable<Chars<'a>>,
    line: u32,
    col: u32,
}

impl<'a> Lexer<'a> {
    pub fn new(input: &'a str) -> Self {
        Self {
            input: input.chars().peekable(),
            line: 1,
            col: 1,
        }
    }

    pub fn tokenize(&mut self) -> Vec<Token> {
        let mut tokens = Vec::new();
        while let Some(token) = self.next_token() {
            let is_ws = matches!(token.kind, TokenKind::Whitespace | TokenKind::Comment);
            if !is_ws {
                tokens.push(token.clone());
            }
            if matches!(token.kind, TokenKind::Eof) {
                break;
            }
        }
        tokens
    }

    fn next_token(&mut self) -> Option<Token> {
        let ch = *self.input.peek()?;

        if ch.is_whitespace() {
            return Some(self.read_whitespace());
        }

        if ch == '/' {
            return Some(self.read_comment_or_div());
        }

        if ch.is_ascii_digit() {
            return Some(self.read_number());
        }

        if ch == '"' || ch == '\'' {
            return Some(self.read_string());
        }

        if ch.is_alphabetic() || ch == '_' || ch == '$' {
            return Some(self.read_identifier());
        }

        Some(self.read_operator())
    }

    fn read_whitespace(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_whitespace() {
                if ch == '\n' {
                    self.line += 1;
                    self.col = 1;
                } else {
                    self.col += 1;
                }
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }
        Token { kind: TokenKind::Whitespace, value, line, col }
    }

    fn read_comment_or_div(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        value.push(self.input.next().unwrap());

        if self.input.peek() == Some(&'/') {
            value.push(self.input.next().unwrap());
            while let Some(&ch) = self.input.peek() {
                if ch == '\n' { break; }
                value.push(self.input.next().unwrap());
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else if self.input.peek() == Some(&'*') {
            value.push(self.input.next().unwrap());
            while let Some(ch) = self.input.next() {
                value.push(ch);
                if ch == '*' && self.input.peek() == Some(&'/') {
                    value.push(self.input.next().unwrap());
                    break;
                }
            }
            Token { kind: TokenKind::Comment, value, line, col }
        } else {
            Token { kind: TokenKind::OpDiv, value: "/".to_string(), line, col }
        }
    }

    fn read_number(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_ascii_digit() || ch == '.' {
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }
        Token { kind: TokenKind::Number, value, line, col }
    }

    fn read_string(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let quote = self.input.next().unwrap();
        let mut value = String::new();
        value.push(quote);
        while let Some(ch) = self.input.next() {
            value.push(ch);
            if ch == quote {
                break;
            }
            if ch == '\\' {
                if let Some(escaped) = self.input.next() {
                    value.push(escaped);
                }
            }
        }
        Token { kind: TokenKind::String, value, line, col }
    }

    fn read_identifier(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let mut value = String::new();
        while let Some(&ch) = self.input.peek() {
            if ch.is_alphanumeric() || ch == '_' || ch == '$' {
                value.push(self.input.next().unwrap());
            } else {
                break;
            }
        }

        let kind = match value.as_str() {
            "let" => TokenKind::KwLet,
            "const" => TokenKind::KwConst,
            "var" => TokenKind::KwVar,
            "function" => TokenKind::KwFunction,
            "return" => TokenKind::KwReturn,
            "if" => TokenKind::KwIf,
            "else" => TokenKind::KwElse,
            "while" => TokenKind::KwWhile,
            "for" => TokenKind::KwFor,
            "class" => TokenKind::KwClass,
            "new" => TokenKind::KwNew,
            "this" => TokenKind::KwThis,
            "true" => TokenKind::KwTrue,
            "false" => TokenKind::KwFalse,
            "null" => TokenKind::KwNull,
            "undefined" => TokenKind::KwUndefined,
            _ => TokenKind::Identifier,
        };

        Token { kind, value, line, col }
    }

    fn read_operator(&mut self) -> Token {
        let line = self.line;
        let col = self.col;
        let ch = self.input.next().unwrap();
        let mut value = ch.to_string();

        let (kind, _): (TokenKind, ()) = match value.as_str() {
            "+" => (TokenKind::OpAdd, ()),
            "-" => (TokenKind::OpSub, ()),
            "*" => (TokenKind::OpMul, ()),
            "/" => (TokenKind::OpDiv, ()),
            "%" => (TokenKind::OpMod, ()),
            "=" => (TokenKind::OpAssign, ()),
            "(" => (TokenKind::PunctLParen, ()),
            ")" => (TokenKind::PunctRParen, ()),
            "{" => (TokenKind::PunctLBrace, ()),
            "}" => (TokenKind::PunctRBrace, ()),
            "[" => (TokenKind::PunctLBracket, ()),
            "]" => (TokenKind::PunctRBracket, ()),
            ";" => (TokenKind::PunctSemi, ()),
            "," => (TokenKind::PunctComma, ()),
            "." => (TokenKind::PunctDot, ()),
            ":" => (TokenKind::PunctColon, ()),
            "?" => (TokenKind::PunctQuestion, ()),
            _ => (TokenKind::Eof, ()),
        };

        Token { kind, value, line, col }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tokenize_let() {
        let mut lexer = Lexer::new("let x = 42;");
        let tokens = lexer.tokenize();
        assert!(tokens.len() >= 5);
        assert!(matches!(tokens[0].kind, TokenKind::KwLet));
    }

    #[test]
    fn test_tokenize_function() {
        let mut lexer = Lexer::new("function foo() { return 1; }");
        let tokens = lexer.tokenize();
        assert!(tokens.len() > 5);
    }

    #[test]
    fn test_tokenize_arithmetic() {
        let mut lexer = Lexer::new("a + b * c");
        let tokens = lexer.tokenize();
        assert!(tokens.len() >= 5);
    }
}
