//! Auto-generated JS Parser
//! Generated by Python - do not edit manually

use super::ast::*;
use super::lexer::*;

pub struct Parser {
    tokens: Vec<Token>,
    pos: usize,
}

impl Parser {
    pub fn new(tokens: Vec<Token>) -> Self {
        Self { tokens, pos: 0 }
    }

    pub fn parse(&mut self) -> Result<Program, String> {
        let mut body = Vec::new();
        while !self.is_eof() {
            body.push(self.parse_stmt()?);
        }
        Ok(Program { body })
    }

    fn parse_stmt(&mut self) -> Result<Stmt, String> {
        let token = self.peek().clone();

        match token.kind {
            TokenKind::KwLet | TokenKind::KwConst | TokenKind::KwVar => {
                self.parse_var_decl()
            }
            TokenKind::KwReturn => {
                self.advance();
                let expr = if !self.is_eof() {
                    Some(self.parse_expr()?)
                } else {
                    None
                };
                Ok(Stmt::Return(expr))
            }
            TokenKind::KwIf => self.parse_if(),
            TokenKind::KwWhile => self.parse_while(),
            _ => {
                let expr = self.parse_expr()?;
                Ok(Stmt::Expr(expr))
            }
        }
    }

    fn parse_var_decl(&mut self) -> Result<Stmt, String> {
        self.advance();
        let name = self.expect_identifier()?;
        let value = if matches!(self.peek().kind, TokenKind::OpAssign) {
            self.advance();
            Some(self.parse_expr()?)
        } else {
            None
        };
        Ok(Stmt::VarDecl { name, value })
    }

    fn parse_if(&mut self) -> Result<Stmt, String> {
        self.advance();
        let condition = self.parse_expr()?;
        let then_branch = self.parse_block()?;
        let else_branch = if matches!(self.peek().kind, TokenKind::KwElse) {
            self.advance();
            Some(self.parse_block()?)
        } else {
            None
        };
        Ok(Stmt::If { condition, then_branch, else_branch })
    }

    fn parse_while(&mut self) -> Result<Stmt, String> {
        self.advance();
        let condition = self.parse_expr()?;
        let body = self.parse_block()?;
        Ok(Stmt::While { condition, body })
    }

    fn parse_block(&mut self) -> Result<Vec<Stmt>, String> {
        if !matches!(self.peek().kind, TokenKind::PunctLBrace) {
            return Err("Expected block".to_string());
        }
        self.advance();
        let mut stmts = Vec::new();
        while !matches!(self.peek().kind, TokenKind::PunctRBrace) && !self.is_eof() {
            stmts.push(self.parse_stmt()?);
        }
        self.advance();
        Ok(stmts)
    }

    fn parse_expr(&mut self) -> Result<Expr, String> {
        self.parse_additive()
    }

    fn parse_additive(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_multiplicative()?;
        while matches!(self.peek().kind, TokenKind::OpAdd | TokenKind::OpSub) {
            let op = match self.peek().kind {
                TokenKind::OpAdd => BinaryOp::Add,
                _ => BinaryOp::Sub,
            };
            self.advance();
            let right = self.parse_multiplicative()?;
            left = Expr::Binary {
                op,
                left: Box::new(left),
                right: Box::new(right),
            };
        }
        Ok(left)
    }

    fn parse_multiplicative(&mut self) -> Result<Expr, String> {
        let mut left = self.parse_unary()?;
        while matches!(self.peek().kind,
            TokenKind::OpMul | TokenKind::OpDiv | TokenKind::OpMod) {
            let op = match self.peek().kind {
                TokenKind::OpMul => BinaryOp::Mul,
                TokenKind::OpDiv => BinaryOp::Div,
                _ => BinaryOp::Mod,
            };
            self.advance();
            let right = self.parse_unary()?;
            left = Expr::Binary {
                op,
                left: Box::new(left),
                right: Box::new(right),
            };
        }
        Ok(left)
    }

    fn parse_unary(&mut self) -> Result<Expr, String> {
        if matches!(self.peek().kind, TokenKind::OpSub) {
            self.advance();
            let operand = self.parse_unary()?;
            return Ok(Expr::Unary { op: UnaryOp::Neg, operand: Box::new(operand) });
        }
        if matches!(self.peek().kind, TokenKind::OpNot) {
            self.advance();
            let operand = self.parse_unary()?;
            return Ok(Expr::Unary { op: UnaryOp::Not, operand: Box::new(operand) });
        }
        self.parse_call()
    }

    fn parse_call(&mut self) -> Result<Expr, String> {
        let mut expr = self.parse_primary()?;
        loop {
            if matches!(self.peek().kind, TokenKind::PunctLParen) {
                self.advance();
                let mut args = Vec::new();
                while !matches!(self.peek().kind, TokenKind::PunctRParen) {
                    args.push(self.parse_expr()?);
                    if matches!(self.peek().kind, TokenKind::PunctComma) {
                        self.advance();
                    } else {
                        break;
                    }
                }
                self.advance();
                expr = Expr::Call { callee: Box::new(expr), args };
            } else {
                break;
            }
        }
        Ok(expr)
    }

    fn parse_primary(&mut self) -> Result<Expr, String> {
        let token = self.peek().clone();
        match token.kind {
            TokenKind::Number => {
                self.advance();
                let n: f64 = token.value.parse().map_err(|_| "Invalid number".to_string())?;
                Ok(Expr::Number(n))
            }
            TokenKind::String => {
                self.advance();
                Ok(Expr::String(token.value))
            }
            TokenKind::KwTrue => { self.advance(); Ok(Expr::Bool(true)) }
            TokenKind::KwFalse => { self.advance(); Ok(Expr::Bool(false)) }
            TokenKind::KwNull => { self.advance(); Ok(Expr::Null) }
            TokenKind::KwUndefined => { self.advance(); Ok(Expr::Undefined) }
            TokenKind::KwThis => { self.advance(); Ok(Expr::This) }
            TokenKind::Identifier => {
                self.advance();
                Ok(Expr::Identifier(token.value))
            }
            _ => Err(format!("Unexpected token: {:?}", token.kind)),
        }
    }

    fn peek(&self) -> &Token {
        &self.tokens[self.pos]
    }

    fn advance(&mut self) {
        if self.pos < self.tokens.len().saturating_sub(1) {
            self.pos += 1;
        }
    }

    fn is_eof(&self) -> bool {
        self.pos >= self.tokens.len() || matches!(self.peek().kind, TokenKind::Eof)
    }

    fn expect_identifier(&mut self) -> Result<String, String> {
        let token = self.peek().clone();
        if matches!(token.kind, TokenKind::Identifier) {
            self.advance();
            Ok(token.value)
        } else {
            Err(format!("Expected identifier, got {:?}", token.kind))
        }
    }
}
