// Bitmap font glyphs for Noir Browser

pub fn get_glyph_bitmap(ch: char) -> &'static [[bool; 6]; 8] {
    match ch {
        'A' => &[
            [false, false, true, true, false, false],
            [false, true, false, false, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'B' => &[
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
        ],
        'C' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'D' => &[
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
        ],
        'E' => &[
            [true, true, true, true, true, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, true],
        ],
        'F' => &[
            [true, true, true, true, true, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
        ],
        'G' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'H' => &[
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'I' => &[
            [true, true, true, true, true, true],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [true, true, true, true, true, true],
        ],
        'L' => &[
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, true],
        ],
        'N' => &[
            [true, false, false, false, false, true],
            [true, true, false, false, false, true],
            [true, false, true, false, false, true],
            [true, false, false, true, false, true],
            [true, false, false, false, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'O' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'R' => &[
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
            [true, false, true, false, false, false],
            [true, false, false, true, false, false],
            [true, false, false, false, true, false],
            [true, false, false, false, false, true],
        ],
        'S' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'T' => &[
            [true, true, true, true, true, true],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
        ],
        'U' => &[
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'b' => &[
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
        ],
        'c' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
        ],
        'd' => &[
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, true, true, true, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, true, false],
        ],
        'e' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
        ],
        'g' => &[
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, true, false],
            [false, false, false, false, true, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, false],
        ],
        'h' => &[
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'i' => &[
            [false, false, true, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, true, true, true, false, false],
        ],
        'l' => &[
            [false, true, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, true, true, true, false, false],
        ],
        'o' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'r' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
        ],
        's' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, false],
            [false, true, true, true, false, false],
            [false, false, false, false, true, false],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
        ],
        't' => &[
            [false, false, true, false, false, false],
            [false, true, true, true, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, true, false],
            [false, false, false, true, false, false],
        ],
        'u' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, false, false],
        ],
        'w' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, true, false, true, true],
            [true, false, true, false, true, true],
            [false, true, false, true, false, false],
        ],
        '<' => &[
            [false, false, false, false, false, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, false, false, false, false],
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
        ],
        '>' => &[
            [false, false, false, false, false, false],
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, true, false],
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
        ],
        '+' => &[
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [true, true, true, true, true, true],
            [true, true, true, true, true, true],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
        ],
        '.' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, false, false, false],
            [false, true, true, false, false, false],
        ],
        ':' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
        ],
        '/' => &[
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
        ],
        '=' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '-' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        ' ' => &[[false; 6]; 8],
        _ => &[
            [true, true, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
        ],
    }
}
