pub fn get_glyph_bitmap(ch: char) -> &'static [[bool; 6]; 8] {
    match ch {
        // ═══ UPPERCASE A-Z ═══
        'A' => &[
            [false, false, true, true, false, false],
            [false, true, false, false, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'B' => &[
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
        ],
        'C' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'D' => &[
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
        ],
        'E' => &[
            [true, true, true, true, true, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, true],
        ],
        'F' => &[
            [true, true, true, true, true, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
        ],
        'G' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'H' => &[
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'I' => &[
            [true, true, true, true, true, true],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [true, true, true, true, true, true],
        ],
        'J' => &[
            [false, false, false, false, true, true],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'K' => &[
            [true, false, false, false, false, true],
            [true, false, false, false, true, false],
            [true, false, false, true, false, false],
            [true, false, true, false, false, false],
            [true, true, false, false, false, false],
            [true, false, true, false, false, false],
            [true, false, false, true, false, false],
            [true, false, false, false, true, false],
        ],
        'L' => &[
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, true],
        ],
        'M' => &[
            [true, false, false, false, false, true],
            [true, true, false, false, true, true],
            [true, false, true, true, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'N' => &[
            [true, false, false, false, false, true],
            [true, true, false, false, false, true],
            [true, false, true, false, false, true],
            [true, false, false, true, false, true],
            [true, false, false, false, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'O' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'P' => &[
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
        ],
        'Q' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, true, false, false, true],
            [true, false, false, true, false, false],
            [false, true, true, false, true, true],
        ],
        'R' => &[
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
            [true, false, true, false, false, false],
            [true, false, false, true, false, false],
            [true, false, false, false, true, false],
            [true, false, false, false, false, true],
        ],
        'S' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'T' => &[
            [true, true, true, true, true, true],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
        ],
        'U' => &[
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'V' => &[
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, false, false, true, false],
            [false, true, false, false, true, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
        ],
        'W' => &[
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, true, true, false, true],
            [true, true, false, false, true, true],
            [true, false, false, false, false, true],
        ],
        'X' => &[
            [true, false, false, false, false, true],
            [false, true, false, false, true, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, true, false, false, true, false],
            [true, false, false, false, false, true],
        ],
        'Y' => &[
            [true, false, false, false, false, true],
            [false, true, false, false, true, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
        ],
        'Z' => &[
            [true, true, true, true, true, true],
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, true],
        ],

        // ═══ LOWERCASE a-z ═══
        'a' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, true, false],
        ],
        'b' => &[
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
        ],
        'c' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
        ],
        'd' => &[
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, true, true, true, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, true, false],
        ],
        'e' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
        ],
        'f' => &[
            [false, false, false, true, true, false],
            [false, false, true, false, false, true],
            [false, false, true, false, false, false],
            [false, true, true, true, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
        ],
        'g' => &[
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, true, false],
            [false, false, false, false, true, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, false],
        ],
        'h' => &[
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'i' => &[
            [false, false, true, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, true, true, true, false, false],
        ],
        'j' => &[
            [false, false, false, false, true, false],
            [false, false, false, false, false, false],
            [false, false, false, true, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, false, false],
        ],
        'k' => &[
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, true, false, false],
            [true, false, true, false, false, false],
            [true, true, false, false, false, false],
            [true, false, true, false, false, false],
            [true, false, false, true, false, false],
            [true, false, false, false, true, false],
        ],
        'l' => &[
            [false, true, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, true, true, true, false, false],
        ],
        'm' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, false, true, true, false],
            [true, false, true, false, false, true],
            [true, false, true, false, false, true],
            [true, false, true, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'n' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
        ],
        'o' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        'p' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
        ],
        'q' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, true],
        ],
        'r' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
        ],
        's' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, true, true, false],
            [true, false, false, false, false, false],
            [false, true, true, true, false, false],
            [false, false, false, false, true, false],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
        ],
        't' => &[
            [false, false, true, false, false, false],
            [false, true, true, true, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, true, false],
            [false, false, false, true, false, false],
        ],
        'u' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [false, true, true, true, false, false],
        ],
        'v' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, false, false, true, false],
            [false, true, false, false, true, false],
            [false, false, true, true, false, false],
        ],
        'w' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, true, false, true, true],
            [true, false, true, false, true, true],
            [false, true, false, true, false, false],
        ],
        'x' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, true],
            [false, true, false, false, true, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, true, false, false, true, false],
            [true, false, false, false, false, true],
        ],
        'y' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, false, false, true, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, false, false, false],
        ],
        'z' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [true, true, true, true, true, true],
        ],

        // ═══ DIGITS 0-9 ═══
        '0' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, true, true],
            [true, false, false, true, false, true],
            [true, false, true, false, false, true],
            [true, true, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        '1' => &[
            [false, false, false, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, true, true, true, false],
        ],
        '2' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [true, true, true, true, true, true],
        ],
        '3' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, true, true, true, false],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        '4' => &[
            [false, false, false, false, true, false],
            [false, false, false, true, true, false],
            [false, false, true, false, true, false],
            [false, true, false, false, true, false],
            [true, false, false, false, true, false],
            [true, true, true, true, true, true],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
        ],
        '5' => &[
            [true, true, true, true, true, true],
            [true, false, false, false, false, false],
            [true, true, true, true, true, false],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        '6' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [true, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        '7' => &[
            [true, true, true, true, true, true],
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
        ],
        '8' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],
        '9' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [false, true, true, true, true, true],
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, true, true, true, true, false],
        ],

        // ═══ SYMBOLS ═══
        '!' => &[
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
        ],
        '?' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, false, false],
            [false, false, false, true, false, false],
        ],
        '@' => &[
            [false, true, true, true, true, false],
            [true, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, true, true, true, false, true],
            [true, false, false, true, false, true],
            [true, false, false, true, false, true],
            [true, false, false, false, false, false],
            [false, true, true, true, true, false],
        ],
        '#' => &[
            [false, false, true, false, true, false],
            [false, false, true, false, true, false],
            [true, true, true, true, true, true],
            [false, false, true, false, true, false],
            [false, false, true, false, true, false],
            [true, true, true, true, true, true],
            [false, false, true, false, true, false],
            [false, false, true, false, true, false],
        ],
        '$' => &[
            [false, false, false, true, false, false],
            [false, true, true, true, true, true],
            [true, false, true, false, false, false],
            [false, true, true, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, true, true, true, true, false],
            [false, false, false, true, false, false],
        ],
        '%' => &[
            [true, true, false, false, false, true],
            [true, true, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [true, false, false, false, true, true],
            [false, false, false, false, true, true],
            [false, false, false, false, false, false],
        ],
        '^' => &[
            [false, false, true, true, false, false],
            [false, true, false, false, true, false],
            [true, false, false, false, false, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '&' => &[
            [false, true, true, false, false, false],
            [true, false, false, true, false, false],
            [true, false, false, true, false, false],
            [false, true, true, false, false, false],
            [true, false, false, true, false, true],
            [true, false, false, false, true, false],
            [true, false, false, false, false, true],
            [false, true, true, true, false, true],
        ],
        '*' => &[
            [false, false, false, false, false, false],
            [false, false, true, false, true, false],
            [false, false, false, true, false, false],
            [true, true, true, true, true, true],
            [false, false, false, true, false, false],
            [false, false, true, false, true, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '(' => &[
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
        ],
        ')' => &[
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
        ],
        '[' => &[
            [false, true, true, true, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, true, false, false, false, false],
            [false, true, true, true, false, false],
        ],
        ']' => &[
            [false, false, true, true, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, true, true, true, false],
        ],
        '{' => &[
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
        ],
        '}' => &[
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
        ],
        '_' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
        ],
        '|' => &[
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
        ],
        '\\' => &[
            [true, false, false, false, false, false],
            [false, true, false, false, false, false],
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, true, false],
            [false, false, false, false, false, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '~' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, false, false, false, true],
            [true, false, true, false, true, false],
            [true, false, false, true, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '\'' => &[
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '"' => &[
            [false, true, false, true, false, false],
            [false, true, false, true, false, false],
            [false, true, false, true, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '<' => &[
            [false, false, false, false, false, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, false, false, false, false],
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
        ],
        '>' => &[
            [false, false, false, false, false, false],
            [false, false, true, false, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, true, false],
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
        ],
        '+' => &[
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [true, true, true, true, true, true],
            [true, true, true, true, true, true],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
        ],
        '-' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        '.' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, true, true, false, false, false],
            [false, true, true, false, false, false],
        ],
        ',' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
        ],
        ':' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
        ],
        ';' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, false, false, false, false],
            [false, false, true, true, false, false],
            [false, false, true, true, false, false],
            [false, false, true, false, false, false],
        ],
        '/' => &[
            [false, false, false, false, false, true],
            [false, false, false, false, true, false],
            [false, false, false, false, true, false],
            [false, false, false, true, false, false],
            [false, false, false, true, false, false],
            [false, false, true, false, false, false],
            [false, false, true, false, false, false],
            [false, true, false, false, false, false],
        ],
        '=' => &[
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, true, true, true, true, true],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false],
        ],
        ' ' => &[[false; 6]; 8],

        // ═══ FALLBACK ═══
        _ => &[
            [true, true, true, true, true, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, false, false, false, false, true],
            [true, true, true, true, true, true],
        ],
    }
}
