//! Console - Logging API
//! Generated by Python

use std::cell::RefCell;
use std::sync::Mutex;
use super::value::JsValue;

#[derive(Debug, Clone)]
pub struct LogEntry {
    pub level: LogLevel,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum LogLevel {
    Log,
    Info,
    Warn,
    Error,
    Debug,
}

pub struct Console {
    pub logs: RefCell<Vec<LogEntry>>,
}

impl Console {
    pub fn new() -> Self {
        Self { logs: RefCell::new(Vec::new()) }
    }

    pub fn log(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Log, message: msg });
        tracing::info!("[console.log] {}", self.logs.borrow().last().map(|l| l.message.clone()).unwrap_or_default());
    }

    pub fn info(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Info, message: msg });
    }

    pub fn warn(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Warn, message: msg.clone() });
        tracing::warn!("[console.warn] {}", msg);
    }

    pub fn error(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Error, message: msg.clone() });
        tracing::error!("[console.error] {}", msg);
    }

    pub fn debug(&self, args: &[JsValue]) {
        let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
        self.logs.borrow_mut().push(LogEntry { level: LogLevel::Debug, message: msg });
    }

    pub fn clear(&self) {
        self.logs.borrow_mut().clear();
    }
}

// Native functions for console
pub fn console_log(args: &[JsValue]) -> Result<JsValue, String> {
    let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
    tracing::info!("[console.log] {}", msg);
    Ok(JsValue::Undefined)
}
pub fn console_warn(args: &[JsValue]) -> Result<JsValue, String> {
    let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
    tracing::warn!("[console.warn] {}", msg);
    Ok(JsValue::Undefined)
}
pub fn console_error(args: &[JsValue]) -> Result<JsValue, String> {
    let msg = args.iter().map(|a| a.to_string()).collect::<Vec<_>>().join(" ");
    tracing::error!("[console.error] {}", msg);
    Ok(JsValue::Undefined)
}
pub fn console_info(args: &[JsValue]) -> Result<JsValue, String> {
    console_log(args)
}
