//! Fetch - Network API
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use std::sync::{Arc, Mutex};
use super::value::JsValue;

#[derive(Debug, Clone)]
pub struct FetchRequest {
    pub url: String,
    pub method: String,
    pub headers: HashMap<String, String>,
    pub body: Option<String>,
}

#[derive(Debug, Clone)]
pub struct FetchResponse {
    pub url: String,
    pub status: u16,
    pub ok: bool,
    pub body: String,
    pub headers: HashMap<String, String>,
}

pub struct FetchQueue {
    pub pending: RefCell<Vec<FetchRequest>>,
    pub responses: RefCell<Vec<FetchResponse>>,
}

impl FetchQueue {
    pub fn new() -> Self {
        Self {
            pending: RefCell::new(Vec::new()),
            responses: RefCell::new(Vec::new()),
        }
    }

    pub fn enqueue(&self, request: FetchRequest) {
        self.pending.borrow_mut().push(request);
    }

    pub fn take_responses(&self) -> Vec<FetchResponse> {
        std::mem::take(&mut *self.responses.borrow_mut())
    }
}

pub fn js_fetch(args: &[JsValue]) -> Result<JsValue, String> {
    if args.is_empty() {
        return Err("fetch needs URL".to_string());
    }
    let url = args[0].to_string();
    tracing::info!("[fetch] {}", url);
    // Would return a Promise
    Ok(JsValue::Object(Rc::new(RefCell::new(HashMap::new()))))
}
