//! JS Engine v3 - Minimalista con DOM completo
//! Generated by Python - do not edit manually

pub mod value;
pub mod env;
pub mod ast;
pub mod lexer;
pub mod parser;
pub mod interpreter;
pub mod dom;
pub mod console;
pub mod timer;
pub mod fetch;
pub mod promise;
pub mod builtins;

pub use value::JsValue;
pub use env::Env;
pub use interpreter::Interpreter;
pub use dom::{Dom, DomNode, DomEvent};

// Compatibility API for app/mod.rs
/// Execute a JS script and return the result as a string
pub fn eval_script(interp: &mut Interpreter, _tab_id: u64, script: &str) -> Result<String, String> {
    let mut lexer = lexer::Lexer::new(script);
    let tokens = lexer.tokenize();
    let mut parser = parser::Parser::new(tokens);
    let program = parser.parse().map_err(|e| e.to_string())?;
    let result = interp.interpret(&program)?;
    Ok(result.to_string())
}

/// Sync DOM to JS engine
pub fn sync_dom_to_js_engine(_nodes: &[crate::parsers::dom_tree::DomNode]) {
    // Placeholder
}

/// Extract inline scripts from DOM
pub fn extract_inline_scripts(_nodes: &[crate::parsers::dom_tree::DomNode]) -> Vec<String> {
    Vec::new()
}

/// Rebuild page from DOM
pub fn rebuild_page_from_dom(_page: &mut crate::parsers::page_document::PageDocument) {
    // Placeholder
}

/// Check if DOM was mutated by JS
pub fn take_mutated_flag() -> bool {
    false
}

/// Get pending timers
pub struct PendingTimer {
    pub callback_id: u64,
}

pub fn get_pending_timers() -> Vec<PendingTimer> {
    Vec::new()
}
