//! Timer - setTimeout, setInterval
//! Generated by Python

use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use std::time::{Duration, Instant};
use super::value::JsValue;

pub struct Timer {
    pub id: u64,
    pub callback: JsValue,
    pub delay_ms: u64,
    pub created_at: Instant,
    pub is_interval: bool,
    pub fired: bool,
}

pub struct TimerQueue {
    pub timers: RefCell<HashMap<u64, Timer>>,
    pub next_id: RefCell<u64>,
}

impl TimerQueue {
    pub fn new() -> Self {
        Self {
            timers: RefCell::new(HashMap::new()),
            next_id: RefCell::new(1),
        }
    }

    pub fn set_timeout(&self, callback: JsValue, delay_ms: u64) -> u64 {
        let id = *self.next_id.borrow();
        *self.next_id.borrow_mut() += 1;
        let timer = Timer {
            id,
            callback,
            delay_ms,
            created_at: Instant::now(),
            is_interval: false,
            fired: false,
        };
        self.timers.borrow_mut().insert(id, timer);
        id
    }

    pub fn set_interval(&self, callback: JsValue, delay_ms: u64) -> u64 {
        let id = *self.next_id.borrow();
        *self.next_id.borrow_mut() += 1;
        let timer = Timer {
            id,
            callback,
            delay_ms,
            created_at: Instant::now(),
            is_interval: true,
            fired: false,
        };
        self.timers.borrow_mut().insert(id, timer);
        id
    }

    pub fn clear(&self, id: u64) {
        self.timers.borrow_mut().remove(&id);
    }

    /// Get all expired timers
    pub fn get_expired(&self) -> Vec<u64> {
        let now = Instant::now();
        self.timers.borrow()
            .iter()
            .filter(|(_, t)| {
                now.duration_since(t.created_at).as_millis() >= t.delay_ms as u128
            })
            .map(|(id, _)| *id)
            .collect()
    }
}

// Native function wrappers
pub fn js_set_timeout(args: &[JsValue]) -> Result<JsValue, String> {
    if args.len() < 2 {
        return Err("setTimeout needs callback and delay".to_string());
    }
    let delay = args[1].to_number() as u64;
    // Would need to access TimerQueue - in practice, interpreter handles this
    Ok(JsValue::Number(0.0))
}

pub fn js_set_interval(args: &[JsValue]) -> Result<JsValue, String> {
    if args.len() < 2 {
        return Err("setInterval needs callback and delay".to_string());
    }
    Ok(JsValue::Number(0.0))
}

pub fn js_clear_timeout(args: &[JsValue]) -> Result<JsValue, String> {
    Ok(JsValue::Undefined)
}
